apache/lucene-solr

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/cloud/DistributedQueue.java, solr/core/src/java/org/apache/solr/cloud/OverseerTaskProcessor.java, solr/core/src/java/org/apache/solr/cloud/OverseerTaskQueue.java, solr/core/src/test/org/apache/solr/cloud/DistributedQueueTest.java
=> SOLR-9191: OverseerTaskQueue.peekTopN() fatally flawed

solr/CHANGES.txt, solr/solrj/src/java/org/apache/solr/common/ToleratedUpdateError.java
ToleranteUpdateProcessorFactory -> TolerantUpdateProcessorFactory
=> Trivial name spelling fix for SOLR-445

lucene/analysis/common/src/java/org/apache/lucene/analysis/ngram/EdgeNGramTokenFilter.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/ngram/NGramTokenFilter.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/ngram/TestNGramFilters.java
Test and fix for https://issues.apache.org/jira/browse/LUCENE-7630.
=> EdgeNGramTokenFilter drops payloads

README.md
See https://issues.apache.org/jira/browse/LUCENE-7978 for the full description.
=> LUCENE-7978: Improve Readme with ivy-bootstrap and Ivy known workaround

solr/core/src/java/org/apache/solr/cloud/Overseer.java, solr/core/src/java/org/apache/solr/cloud/ZkDistributedQueue.java, solr/core/src/java/org/apache/solr/cloud/overseer/ZkStateWriter.java, solr/core/src/test/org/apache/solr/cloud/OverseerCollectionConfigSetProcessorTest.java, solr/core/src/test/org/apache/solr/cloud/overseer/ZkStateWriterTest.java, solr/solrj/src/java/org/apache/solr/common/cloud/DistributedQueue.java
SOLR-11443: Remove the usage of workqueue for Overseer
=> SOLR-11443: Remove the usage of workqueue for Overseer

solr/webapp/web/css/angular/analysis.css, solr/webapp/web/css/angular/common.css, solr/webapp/web/css/angular/dataimport.css
There are some minor syntax bugs in the CSS files of the Angular UI module.
=> minor syntax corrections in CSS files of Solr's Angular UI

solr/core/src/test/org/apache/solr/update/TestInPlaceUpdatesDistrib.java
Hi there, 
I wrote this bot based on the top 10 most misspelled english words.
(https://blog.oxforddictionaries.com/2016/08/02/corpus-misspellings/)
The bot queries, forks, clones, fixes and commits but I manually create the PRs.
All the best,
Jimmy
=> Fixed Spelling.

solr/core/src/java/org/apache/solr/cloud/api/collections/CategoryRoutedAlias.java, solr/core/src/test/org/apache/solr/update/processor/CategoryRoutedAliasUpdateProcessorTest.java, solr/solrj/src/java/org/apache/solr/client/solrj/request/CollectionAdminRequest.java
make maxCardinality part of createCRACmd constructor para,s and validate CRA params during construction of alias.
=> SOLR-13152

lucene/test-framework/src/java/org/apache/lucene/index/RandomIndexWriter.java
This is a spinn-off from `LUCENE-8700` that is satisfied by IndexWriter#flushNextBuffer.
The idea here is to additionally call flushNextBuffer in RandomIndexWriter for better
test coverage.
=> Concurrently flush next buffer during commit in RandomIndexWriter

solr/CHANGES.txt, solr/core/src/test/org/apache/solr/security/JWTAuthPluginIntegrationTest.java, solr/core/src/test/org/apache/solr/security/hadoop/TestSolrCloudWithHadoopAuthPlugin.java
=> SOLR-13453: Adjust auth metrics asserts in tests after SOLR-13449

solr/core/src/java/org/apache/solr/cloud/autoscaling/AutoScalingHandler.java, solr/core/src/java/org/apache/solr/handler/SchemaHandler.java, solr/core/src/java/org/apache/solr/handler/SolrConfigHandler.java, solr/core/src/java/org/apache/solr/request/SolrRequestInfo.java, solr/core/src/test/org/apache/solr/cloud/autoscaling/AutoScalingHandlerTest.java, solr/core/src/test/org/apache/solr/handler/admin/TestApiFramework.java, solr/solrj/src/java/org/apache/solr/common/util/StrUtils.java, solr/solrj/src/java/org/apache/solr/common/util/Utils.java
autoscaling/diagnostics APIshould be able to give diagnostics output from config pasted as a payload
=> SOLR-13484 autoscaling/diagnostics APIshould be able to give diagnostics output from config pasted as a payload

solr/core/src/java/org/apache/solr/update/TransactionLog.java, solr/core/src/test/org/apache/solr/update/TransactionLogTest.java, solr/solrj/src/java/org/apache/solr/common/util/JavaBinCodec.java
Test are included in https://github.com/apache/lucene-solr/pull/665
=> Fix SOLR-13347

solr/core/src/test/org/apache/solr/util/hll/NumberUtilTest.java
First commit and first contribution, I haven't created any Jira ticket.
I create a test class for an uncovered class I found using the test coverage report.
=> SOLR-8754 add tests for org.apache.solr.util.hll.NumberUtilTest

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/util/IntArrayDocIdSet.java
As described in https://issues.apache.org/jira/browse/LUCENE-8796 .
=> LUCENE-8796: Use exponential search in IntArrayDocIdSetIterator#advance

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/util/bkd/BKDReader.java, lucene/core/src/java/org/apache/lucene/util/bkd/BKDWriter.java, lucene/core/src/java/org/apache/lucene/util/bkd/HeapPointWriter.java, lucene/core/src/test/org/apache/lucene/util/bkd/TestBKD.java
=> [Backport ]LUCENE-8868: New storing strategy for BKD tree leaves with low cardinality

README.md
add table for the build statuses on each platform for more accessible project pulse.
=> SOLR-13537: README Build Status

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/admin/ZookeeperInfoHandler.java
SOLR-13507: Remove support for addr parameter from the /solr/admin/zookeeper endpoint.
=> SOLR-13507: Remove support for addr parameter from the /solr/admin/zookeeper endpoint.

.github/PULL_REQUEST_TEMPLATE.md
Updated the Pull Request template to render checkboxes work.
Add space in between brackets.
Previewed the changes rendered.
- [] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [] I have created a Jira issue and added the issue ID to my pull request title.
- [] I am authorized to contribute this code to the ASF and have removed any code I do not have a license to distribute.
- [] I have developed this patch against the `master` branch.
- [] I have run `ant precommit` and the appropriate test suite.
- [] I have added tests for my changes.
- [] I have added documentation for the Ref Guide (for Solr …
=> updated the pull request template to make checkboxes work

solr/bin/solr, solr/bin/solr.cmd, solr/core/src/java/org/apache/solr/util/ExportTool.java, solr/core/src/java/org/apache/solr/util/SolrCLI.java, solr/core/src/test/org/apache/solr/util/TestExportTool.java, solr/solr-ref-guide/src/solr-control-script-reference.adoc, solr/solrj/src/java/org/apache/solr/common/SolrInputDocument.java
=> SOLR-13682: command line option to export data to a file

solr/core/src/java/org/apache/solr/update/DocumentBuilder.java, solr/core/src/test-files/solr/collection1/conf/schema.xml, solr/core/src/test/org/apache/solr/update/DocumentBuilderTest.java
A regression was introduced as part of the optimizations made in [SOLR-12992](SOLR-12992), which caused the maxChars property to no longer work as expected when indexing via Javabin. Text fields below a certain size limit now are read as ByteArrayUtf8CharSequence instead of Strings, which causes an instanceOf check to fail when attempting to apply the maxChars truncation.
Changed the instanceOf check to use the more generic CharSequence, which is implemented by both String and the new ByteArrayUtf8CharSequence. This will allow the truncation to be applied regardless of type.
This solution was discussed with Noble Paul and others in [SOLR-13699](https://issues.apache.org/jira/browse/SOLR-13699).
Added a test to DocumentBuilder to test the maxChars truncation given both a String value and a …
=> SOLR-13699 - maxChars no longer working on CopyField with Javabin

lucene/CHANGES.txt, lucene/sandbox/src/java/org/apache/lucene/search/NearestNeighbor.java
=> LUCENE-8955: Move compare logic to IntersectVisitor in NearestNeighbor

lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/GraphvizFormatter.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/KoreanAnalyzer.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/KoreanNumberFilter.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/KoreanPartOfSpeechStopFilter.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/KoreanTokenizer.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/BinaryDictionary.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/CharacterDefinition.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/ConnectionCosts.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/TokenInfoFST.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/UserDictionary.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/util/BinaryDictionaryWriter.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/util/CSVUtil.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/util/TokenInfoDictionaryBuilder.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/StringMockResourceLoader.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/TestKoreanAnalyzer.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/TestKoreanNumberFilterFactory.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/TestKoreanPartOfSpeechStopFilterFactory.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/TestKoreanReadingFormFilterFactory.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/TestKoreanTokenizerFactory.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/dict/TokenInfoDictionaryTest.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/dict/UserDictionaryTest.java
This is the PR for refactoring of the Nori(Korean) Analyzer.
There are no logical changes in the Nori itself.
Please check the following link:
https://issues.apache.org/jira/browse/LUCENE-8954
=> LUCENE-8954: refactor Nori analyzer

lucene/misc/src/test/org/apache/lucene/search/TestDiversifiedTopDocsCollector.java
TestDiversifiedTopDocsCollector.testInvalidArguments should check for
exceptions and corresponding messages, post LUCENE-8905
=> Harden Up TestDiversifiedTopDocsCollector

.github/workflows/ant.yml
=> SOLR-13753: ant precommit GitHub action for all PRs

lucene/CHANGES.txt, lucene/sandbox/src/java/org/apache/lucene/document/FloatPointNearestNeighbor.java, lucene/sandbox/src/test/org/apache/lucene/document/TestFloatPointNearestNeighbor.java
The algorithm uses now the exact minimum distance between a point and a bounding rectangle to navigate the tree.
=> LUCENE-8976: Use exact distance between point and bounding rectangle in FloatPointNearestNeighbor

solr/CHANGES.txt, solr/contrib/prometheus-exporter/bin/solr-exporter, solr/contrib/prometheus-exporter/bin/solr-exporter.cmd, solr/solr-ref-guide/src/monitoring-solr-with-prometheus-and-grafana.adoc
Cherrypick from master (c7f84873280d7d60ebdfff72e0c72fb60cf24e69)
* SOLR-13773: Prometheus Exporter GC and Heap options
* Adding info to the ref-guide.
=> SOLR-13773: Prometheus Exporter GC and Heap options (#887)

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/security/AuthorizationContext.java, solr/core/src/java/org/apache/solr/security/RuleBasedAuthorizationPlugin.java
Adds log messages to RuleBasedAuthorizationPlugin to aid in debugging.
Increase log level to DEBUG or TRACE for org.apache.solr.security.RuleBasedAuthorizationPlugin for more helpful output.
N/A - logging change only
=> SOLR-13638: Add debug,trace RBAP logging

lucene/CHANGES.txt, lucene/queries/src/java/org/apache/lucene/queries/mlt/MoreLikeThis.java, lucene/queries/src/test/org/apache/lucene/queries/mlt/TestMoreLikeThis.java, solr/CHANGES.txt
Fix MLT not to be biased for fields with few docs
Use the per field doc count
Tests with uncommon and common fields
- [x ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x ] I have created a Jira issue and added the issue ID to my pull request title.
- [ x] I am authorized to contribute this code to the ASF and have removed any code I do not have a license to distribute.
- [ x] I have developed this patch against the `master` branch.
- [x ] I have run `ant precommit` and the appropriate test suite.
- [x ] I have added tests for my changes.
- [ Not required] I have added documentation for the [Ref …
=> LUCENE-8984: MoreLikeThis MLT is biased for uncommon fields

lucene/CHANGES.txt, lucene/queries/src/java/org/apache/lucene/queries/mlt/MoreLikeThis.java, lucene/queries/src/test/org/apache/lucene/queries/mlt/TestMoreLikeThis.java, solr/CHANGES.txt
=> LUCENE-8984: MoreLikeThis MLT is biased for uncommon fields (#871)

solr/solr-ref-guide/src/solr-system-requirements.adoc
Fixing the link to Lucene Java Bugs page
Link updated
N/A
=> Fixing link to Lucene Java Bugs page

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java, lucene/core/src/java/org/apache/lucene/search/LRUQueryCache.java, lucene/core/src/java/org/apache/lucene/search/QueryCache.java, lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java, lucene/core/src/test/org/apache/lucene/search/TestLRUQueryCache.java
Reverts apache/lucene-solr#815
=> Revert "LUCENE-8213: Introduce Asynchronous Caching in LRUQueryCache"

solr/core/src/test/org/apache/solr/cloud/api/collections/AssignTest.java
Looks like the merge when the original PR was put up broke test compilation.  Here's the simple fix.
=> SOLR-13101: fix test compilation

solr/core/src/test/org/apache/solr/cloud/SplitShardTest.java
enhancement to the test case to allow more indexing threads to increase the chance of test failure.  On my laptop, this caused the test to fail almost 50% of the time with 4 threads.  Also changed the failure code to speed up checking what docs were missing (avoid a query-per-doc)
=> SOLR-13815: enhance live split test to fail more often

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/BaseCompositeReader.java, lucene/core/src/java/org/apache/lucene/index/IndexReader.java, lucene/core/src/test/org/apache/lucene/index/TestFilterDirectoryReader.java
See [LUCENE-9003](https://issues.apache.org/jira/browse/LUCENE-9003) for background.
=> LUCENE-9003: Compute numDocs() lazily.

solr/CHANGES.txt, solr/solrj/ivy.xml, solr/solrj/src/java/org/apache/solr/common/util/ReflectMapWriter.java
SOLR-13841:Add jackson databind annotations to SolrJ classpath
=> SOLR-13841: Add jackson databind annotations to SolrJ classpath

solr/solr-ref-guide/src/uploading-data-with-solr-cell-using-apache-tika.adoc
Tweak How to use Solr Cell doc
Simplifying parameters in initial example query.
Tested in Solr 8.2
- [x ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x ] I have created a Jira issue and added the issue ID to my pull request title.
- [x ] I am authorized to contribute this code to the ASF and have removed any code I do not have a license to distribute.
- [ X] I have developed this patch against the `master` branch.
- [ X] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).
=> SOLR-13848 tweak documentation to be clearer about uprefix

solr/CHANGES.txt, solr/solrj/src/java/org/apache/solr/common/util/NamedList.java, solr/solrj/src/test/org/apache/solr/common/util/NamedListTest.java
NamedList.toString() differs in format from AbstractMap.toString() when the NamedList has 2 or more entries, in that there's no space after each comma between entries.
Added a space after the comma.
Added NamedListTest.testToString(), which covers toString() for the cases with 0, 1 and 2 entries. (The method currently seems to have no test coverage.)
=> SOLR-13783: Add space after comma in NamedList.toString()

solr/core/src/java/org/apache/solr/filestore/PackageStoreAPI.java, solr/core/src/java/org/apache/solr/servlet/HttpSolrCall.java, solr/core/src/java/org/apache/solr/servlet/SolrRequestParsers.java, solr/solr-ref-guide/src/solr-packages.adoc, solr/solr-ref-guide/src/the-well-configured-solr-instance.adoc
ref guide and some `curl` friendly changes
=> SOLR-13822 Isolated Classloading from packages

lucene/core/src/java/org/apache/lucene/codecs/lucene84/Lucene84PostingsReader.java
I also cherry-picked LUCENE-8901 (lazy loading of freq blocks) for BlockDocsImpactsEnum.
=> LUCENE-9056: Fewer conditionals in #advance.

solr/core/src/test/org/apache/solr/store/blob/SharedStorageSplitTest.java
New live split test for shared storage.
Unfortunately, it currently fails.
=> SOLR-13813: add test for shared storage live split

solr/core/src/java/org/apache/solr/core/CorePropertiesLocator.java
There was a missing space in error message
=> Minor - Fix error message

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/security/AuditEvent.java, solr/core/src/test/org/apache/solr/security/AuditLoggerPluginTest.java
See https://issues.apache.org/jira/browse/SOLR-13969
Added tests for the new getters
=> SOLR-13969: Clean up and document AuditEvent API

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java, lucene/core/src/java/org/apache/lucene/search/LRUQueryCache.java, lucene/core/src/java/org/apache/lucene/search/QueryCache.java, lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java, lucene/core/src/test/org/apache/lucene/search/TestLRUQueryCache.java
Reverts apache/lucene-solr#916
=> Revert "LUCENE-8213: Asynchronous Caching in LRUQueryCache"

solr/core/src/test/org/apache/solr/store/blob/SharedStorageSplitTest.java
Cleans up the remaining sleeps in the shared storage split test and replaces them with countdown latches.
=> SOLR-13813: change test sleeps to latches

solr/CHANGES.txt, solr/solrj/src/java/org/apache/solr/common/annotation/SolrSingleThreaded.java, solr/solrj/src/java/org/apache/solr/common/annotation/SolrThreadSafe.java
=> SOLR-13998: Add thread safety annotations to classes (#1053)

lucene/core/src/java/org/apache/lucene/analysis/CharacterUtils.java, lucene/core/src/test/org/apache/lucene/analysis/TestCharacterUtils.java
Assertions in CharacterUtils are not consistent with javadocs 
Fix assertion
Added a testcase that will in current implementation.
- `toLowerCase` and `toUpperCase` with non-zero offset.
=> LUCENE-9085: fix assertion in CharacterUtils

solr/solr-ref-guide/src/requestdispatcher-in-solrconfig.adoc
Incorrect documentation for handleSelect and qt param.
Short documentation update
N.A.
- [ Y] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ Y] I have created a Jira issue and added the issue ID to my pull request title.
- [ Y] I am authorized to contribute this code to the ASF and have removed any code I do not have a license to distribute.
- [Y ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [Y ] I have developed this patch against the `master` …
=> [SOLR-14029] Documentation updated

solr/solr-ref-guide/src/stream-source-reference.adoc
Added missing parameter in solr-ref-guide for stream-source-reference under 'topic parameters'.
Fix documentation.
Not applicable
- [*] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [*] I have created a Jira issue and added the issue ID to my pull request title.
- [*] I am authorized to contribute this code to the ASF and have removed any code I do not have a license to distribute.
- [*] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [*] I have …
=> SOLR-13999: Added missing parameter under 'topic parameters'

solr/common-build.xml, solr/core/src/test/org/apache/solr/cloud/hdfs/HdfsTestUtil.java
https://issues.apache.org/jira/browse/SOLR-14053
=> Don't start hdfs on windows. Remove tests.disableHdfs.

solr/core/src/java/org/apache/solr/filestore/PackageStoreAPI.java, solr/core/src/java/org/apache/solr/pkg/PackageAPI.java, solr/core/src/test/org/apache/solr/filestore/TestDistribPackageStore.java
I wish this to be included in 8.4. There are so many security holes in Solr and we want to play extra safe
=> SOLR-14087 disable package store API if -Denable.packages not set to true

solr/solr-ref-guide/build.xml, solr/solr-ref-guide/src/_config.yml.template
See https://issues.apache.org/jira/browse/SOLR-14146
=> SOLR-14146: Zookeeper version not resolved in RefGuide

lucene/ivy-versions.properties, solr/core/ivy.xml
Updating a reference to a JAR to keep consistent with SFDC downstream.
Modified JAR path.
N/A
=> SOLR-13101: Fix the gson version reference

solr/solr-ref-guide/src/major-changes-in-solr-8.adoc, solr/solr-ref-guide/src/major-changes-in-solr-9.adoc
Wrong word slipped in, but is properly spelled so autocorrect won't see it.
Fixed docs.
n/a
- [ X] I have developed this patch against the `master` branch.
- [X ] I have run `ant precommit` and the appropriate test suite.
- [ X] I have added documentation for the [Ref …
=> SOLR-14153 Word choice should be "starting", not "staring"

lucene/core/src/java/org/apache/lucene/codecs/blocktree/BlockTreeTermsWriter.java
I'm not expecting any speedups, this is mostly for consistency.
=> BlockTreeTermsWriter should compute prefix lengths using Arrays#mismatch.

solr/core/src/java/org/apache/solr/store/blob/client/BlobCoreMetadata.java, solr/core/src/java/org/apache/solr/store/blob/client/BlobCoreMetadataBuilder.java, solr/core/src/java/org/apache/solr/store/blob/metadata/CorePushPull.java, solr/core/src/java/org/apache/solr/store/blob/metadata/ServerSideMetadata.java, solr/core/src/java/org/apache/solr/store/blob/metadata/SharedStoreResolutionUtil.java, solr/core/src/java/org/apache/solr/store/blob/process/BlobDeleterTask.java, solr/core/src/java/org/apache/solr/store/blob/process/CorePullTask.java, solr/core/src/java/org/apache/solr/store/blob/process/CorePusher.java, solr/core/src/java/org/apache/solr/store/blob/util/BlobStoreUtils.java, solr/core/src/java/org/apache/solr/store/shared/SharedCoreConcurrencyController.java, solr/core/src/test/org/apache/solr/store/blob/metadata/CorePushPullTest.java, solr/core/src/test/org/apache/solr/store/blob/metadata/SharedStoreResolutionUtilTest.java, solr/core/src/test/org/apache/solr/store/blob/util/BlobStoreUtilsTest.java
SOLR-13932: Review directory locking and Blob interactions
Take into account all local files in a local index to avoid conflict with files pulled from Blob.
Do not make local copy of directory for pushing to Blob.
Minor changes.
=> SOLR-13932 Review directory locking and Blob interactions

solr/solr-ref-guide/src/schema-api.adoc
Fix api v2 sample urls to be solrcloud instead of standalone.
text change.
n/a
- [ X] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ X] I am authorized to contribute this code to the ASF and have removed any code I do not have a license to distribute.
- [ X] I have developed this patch against the `master` branch.
- [ …
=> Update documentation to fix SOLR-13927

solr/solr-ref-guide/src/post-tool.adoc
Provide example for windows users in documentation
Provide example for windows users in documentation
Verified formatting by using ascii doc plugin in vscode
- [ x] I have created a Jira issue and added the issue ID to my pull request title.
- [x ] I am authorized to contribute this code to the ASF and have removed any code I do not have a license to distribute.
- [x ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x ] I have developed this patch against the `master` branch.
- [x ] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr- …
=> SOLR-13934: Documentation for windows users

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/util/bkd/BKDWriter.java, lucene/core/src/test/org/apache/lucene/util/bkd/TestBKD.java
See https://issues.apache.org/jira/browse/LUCENE-9144
=> LUCENE-9144: Fix error message on OneDimensionBKDWriter

lucene/core/src/java/org/apache/lucene/util/packed/DirectMonotonicWriter.java, lucene/core/src/test/org/apache/lucene/util/packed/TestDirectMonotonic.java
See https://issues.apache.org/jira/browse/LUCENE-9161
=> LUCENE-9161: DirectMonotonicWriter checks for overflows.

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/store/hdfs/HdfsDirectory.java, solr/core/src/test/org/apache/solr/store/hdfs/HdfsDirectoryTest.java
JIRA: https://issues.apache.org/jira/browse/SOLR-14242
=> SOLR-14242: HdfsDirectory#createTempOutput.

.github/workflows/gradle-precommit.yml
This adds a gradle precommit action w/ Java11 for all branches.
=> LUCENE-9146: Create gradle precommit action

lucene/core/src/test/org/apache/lucene/search/TestDoubleValuesSource.java
=> LUCENE-9216: Make sure we index LEAST_DOUBLE_VALUE

lucene/core/src/java/org/apache/lucene/geo/Point2D.java, lucene/core/src/test/org/apache/lucene/geo/TestPoint2D.java
return the right relation when point inside a triangle.
=> LUCENE-9226: Return CELL_CROSSES_QUERY when point inside the triangle

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/document/XYDocValuesField.java, lucene/core/src/java/org/apache/lucene/document/XYDocValuesPointInGeometryQuery.java, lucene/core/src/java/org/apache/lucene/document/XYPointDistanceComparator.java, lucene/core/src/java/org/apache/lucene/document/XYPointField.java, lucene/core/src/java/org/apache/lucene/document/XYPointInGeometryQuery.java, lucene/core/src/java/org/apache/lucene/document/XYPointSortField.java, lucene/core/src/test/org/apache/lucene/search/TestXYDocValuesQueries.java, lucene/core/src/test/org/apache/lucene/search/TestXYPointDistanceSort.java, lucene/core/src/test/org/apache/lucene/search/TestXYPointQueries.java, lucene/test-framework/src/java/org/apache/lucene/geo/BaseXYPointTestCase.java, lucene/test-framework/src/java/org/apache/lucene/geo/ShapeTestUtil.java
Adaptation of LatLonPoint to generic cartesian space.
=> LUCENE-9238: Add new XYPointField, queries and sorting capabilities

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/cloud/SolrZkServer.java
See https://issues.apache.org/jira/browse/SOLR-14114
=> SOLR-14114: Add WARN to Solr log that embedded ZK is not supported in prod

lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/GraphvizFormatter.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/KoreanAnalyzer.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/KoreanNumberFilter.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/KoreanPartOfSpeechStopFilter.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/KoreanTokenizer.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/BinaryDictionary.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/CharacterDefinition.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/ConnectionCosts.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/TokenInfoFST.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/UserDictionary.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/util/BinaryDictionaryWriter.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/util/CSVUtil.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/util/TokenInfoDictionaryBuilder.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/StringMockResourceLoader.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/TestKoreanAnalyzer.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/TestKoreanNumberFilterFactory.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/TestKoreanPartOfSpeechStopFilterFactory.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/TestKoreanReadingFormFilterFactory.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/TestKoreanTokenizerFactory.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/dict/TokenInfoDictionaryTest.java, lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/dict/UserDictionaryTest.java
There is a lint error in patch.
Sorry for confusing.
=> Revert "LUCENE-8954: refactor Nori analyzer"

solr/core/src/test/org/apache/solr/cloud/autoscaling/TestPolicyCloud.java
Trivial fix of a test resource leak
=> Fix resource leak in TestPolicyCloud

solr/core/src/test/org/apache/solr/cloud/RoutingToNodesWithPropertiesTest.java, solr/core/src/test/org/apache/solr/cloud/autoscaling/MetricTriggerTest.java
Just closes some CloudManager instances in tests
=> Add try-with-resources to CloudManager in tests

solr/solr-ref-guide/src/config-api.adoc, solr/solr-ref-guide/src/stream-api.adoc, solr/solr-ref-guide/src/stream-decorator-reference.adoc, solr/solr-ref-guide/src/streaming-expressions.adoc
Add expressible to the list of config supported methods.
updated docs.  
Locally built ref guide.  I manually tested the commands.
- [ X] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ X] I have developed this patch against the `master` branch.
- [ X] I have added documentation for the [Ref …
=> SOLR-14284 add expressible support to list, and add example of removing a component

solr/core/src/java/org/apache/solr/handler/StreamHandler.java
fix typo in message in response to querying /stream.
Typo fix.
PLEASE NOTE that SOLR-14284 addes documentation on the /stream api, and has in the documentation the misspelled version of the word, which should also be updated.
manual test.
- [ X] I have developed this …
=> SOLR-14294 fix typo in message

build.gradle, gradle/jar-manifest.gradle, gradle/testing/randomization.gradle, gradle/validation/git-status.gradle
Suggested patch. I did try to make it similar to what ant produces at the moment but I didn't verify each and every subproject so it'd be good if somebody had a look.
=> LUCENE-9301: add a manifest entries to JARs.

solr/core/src/java/org/apache/solr/core/ZkContainer.java, solr/solrj/src/java/org/apache/solr/client/solrj/impl/SolrClientNodeStateProvider.java
When starting an embedded zk server, if we can detect that we are using https, set the urlScheme cluster property accordingly.
=> zkRun+https

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/security/AuthenticationPlugin.java, solr/core/src/java/org/apache/solr/security/BasicAuthPlugin.java, solr/core/src/java/org/apache/solr/security/HadoopAuthPlugin.java, solr/core/src/java/org/apache/solr/security/JWTAuthPlugin.java, solr/core/src/java/org/apache/solr/security/KerberosPlugin.java, solr/core/src/java/org/apache/solr/security/PKIAuthenticationPlugin.java, solr/core/src/test/org/apache/solr/cloud/TestAuthenticationFramework.java, solr/core/src/test/org/apache/solr/security/MockAuthenticationPlugin.java
https://issues.apache.org/jira/browse/SOLR-14420
=> SOLR-14420 Declare ServletRequests as HttpRequests

solr/solr-ref-guide/src/authentication-and-authorization-plugins.adoc, solr/solr-ref-guide/src/securing-solr.adoc
=> Move audit logging docs under AAA section

solr/solr-ref-guide/src/command-line-utilities.adoc
typo in `cloud-scripts` path
Fix
=> Fix typo in `cloud-scripts` path

build.gradle, lucene/CHANGES.txt, lucene/common-build.xml
TODO: Use task configuration avoidance also in Lucene/Solr build for speedup
=> LUCENE-9347: Add support for forbiddenapis 3.0

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/metrics/reporters/solr/SolrShardReporter.java, solr/core/src/test-files/solr/solr-solrreporter.xml, solr/core/src/test/org/apache/solr/metrics/reporters/solr/SolrCloudReportersTest.java
https://issues.apache.org/jira/browse/SOLR-14433#
Now includes TLOG and UPDATE./update.
These were small bugs to begin with but from user perspective this is an incremental improvement.
CC @sigram
=> SOLR-14433: Improve SolrShardReporter default metrics list

solr/core/src/java/org/apache/solr/search/GraphTermsQParserPlugin.java
No WeightOrDocIdSet; no override of bulkScorer
@joel-bernstein can you please look.  I happened to be viewing this code and didn't understand why the complexity was there (and no comments justifying it either).
=> Solr GraphTermsQParser simplifications

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/metrics/SolrMetricManager.java, solr/core/src/java/org/apache/solr/security/CertAuthPlugin.java, solr/core/src/java/org/apache/solr/servlet/SolrDispatchFilter.java, solr/core/src/test/org/apache/solr/security/CertAuthPluginTest.java, solr/solr-ref-guide/src/authentication-and-authorization-plugins.adoc, solr/solr-ref-guide/src/cert-authentication-plugin.adoc, solr/solr-ref-guide/src/securing-solr.adoc, solr/webapp/web/js/angular/controllers/login.js, solr/webapp/web/partials/login.html
https://issues.apache.org/jira/browse/SOLR-14440
=> SOLR-14440 Cert Auth plugin

solr/CHANGES.txt, solr/bin/solr, solr/bin/solr.cmd, solr/bin/solr.in.cmd, solr/bin/solr.in.sh, solr/core/src/java/org/apache/solr/search/GraphTermsQParserPlugin.java, solr/core/src/java/org/apache/solr/servlet/LoadAdminUiServlet.java
I added a system property to allow users to disable the Solr Admin UI on start.
I added this property, which accepts a boolean value, to SOLR_START_OPTS and START_OPTS.
Not easily testable in the current project.
=> SOLR-14014 PR Against Master

lucene/CHANGES.txt, lucene/expressions/src/java/org/apache/lucene/expressions/ExpressionValueSource.java, lucene/expressions/src/test/org/apache/lucene/expressions/TestExpressionValueSource.java
[LUCENE-9362](https://issues.apache.org/jira/browse/LUCENE-9362): ExpressionValuesSource does not actually rewrite itself due to small mistake in the check of inner rewrites.
`changed |= (rewritten[i] == variables[i]);`
should be changed to
`changed |= (rewritten[i] != variables[i]);`
I added a test that checks that the ExpressionValueSource was rewritten when the inner ValueSource was rewritten, and vice versa
=> LUCENE-9362: Fix rewriting check in ExpressionValueSource

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/admin/ZookeeperStatusHandler.java, solr/core/src/test/org/apache/solr/handler/admin/ZookeeperStatusHandlerTest.java
See https://issues.apache.org/jira/browse/SOLR-14463
=> SOLR-14463: Solr Admin ZkStatus page now works with ZK 3.6

lucene/CHANGES.txt, lucene/MIGRATE.md
9.0 enhancement added to changes
=> Lucene-9336: Changes.txt addition for RegExp enhancements

dev-tools/scripts/poll-mirrors.py, lucene/CHANGES.txt
see https://issues.apache.org/jira/browse/LUCENE-9288
=> LUCENE-9288: poll_mirrors.py release script can handle HTTPS mirrors

solr/core/src/java/org/apache/solr/cloud/Overseer.java, solr/core/src/java/org/apache/solr/cloud/ZkDistributedQueue.java, solr/solrj/src/java/org/apache/solr/common/params/CollectionParams.java
Improve Overseer Javadoc.
Added/modified Javadoc on Overseer, ClusterStateUpdater, ZkDistributedQueue and CollectionParams.CollectionAction
N/A
=> SOLR-14473: Improve Overseer Javadoc

lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java
Made RegExp internal fields public final to allow external classes to render eg English explanations of pattern logic
Backport of https://github.com/apache/lucene-solr/pull/1521
=> Lucene-9371: Allow external access to RegExp's parsed structure (#1521)

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/component/QueryComponent.java, solr/core/src/java/org/apache/solr/search/QueryCommand.java, solr/core/src/java/org/apache/solr/search/QueryResultKey.java, solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java, solr/core/src/test/org/apache/solr/TestDistributedSearch.java, solr/core/src/test/org/apache/solr/TestGroupingSearch.java, solr/core/src/test/org/apache/solr/core/QueryResultKeyTest.java, solr/core/src/test/org/apache/solr/request/TestFaceting.java, solr/core/src/test/org/apache/solr/search/SolrIndexSearcherTest.java, solr/core/src/test/org/apache/solr/search/TestCollapseQParserPlugin.java, solr/solrj/src/java/org/apache/solr/common/params/CommonParams.java, solr/solrj/src/test/org/apache/solr/common/params/CommonParamsTest.java
Rename the parameter used to define the number of hits to count
=> SOLR-13289: minExactHits -> minExactCount

solr/solr-ref-guide/src/common-query-parameters.adoc
Reference guide changes for SOLR-13289
=> SOLR-13289: Add Refguide changes

solr/solr-ref-guide/src/metrics-reporting.adoc
=> ref_guide - metrics reporting - small typo

solr/CHANGES.txt, solr/bin/solr, solr/bin/solr.cmd, solr/bin/solr.in.cmd, solr/bin/solr.in.sh
-XX:+DisableExplicitGC disables any explicit calls to System.gc()
In many cases, if an explicit GC is invoked, a potential premature garbage collection might degrade application's performance.
=> SOLR-13492: Ensure explicit GCs are concurrent by default

solr/core/src/test/org/apache/solr/cloud/autoscaling/AutoAddReplicasIntegrationTest.java, solr/solr-ref-guide/src/solrcloud-autoscaling-triggers.adoc
fix action name in doc and test. 
Change the execute action to be `execute_plan`
Fixes existing test
=> SOLR-14578: Update solrcloud-autoscaling-triggers.adoc and test

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java, solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreaker.java, solr/core/src/java/org/apache/solr/util/circuitbreaker/MemoryCircuitBreaker.java, solr/core/src/test/org/apache/solr/handler/component/DebugComponentTest.java, solr/core/src/test/org/apache/solr/util/TestCircuitBreaker.java, solr/example/files/conf/solrconfig.xml
This commit is a follow up to the original commit and adds more documentation and adds timing information for circuit breaker check only if circuit breakers are enabled
=> SOLR-14588: Follow Up Fixes and Documentation

solr/solrj/src/java/org/apache/solr/client/solrj/cloud/autoscaling/PolicyHelper.java, solr/solrj/src/test/org/apache/solr/client/solrj/cloud/autoscaling/TestPolicy.java
Cherry picked from 25428013fb0ed8f8fdbebdef3f1d65dea77129c2
=> SOLR-14462: cache more than one autoscaling session

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/schema/RankField.java, solr/core/src/java/org/apache/solr/search/QParserPlugin.java, solr/core/src/java/org/apache/solr/search/RankQParserPlugin.java, solr/core/src/test-files/solr/collection1/conf/schema-rank-fields.xml, solr/core/src/test-files/solr/collection1/conf/schema15.xml, solr/core/src/test/org/apache/solr/schema/RankFieldTest.java, solr/core/src/test/org/apache/solr/search/QueryEqualityTest.java, solr/core/src/test/org/apache/solr/search/RankQParserPluginTest.java, solr/server/solr/configsets/_default/conf/managed-schema
This implements the "Approach 2"  suggested by Varun here: https://github.com/apache/lucene-solr/pull/1616#discussion_r446404384
=> SOLR-14590 : Add support for Lucene's FeatureField in Solr

solr/solr-ref-guide/src/kerberos-authentication-plugin.adoc
Applying fix from Andras Salamon.  Thanks!
=> SOLR-14639 update the name of the deletegation method to be correct

solr/webapp/web/index.html
Replacement branch for https://github.com/apache/lucene-solr/pull/1633.
=> SOLR-14422 progressive render load main admin page

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/RegexpQuery.java, lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java, lucene/core/src/test/org/apache/lucene/search/TestRegexpQuery.java, lucene/core/src/test/org/apache/lucene/util/automaton/TestRegExp.java
Backport of 887fe4c83d4114c6238265ca7f05aa491525af9d
=> LUCENE-9386 add case insensitive RegExp matching option

lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java
Constructor passed the wrong flag
=> LUCENE-9386 Bug fix for 8x backport

lucene/core/src/java/overview.html
Add a missing semicolon in the documentation.
self-explanatory
Does not apply.
=> LUCENE-9429 missing semicolon in overview.html

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/admin/ZookeeperStatusHandler.java, solr/core/src/test/org/apache/solr/common/cloud/ZkDynamicConfigTest.java, solr/solrj/src/java/org/apache/solr/common/cloud/ZkDynamicConfig.java
See https://issues.apache.org/jira/browse/SOLR-14671
=> SOLR-14671: Parsing dynamic ZK config sometimes cause NuberFormatException

solr/CHANGES.txt, solr/solr-ref-guide/src/major-changes-in-solr-9.adoc
This is just the CHANGES.txt entries, including upgrade notes
CC @MarcusSorealheis
=> SOLR-14702: Add Upgrade Notes and CHANGES entry

lucene/suggest/src/java/org/apache/lucene/search/spell/SuggestWord.java
This is simply an obvious toString impl on SuggestWord.
=> LUCENE spell: Implement SuggestWord.toString

solr/core/src/test/org/apache/solr/servlet/TestRequestRateLimiter.java
This commit adds higher data size and load in the test path. Also improves
the asserts that are performed.
=> Harden RequestRateLimiter Tests

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/cloud/autoscaling/sim/SimNodeStateProvider.java, solr/core/src/java/org/apache/solr/cloud/autoscaling/sim/SimScenario.java, solr/solr-ref-guide/src/solr-upgrade-notes.adoc, solr/solrj/src/java/org/apache/solr/client/solrj/cloud/autoscaling/Clause.java
forward-porting #1716 for https://issues.apache.org/jira/browse/SOLR-14706
=> SOLR-14706: Fix support for default autoscaling policy (8x forward-port)

lucene/CHANGES.txt, lucene/highlighter/build.xml, lucene/highlighter/src/java/org/apache/lucene/search/matchhighlight/BreakIteratorShrinkingAdjuster.java, lucene/highlighter/src/java/org/apache/lucene/search/matchhighlight/CharSequenceIterator.java, lucene/highlighter/src/java/org/apache/lucene/search/matchhighlight/MatchRegionRetriever.java, lucene/highlighter/src/java/org/apache/lucene/search/matchhighlight/OffsetRange.java, lucene/highlighter/src/java/org/apache/lucene/search/matchhighlight/OffsetsFromMatchIterator.java, lucene/highlighter/src/java/org/apache/lucene/search/matchhighlight/OffsetsFromPositions.java, lucene/highlighter/src/java/org/apache/lucene/search/matchhighlight/OffsetsFromTokens.java, lucene/highlighter/src/java/org/apache/lucene/search/matchhighlight/OffsetsFromValues.java, lucene/highlighter/src/java/org/apache/lucene/search/matchhighlight/OffsetsRetrievalStrategy.java, lucene/highlighter/src/java/org/apache/lucene/search/matchhighlight/OffsetsRetrievalStrategySupplier.java, lucene/highlighter/src/java/org/apache/lucene/search/matchhighlight/Passage.java, lucene/highlighter/src/java/org/apache/lucene/search/matchhighlight/PassageAdjuster.java, lucene/highlighter/src/java/org/apache/lucene/search/matchhighlight/PassageFormatter.java, lucene/highlighter/src/java/org/apache/lucene/search/matchhighlight/PassageSelector.java, lucene/highlighter/src/java/org/apache/lucene/search/matchhighlight/package-info.java, lucene/highlighter/src/test/org/apache/lucene/search/matchhighlight/AsciiMatchRangeHighlighter.java, lucene/highlighter/src/test/org/apache/lucene/search/matchhighlight/MissingAnalyzer.java, lucene/highlighter/src/test/org/apache/lucene/search/matchhighlight/TestMatchRegionRetriever.java, lucene/highlighter/src/test/org/apache/lucene/search/matchhighlight/TestPassageSelector.java
Separated components from previous PR. Already reviewed by @romseygeek
=> LUCENE-9463: Query match region retrieval component, passage scoring and formatting

gradle/validation/forbidden-apis.gradle
See issue https://issues.apache.org/jira/browse/LUCENE-9479
=> LUCENE-9479: Forbiddenapis & Gradle: Add commons-io bundled signatures

solr/core/src/java/org/apache/solr/core/SolrConfig.java, solr/core/src/java/org/apache/solr/core/SolrCore.java, solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java, solr/core/src/java/org/apache/solr/util/circuitbreaker/CPUCircuitBreaker.java, solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreaker.java, solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreakerManager.java, solr/core/src/java/org/apache/solr/util/circuitbreaker/MemoryCircuitBreaker.java, solr/core/src/resources/EditableSolrConfigAttributes.json, solr/core/src/test-files/solr/collection1/conf/solrconfig-memory-circuitbreaker.xml, solr/core/src/test/org/apache/solr/core/SolrCoreTest.java, solr/core/src/test/org/apache/solr/core/TestConfigOverlay.java, solr/core/src/test/org/apache/solr/util/TestCircuitBreaker.java, solr/example/files/conf/solrconfig.xml, solr/solr-ref-guide/src/circuit-breakers.adoc, solr/solr-ref-guide/src/query-settings-in-solrconfig.adoc
This commit refactors circuit breaker configurations to use PluginInfo and reduce the footprint on SolrConfig.
=> Update Circuit Breaker configured as a standard plugin

lucene/core/src/java/org/apache/lucene/index/ExitableDirectoryReader.java, lucene/core/src/java/org/apache/lucene/search/TimeLimitingCollector.java
And cross-link javadocs with TimeLimitingCollector
=> LUCENE ExitableReaderException public constructor

solr/cloud-dev/cloud.sh
Initial cut at this, only tested on mac osx so far.
=> SOLR-14704 add download option to cloud.sh

lucene/core/src/java/org/apache/lucene/search/DoubleValuesSource.java, lucene/core/src/java/org/apache/lucene/search/LongValuesSource.java, lucene/core/src/java/org/apache/lucene/search/Sort.java, lucene/core/src/test/org/apache/lucene/search/TestDoubleValuesSource.java, lucene/core/src/test/org/apache/lucene/search/TestLongValuesSource.java, lucene/core/src/test/org/apache/lucene/search/TestSort.java
https://issues.apache.org/jira/browse/LUCENE-9451
=> LUCENE-9451 Sort.rewrite does not always return this when unchanged

lucene/CHANGES.txt, lucene/backward-codecs/src/test/org/apache/lucene/codecs/lucene60/Lucene60PointsWriter.java, lucene/backward-codecs/src/test/org/apache/lucene/codecs/lucene60/TestLucene60PointsFormat.java, lucene/codecs/src/java/org/apache/lucene/codecs/simpletext/SimpleTextBKDWriter.java, lucene/codecs/src/java/org/apache/lucene/codecs/simpletext/SimpleTextPointsWriter.java, lucene/core/src/java/org/apache/lucene/codecs/lucene86/Lucene86PointsWriter.java, lucene/core/src/java/org/apache/lucene/index/PointValues.java, lucene/core/src/java/org/apache/lucene/util/bkd/BKDConfig.java, lucene/core/src/java/org/apache/lucene/util/bkd/BKDRadixSelector.java, lucene/core/src/java/org/apache/lucene/util/bkd/BKDReader.java, lucene/core/src/java/org/apache/lucene/util/bkd/BKDWriter.java, lucene/core/src/java/org/apache/lucene/util/bkd/HeapPointReader.java, lucene/core/src/java/org/apache/lucene/util/bkd/HeapPointWriter.java, lucene/core/src/java/org/apache/lucene/util/bkd/MutablePointsReaderUtils.java, lucene/core/src/java/org/apache/lucene/util/bkd/OfflinePointReader.java, lucene/core/src/java/org/apache/lucene/util/bkd/OfflinePointWriter.java, lucene/core/src/test/org/apache/lucene/codecs/lucene86/TestLucene86PointsFormat.java, lucene/core/src/test/org/apache/lucene/search/TestLatLonPointQueries.java, lucene/core/src/test/org/apache/lucene/search/TestPointQueries.java, lucene/core/src/test/org/apache/lucene/util/bkd/Test2BBKDPoints.java, lucene/core/src/test/org/apache/lucene/util/bkd/TestBKD.java, lucene/core/src/test/org/apache/lucene/util/bkd/TestBKDRadixSelector.java, lucene/core/src/test/org/apache/lucene/util/bkd/TestBKDRadixSort.java, lucene/core/src/test/org/apache/lucene/util/bkd/TestMutablePointsReaderUtils.java, lucene/test-framework/src/java/org/apache/lucene/index/RandomCodec.java
=> [Backport] LUCENE-9292: Refactor BKD point configuration into its own class (#1697)

solr/solrj/src/java/org/apache/solr/common/params/FacetParams.java
https://issues.apache.org/jira/browse/SOLR-14831
=> SOLR-14831: remove deprecated-and-unused "facet.distrib.mco" constant

solr/core/src/java/org/apache/solr/cloud/api/collections/BackupCmd.java, solr/core/src/java/org/apache/solr/cloud/api/collections/RestoreCmd.java, solr/core/src/java/org/apache/solr/core/CoreContainer.java, solr/core/src/java/org/apache/solr/core/backup/repository/BackupRepository.java, solr/core/src/java/org/apache/solr/handler/ReplicationHandler.java, solr/core/src/java/org/apache/solr/handler/admin/BackupCoreOp.java, solr/core/src/java/org/apache/solr/handler/admin/CollectionsHandler.java, solr/core/src/java/org/apache/solr/handler/admin/RestoreCoreOp.java, solr/core/src/java/org/apache/solr/search/facet/RelatednessAgg.java, solr/core/src/java/org/apache/solr/security/ConfigurableInternodeAuthHadoopPlugin.java, solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpClientBuilderFactory.java, solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpClientUtil.java, solr/solrj/src/java/org/apache/solr/client/solrj/impl/Krb5HttpClientBuilder.java, solr/solrj/src/java/org/apache/solr/client/solrj/impl/PreemptiveBasicAuthClientBuilderFactory.java, solr/solrj/src/java/org/apache/solr/client/solrj/routing/RequestReplicaListTransformerGenerator.java
https://issues.apache.org/jira/browse/SOLR-14846
=> SOLR-14846 Remove Optional.ofNullable.orElse pattern

dev-tools/scripts/buildAndPushRelease.py, dev-tools/scripts/releaseWizard.py, dev-tools/scripts/releaseWizard.yaml, dev-tools/scripts/scriptutil.py, lucene/version.properties
https://issues.apache.org/jira/browse/LUCENE-9488
=> LUCENE-9488 Update release process to work with gradle

.github/workflows/docker-test.yml
https://issues.apache.org/jira/browse/SOLR-14856
=> SOLR-14856: Adding docker test to github workflow.

dev-docs/working-between-major-versions.adoc
First attempt, very open to suggestions on making things more clear.
=> Adding dev-docs around the use of Git Worktree.

.github/workflows/docker-test.yml, .github/workflows/gradle-precommit.yml
Cache our gradle downloads when dependancies haven't changed
=> Use github actions cache

lucene/core/src/java/org/apache/lucene/search/Weight.java, lucene/core/src/java/org/apache/lucene/search/comparators/DocComparator.java, lucene/core/src/java/org/apache/lucene/search/comparators/NumericComparator.java, lucene/core/src/test/org/apache/lucene/search/TestFieldSortOptimizationSkipping.java
Fix bug how iterator with skipping functionality
advances and produces docs
Relates to #1725
Backport for #1903
=> Fix bug in sort optimization (#1903)

solr/solr-ref-guide/src/cluster-node-management.adoc
Ignoring the default issue template given that this PR is about a tiny fix for a typo. Right?
=> Fix minor typo

build.gradle, gradle/generation/nori.gradle, lucene/CHANGES.txt
It's almost the same as the #1924 (except CHANGES.txt).
=> LUCENE-9544: Port Nori dictionary compilation

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/admin/ConfigSetsHandler.java, solr/core/src/test/org/apache/solr/cloud/TestConfigSetsAPI.java, solr/solr-ref-guide/src/configsets-api.adoc, solr/solrj/src/java/org/apache/solr/common/params/ConfigSetParams.java
https://issues.apache.org/jira/browse/SOLR-14907
=> SOLR-14907: Support single file upload/overwrite in configSet API

solr/core/src/java/org/apache/solr/util/PackageTool.java, solr/core/src/java/org/apache/solr/util/SolrCLI.java
* Include add-key and uninstall commands
> As this is a minor change, I haven't created a JIRA, will create one if required
=> Include missing commands in package tool help section

solr/CHANGES.txt, solr/contrib/prometheus-exporter/conf/grafana-solr-dashboard.json
See https://issues.apache.org/jira/browse/SOLR-14936
=> SOLR-14936: Fixed Grafana dashboard filters

.github/workflows/solrj-test.yml
https://issues.apache.org/jira/browse/SOLR-14877
=> SOLR-14877: Add github action for running SolrJ tests.

solr/solr-ref-guide/src/uploading-structured-data-store-data-with-the-data-import-handler.adoc
PR against branch_8x. Superseeds #1466 which was for master.
@tkaessmann
=> SOLR-14445: Add Entity Caching documentation

solr/core/src/test/org/apache/solr/search/facet/TestJsonFacetRefinement.java, solr/core/src/test/org/apache/solr/search/facet/TestJsonFacets.java, solr/core/src/test/org/apache/solr/search/facet/TestJsonRangeFacets.java
https://issues.apache.org/jira/browse/SOLR-14937
=> SOLR-14937: Correct client.queryDefaults().set(...) calls in some JSON facet tests.

solr/core/src/java/org/apache/solr/cloud/api/collections/AddReplicaCmd.java, solr/core/src/java/org/apache/solr/cloud/api/collections/CreateCollectionCmd.java, solr/core/src/java/org/apache/solr/cloud/api/collections/DeleteCollectionCmd.java, solr/core/src/java/org/apache/solr/cloud/api/collections/MoveReplicaCmd.java, solr/core/src/java/org/apache/solr/cloud/api/collections/OverseerCollectionMessageHandler.java, solr/core/src/java/org/apache/solr/handler/admin/CollectionsHandler.java, solr/dev-docs/overseer/overseer.adoc, solr/solr-ref-guide/src/collection-management.adoc, solr/solr-ref-guide/src/major-changes-in-solr-9.adoc, solr/solrj/src/java/org/apache/solr/client/solrj/impl/SolrClientNodeStateProvider.java, solr/solrj/src/java/org/apache/solr/client/solrj/request/CollectionAdminRequest.java, solr/solrj/src/java/org/apache/solr/common/params/CollectionAdminParams.java
This cleanup is related to SOLR-14656 "Deprecate current autoscaling framework, remove from master" that didn't remove everything related to "withCollection".
=> SOLR-14964: remove Autoscaling related withCollection and COLOCATED_WITH

solr/CHANGES.txt
Remove the entries which are master(9x) only
=> Fix changes entry in 8x branch

solr/core/src/java/org/apache/solr/schema/ExternalFileField.java
=> SOLR-14968

solr/CHANGES.txt, solr/contrib/prometheus-exporter/bin/solr-exporter, solr/contrib/prometheus-exporter/bin/solr-exporter.cmd, solr/solr-ref-guide/src/monitoring-solr-with-prometheus-and-grafana.adoc
https://issues.apache.org/jira/browse/SOLR-14955
=> SOLR-14955: Add env var options to Prometheus Export scripts.

solr/solr-ref-guide/src/metrics-reporting.adoc
https://issues.apache.org/jira/browse/SOLR-14865
=> SOLR-14865: 'Index Merge Metrics' documentation correction

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/ClusterAPI.java, solr/core/src/java/org/apache/solr/handler/admin/ConfigSetsHandler.java, solr/core/src/test/org/apache/solr/cloud/TestConfigSetsAPI.java, solr/solr-ref-guide/src/configsets-api.adoc, solr/solrj/src/java/org/apache/solr/common/params/ConfigSetParams.java
https://issues.apache.org/jira/browse/SOLR-14907
Adding v2 APIs.
=> SOLR-14907: Adding V2 API for ConfigSet Upload.

help/docker.txt, solr/docker/build.gradle
https://issues.apache.org/jira/browse/SOLR-14949
Missed one option for customizing the building of docker images.
=> SOLR-14949: Adding githubUrl option for docker build.

lucene/core/src/java/org/apache/lucene/index/IndexingChain.java
This removes just a redundant check.
=> LUCENE-9603: Remove redundant fieldType.stored() check

solr/CHANGES.txt
=> SOLR-12182: Fix Changes.txt

solr/core/src/test/org/apache/solr/cloud/TestPullReplicaErrorHandling.java
https://issues.apache.org/jira/browse/SOLR-14992
=> SOLR-14992 Wait for node down before checking for node up

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/search/facet/FacetContext.java, solr/core/src/java/org/apache/solr/search/facet/SlotAcc.java, solr/core/src/test/org/apache/solr/search/function/AggValueSourceTest.java
Prior to this change, it was not feasible to write a custom aggregate function in plugin code
because the FacetContext class did not expose its fields for access outside its package. Also
some of the useful abstract classes for SlotAcc were package-private too
=> SOLR-8673: Enable custom aggregate functions by opening up FacetContext

lucene/CHANGES.txt, lucene/core/src/test/org/apache/lucene/document/BaseLatLonShapeTestCase.java, lucene/core/src/test/org/apache/lucene/document/BaseShapeTestCase.java, lucene/core/src/test/org/apache/lucene/document/BaseXYShapeTestCase.java, lucene/core/src/test/org/apache/lucene/document/TestLatLonLineShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestLatLonMultiLineShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestLatLonMultiPointShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestLatLonMultiPolygonShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestLatLonPointShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestLatLonPolygonShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestLatLonShape.java, lucene/core/src/test/org/apache/lucene/document/TestXYLineShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestXYMultiLineShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestXYMultiPointShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestXYMultiPolygonShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestXYPointShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestXYPolygonShapeQueries.java, lucene/core/src/test/org/apache/lucene/geo/TestLine2D.java, lucene/test-framework/src/java/org/apache/lucene/geo/GeoTestUtil.java, lucene/test-framework/src/java/org/apache/lucene/geo/ShapeTestUtil.java
Removes some unused code and replaces the Point implementation on the test with the Point implementation in the geo package.
cc: @nknize
=> LUCENE-9637: Clean up ShapeField/ShapeQuery random test

solr/core/src/test/org/apache/solr/core/ConfigureRecoveryStrategyTest.java
Test failure due to recent changes in https://github.com/apache/lucene-solr/pull/2120 
See: https://issues.apache.org/jira/browse/SOLR-15054
=> SOLR-15054: Test should not require private methods to be final

lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90VectorReader.java, lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90VectorWriter.java, lucene/core/src/java/org/apache/lucene/index/KnnGraphValues.java, lucene/core/src/java/org/apache/lucene/util/LongHeap.java, lucene/core/src/java/org/apache/lucene/util/hnsw/BoundsChecker.java, lucene/core/src/java/org/apache/lucene/util/hnsw/HnswGraph.java, lucene/core/src/java/org/apache/lucene/util/hnsw/HnswGraphBuilder.java, lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborArray.java, lucene/core/src/java/org/apache/lucene/util/hnsw/NeighborQueue.java, lucene/core/src/test/org/apache/lucene/index/TestKnnGraph.java, lucene/core/src/test/org/apache/lucene/util/TestLongHeap.java, lucene/core/src/test/org/apache/lucene/util/TestNumericUtils.java, lucene/core/src/test/org/apache/lucene/util/hnsw/KnnGraphTester.java, lucene/core/src/test/org/apache/lucene/util/hnsw/MockVectorValues.java, lucene/core/src/test/org/apache/lucene/util/hnsw/TestHnsw.java, lucene/core/src/test/org/apache/lucene/util/hnsw/TestNeighbors.java
This replaces the simple nearest neighbor selection with a criterion that takes into account the distance of the neighbors from each other. It is seen to provide dramatically improved recall on at least two datasets, and is what is being used by our reference implementation, hnswlib. Also:
* Split Neighbors into NeighborArray and NeighborQueue; use queue for gathering results; store graph arcs in arrays since diversity selection does not use a queue
* Add InfoStream progress messages to HnswGraphBuilder
* Add options to KnnGraphTester to support testing using ann-benchmarks (no warmup, write output to file)
* Improve memory usage; eliminate more object allocations; replaced iterator objects with single-use iterator "views"
=> LUCENE-9644: diversity heuristic for HNSW graph neighbor selection

.github/workflows/ant.yml
https://issues.apache.org/jira/browse/LUCENE-9647
Tagging @tflobbe for review because you removed the file in the first place. If there's a better place to put it, let me know.
=> LUCENE-9647 Add back github action for Ant

solr/solrj/src/test-files/solrj/solr/autoscaling/testEqualOnNonNode.json, solr/solrj/src/test-files/solrj/solr/autoscaling/testFreeDiskDeviation.json, solr/solrj/src/test-files/solrj/solr/autoscaling/testFreeDiskSuggestions.json, solr/solrj/src/test-files/solrj/solr/autoscaling/testMoveReplicasInMultipleCollections.json, solr/solrj/src/test-files/solrj/solr/autoscaling/testPolicy.json, solr/solrj/src/test-files/solrj/solr/autoscaling/testWithCollection.json, solr/solrj/src/test-files/solrj/solr/autoscaling/testWithCollectionMoveReplica.json, solr/solrj/src/test-files/solrj/solr/autoscaling/testWithCollectionMoveVsAddSuggestions.json, solr/solrj/src/test-files/solrj/solr/autoscaling/testWithCollectionSuggestions.json, solr/solrj/src/test/org/apache/solr/client/solrj/cloud/autoscaling/TestPolicy.java, solr/solrj/src/test/org/apache/solr/client/solrj/cloud/autoscaling/TestPolicy2.java
See: https://github.com/apache/lucene-solr/pull/2180 ... missed some test failures
=> SOLR-15058: Fix auto-scaling test fails missed in previous PR

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/update/processor/AtomicUpdateDocumentMerger.java, solr/core/src/test/org/apache/solr/update/TestInPlaceUpdatesDistrib.java, solr/core/src/test/org/apache/solr/update/TestInPlaceUpdatesStandalone.java, solr/core/src/test/org/apache/solr/update/processor/AtomicUpdatesTest.java
Additionally,
* Return proper error when inc operation is specified for non-numeric fields
=> SOLR-10860: Return proper error code for bad input incase of inplace updates

solr/CHANGES.txt, solr/contrib/prometheus-exporter/conf/grafana-solr-dashboard.json, solr/contrib/prometheus-exporter/conf/solr-exporter-config.xml, solr/contrib/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/MetricsConfiguration.java, solr/contrib/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/MetricsQuery.java, solr/contrib/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/MetricsQueryTemplate.java, solr/contrib/prometheus-exporter/src/test-files/conf/test-config-with-templates.xml, solr/contrib/prometheus-exporter/src/test-files/query-metrics.json, solr/contrib/prometheus-exporter/src/test/org/apache/solr/prometheus/exporter/MetricsQueryTemplateTest.java
Backport of https://github.com/apache/lucene-solr/pull/2165 to 8x
=> SOLR-15059: Improve query performance monitoring

.github/workflows/docker-test.yml, .github/workflows/gradle-precommit.yml, .github/workflows/solrj-test.yml
The github precommit action is failing because of OOMs. It should be fixed by setting local settings before running gradle commands.
=> Add gradle settings for github actions.

solr/contrib/ltr/src/test/org/apache/solr/ltr/feature/TestEdisMaxSolrFeature.java
Add test for reproducing the issue SOLR-15071
Add test for reproducing the issue SOLR-15071
=> SOLR-15071: add TestEdisMaxSolrFeature.testEdisMaxSolrFeatureCustomMM() test case

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestDictionary.java
The code produces too many warnings, so it's hard to notice newly introduced ones when developing new functionality.
Apply IDE quick fixes, sometimes cleanup manually.
No semantic changes, just cleanup.
=> LUCENE-9664: Hunspell support: fix most IntelliJ warnings, cleanup

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java
The code is too repetitive, hard to see the differences in similarly-looking branches.
call stem() recursively just once with different arguments depending on various conditions
Not applicable
=> LUCENE-9671: Hunspell: shorten Stemmer.applyAffix

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java
The code around `affixData` can be simplified, at the same time reducing thread-unsafe field count
use char[] instead of byte[], get rid of unnecessary byte array readers/writers
It's a refactoring; existing tests pass
=> LUCENE-9677: simplify Dictionary.affixData storage

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestDictionary.java
Too much repetitive code.
Introduce methods more suited for the frequent usage patterns
no new functionality, no tests
=> LUCENE-9681: deduplicate decodeFlags+hasFlag checks

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestDependencies.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/dependencies.aff, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/dependencies.dic
aff:
```
PFX h Y 1
PFX h 0 de .
SFX A Y 1
SFX A te tion/S .
```
dic:
```
hydrate/hA
```
should pass: `assertStemsTo("dehydration", "hydrate");`
After the prefix is stripped and there's a suffix to strip, its condition flag may be present not only on the suffix, but also on the stem.
A synthetic test based on Spanish `deshidratación`
=> LUCENE-9685: Hunspell: prefix condition is only checked on suffix, not stem

gradle/validation/forbidden-apis/commons-codec.commons-codec.all.txt, solr/CHANGES.txt, solr/core/src/java/org/apache/solr/security/BasicAuthPlugin.java, solr/core/src/java/org/apache/solr/security/Sha256AuthenticationProvider.java, solr/core/src/java/org/apache/solr/servlet/cache/HttpCacheHeaderUtil.java
Java8 has a builtin Base64 encoder and decoder, there is no need to use commons-codec for this purpose.
Eliminate commons-codec Base64 usage
Unit tests
=> SOLR-14297: replace commons-codec Base64 with JDK8 Base64

solr/core/src/java/org/apache/solr/handler/admin/ZookeeperInfoHandler.java
Backport of https://github.com/apache/lucene-solr/pull/2232 to branch for 8.8
=> SOLR-15097: Supply base_url in replica data returned to Admin UI

lucene/analysis/common/src/java/org/apache/lucene/analysis/pattern/PatternTypingFilter.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/pattern/PatternTypingFilterFactory.java, lucene/analysis/common/src/resources/META-INF/services/org.apache.lucene.analysis.TokenFilterFactory, lucene/analysis/common/src/test/org/apache/lucene/analysis/pattern/TestPatternTypingFilter.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/pattern/TestPatternTypingFilterFactory.java
=> LUCENE-9575 Add PatternTypingFilter to annotate tokens with flags and types

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/SpellChecker.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/SpellCheckerTest.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestAllCaps.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/allcaps.aff, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/allcaps.dic, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/allcaps.good, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/allcaps.wrong
When checking French L'AFRIQUE, consider not only L'afrique, but also L'Afrique
When there's an apostrophe, try a case variant with an uppercase after it, just like Hunspell does (https://github.com/hunspell/hunspell/blob/master/src/hunspell/hunspell.cxx#L547)
Enhanced `allcaps` test for both stemmer and spellchecker (as the case processing logic is duplicated there)
=> LUCENE-9690: Hunspell: support special title-case for words with apostrophe

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/conv.aff
plus cleanup & deduplicate parsing
e.g.
```
OCONV 2 # space, space
OCONV   a A # tab, space, space
OCONV   b   B # tab, tab, space
```
Deduplicate the code where an aff string is split into parts by whitespace, allow for # in the first unexpected part there
Expanded `conv` test
=> LUCENE-9691: Hunspell: support trailing comments on aff option lines

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java
The code is too similar, can be deduplicated
Extract a method, cleanup
Just a refactoring, no tests
=> LUCENE-9692: Hunspell: extract Stemmer.stripAffix from similar code in prefix/suffix processing

lucene/analysis/common/src/test/org/apache/lucene/analysis/core/TestRandomChains.java
fixes failure with seed 65EA739C95F40313
=> @gus-asf LUCENE-9575 Provide a producer for PatternTypingRule in TestRandomChains

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java
Hunspell: check that all flags are > 0 and fit char range, as Hunspell does
1. Add a corresponding assertion
2. Fix HIDDEN_FLAG serialization bug found by this assertion
3. Use char instead of int to store and pass flags around, because now we can use 0 for an unset flag instead of -1
No new tests, but some tests failed after implementing step 1 and were fixed in step 2
=> LUCENE-9693: Hunspell: check that all flags are > 0 and fit char range

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java
There's no need to allocate 3 `BytesReader`s when just one would be enough, as it's used as a scratch, without a need to preserve any state between uses.
Allocate just one `BytesReader` per affix type
No behavior change, no tests
=> LUCENE-9697: Hunspell Stemmer: use the same FST.BytesReader on all recursion levels

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/cloud/SolrZkServer.java, solr/solrj/src/java/org/apache/solr/common/cloud/ConnectionManager.java
https://issues.apache.org/jira/browse/SOLR-15113
=> SOLR-15113 Do not attempt to start Solr server when embedded ZK fails

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/SpellCheckerTest.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/dotless_i.aff, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/dotless_i.dic, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/dotless_i.good, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/dotless_i.wrong
Turkish `I`s don't work with `LANG tr`
Support `tr` as well as `tr_TR`
`dotless_i` from Hunspell/C++
=> LUCENE-9702: Hunspell: support alternate casing for short language codes

lucene/CHANGES.txt, lucene/misc/src/java/org/apache/lucene/misc/index/BinaryDocValueSelector.java, lucene/misc/src/java/org/apache/lucene/misc/index/IndexRearranger.java, lucene/misc/src/test/org/apache/lucene/misc/index/TestIndexRearranger.java
Create a new tool `IndexRearranger`, which could rearrange a built index concurrently to desired segment number and document distribution
Essentially combines `IndexWriter.addIndexes` and `FilterCodecReader` to select only certain documents into 1 segment
Added one unit test testing rearranger.
=> LUCENE-9694: New tool for creating a deterministic index

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestDictionary.java
This is a valid situation to be supported :(
Explititly encode/decode UTF-8 from default charset bytes
Extended `TestDictionary`
=> LUCENE-9708: Hunspell: support FLAG UTF-8 in absence of SET UTF-8

solr/contrib/ltr/src/test/org/apache/solr/ltr/TestRerankBase.java
There are two unused methods in TestRerankBase: buildIndexUsingAdoc, loadModelAndFeatures which can be removed.
Remove the methods.
Unit tests
=> SOLR-15115: Remove unused methods from TestRerankBase

solr/core/src/java/org/apache/solr/cloud/ZkController.java, solr/core/src/java/org/apache/solr/cloud/api/collections/AddReplicaCmd.java, solr/core/src/java/org/apache/solr/cloud/api/collections/OverseerCollectionMessageHandler.java, solr/core/src/test/org/apache/solr/cloud/LeaderElectionIntegrationTest.java, solr/core/src/test/org/apache/solr/cloud/OverseerCollectionConfigSetProcessorTest.java, solr/core/src/test/org/apache/solr/core/TestSolrConfigHandler.java, solr/test-framework/src/java/org/apache/solr/cloud/MiniSolrCloudCluster.java
There are lots of places in the code where we poll and sleep rather than using proper ZK callbacks.
Replace poll loops with waitForState
=> SOLR-14253 Replace various sleep calls with ZK waits

gradle/testing/randomization/policies/tests.policy, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/SpellCheckerTest.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestHunspellRepositoryTestCases.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestsFromOriginalHunspellRepository.java
and unify test naming in SpellCheckerTest
We want to have more or less parity in Java and C++ Hunspell implementations
See below
Added `TestsFromOriginalHunspellRepository` that runs spell checker on all flies from Hunspell repository which should be checked out somewhere. Some tests still fail there, but it won't fail on the CI now because it only runs when there's a special system property defined.
=> LUCENE-9707: Hunspell: check Lucene's implementation against Hunspel's test data

lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90VectorWriter.java, lucene/core/src/java/org/apache/lucene/document/VectorField.java, lucene/core/src/java/org/apache/lucene/util/hnsw/HnswGraphBuilder.java, lucene/core/src/test/org/apache/lucene/index/TestKnnGraph.java, lucene/core/src/test/org/apache/lucene/index/TestVectorValues.java, lucene/core/src/test/org/apache/lucene/util/hnsw/KnnGraphTester.java
Expose HnswGraphBuilder index-time hyperparameters as FieldType attributes
HnswGraphBuilder has a few tunables: maxConnections, beamWidth, and we may add a few more, such as whether to use a diversity heuristic when choosing neighbors to link in the graph. Currently these are locked to defaults set by global variables. Instead we should provide some interface for configuring them.
Here with this change we allow to pass down these parameters as FieldType attributes of VectorFields as well provide a convenience method in VectorFields.java to  add these parameters in FieldType attributes. The value passed in the attributes would be used in `Lucene90VectorWriter ` while creating a HNSW graph, in case no value is found we switch back to default parameter values present in `HnswGraphBuilder`. …
=> LUCENE-9615: Expose HnswGraphBuilder index-time hyperparameters as FieldType attributes

gradle/testing/randomization/policies/tests.policy, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestAllDictionaries.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestPerformance.java
We need some way check that changes don't regress performance, and preferably improve it
See below
Added a `TestPerformance` which prints some times that can be compared before and after risky changes. It's not run on CI yet and never fails.
=> LUCENE-9728: Hunspell: add a performance test

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/CheckCompoundPattern.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/CompoundRule.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/FlagEnumerator.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/SpellChecker.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestDictionary.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestPerformance.java
Each `Dictionary.decodeFlags` (and most `hasFlag`) checks allocated a `char[]`, in many cases only searched once
Check for flags for the given entry ID without allocations. Instead of `BytesRefHash`, store the sorted flags in a contiguous `char[]` built in a similar way (but without hashtable overhead after it's fully built), use offsets there as ids (like `BytesRefHash` does), store the length of the sub-array in the first char at the identifying offset. Search linearly instead of binary, as it results in a bit better performance.
I've got got 10-20% improvement on a manual check in `de` and `fr` in `TestPerformance`.
=> LUCENE-9735: Hunspell: speed up flag checks by avoiding allocations

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java
Flags in `FLAG num` mode were quite expensive to parse: strings were split by a regexp compiled every time.
I avoid regexps at all by hand-coding their quite simple "ignore non-digit characters" and "split by comma, ignoring empty parts" logic.
Manual. I've observed ~20% speedup on (non-parallelized) `TestAllDictionaries` (wooorm repo)
=> LUCENE-9739: Hunspell: speed up numeric flag parsing

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/SpellChecker.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java
There's duplication in this quite complicated logic
Introduce a lambda processor to pass around, and move the logic into one place
No new tests, no noticeable degradation in `TestPerformance`
=> LUCENE-9746: Hunspell: unify case variation logic in Stemmer and SpellChecker

lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestHunspellRepositoryTestCases.java
I've found more Hunspell repo tests either out of my immediate scope, or because they rely on dubious Hunspell's behavior
Mark them as failing
A test-only change :)
=> LUCENE-9759: Hunspell: add more to TestHunspellRepositoryTestCases.EXPECTED_FAILURES

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/GeneratingSuggester.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/SpellChecker.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/SpellCheckerTest.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/nosuggest.aff, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/nosuggest.dic, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/nosuggest.good, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/nosuggest.wrong
don't suggest NOSUGGEST and SUBSTANDARD dictionary entries and their derivations
Check for these flags when enumerating suggestions. To avoid passing `boolean forSuggestions` everywhere, subclass `SpellChecker` used for enumerating suggestions.
`nosuggest` from Hunspell repo
=> LUCENE-9758: Hunspell: support NOSUGGEST option

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/SpellChecker.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/forceucase.sug
Hunspell has a special branch in `suggest` for `FORCEUCASE` words
Replicate that logic
`forceucase.sug` from Hunspell repo
=> LUCENE-9764: Hunspell: try title case as FORCEUCASE misspelled word suggestions

solr/CHANGES.txt, solr/solr-ref-guide/src/solr-upgrade-notes.adoc
No code changes, just updating release note and changes.txt
=> SOLR-15145: Fix up changes.txt in branch_8x for 8.8.1 release

solr/CHANGES.txt, solr/contrib/ltr/src/java/org/apache/solr/ltr/model/LTRScoringModel.java, solr/contrib/ltr/src/java/org/apache/solr/ltr/model/LinearModel.java, solr/contrib/ltr/src/java/org/apache/solr/ltr/store/rest/ManagedModelStore.java, solr/contrib/ltr/src/test-files/modelExamples/linear-model_notExistentFeature.json, solr/contrib/ltr/src/test-files/modelExamples/linear-model_notExistentStore.json, solr/contrib/ltr/src/test-files/modelExamples/multipleadditivetreesmodel_notExistentStore.json, solr/contrib/ltr/src/test-files/modelExamples/multipleadditivetreesmodel_unknownFeature.json, solr/contrib/ltr/src/test/org/apache/solr/ltr/model/TestLinearModel.java, solr/contrib/ltr/src/test/org/apache/solr/ltr/model/TestMultipleAdditiveTreesModel.java
LTR integration gives obsvure and misleading error messages when creating models under certain circumstances
better exception handling
Tests to cover the exceptional use cases have been added
=> SOLR-15149: model creation errors fixes

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/admin/ZookeeperInfoHandler.java
see: https://github.com/apache/lucene-solr/pull/2383
=> SOLR-15135: Use DocCollection to generate state.json format expected by UI to work with perReplicaState collections (backport to 8x)

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/GeneratingSuggester.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Hunspell.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/HunspellTest.java
For example, to ensure responsiveness, IntelliJ-based IDEs periodically call a special method which can throw a dedicated exception. This allows the currently executed computation to be interrupted and release all the locks it holds, allowing the UI thread to grab them as quickly as possible.
Pass a `Runnable` to `Hunspell` constructor that may throw whatever exceptions the environment expects when needed
`HunspellTest.testCheckCanceled`
=> LUCENE-9779: Hunspell: add an API to interrupt long computations

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/ConvTable.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Hunspell.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestDictionary.java
Every input is converted to StringBuilder and then back, and an ICONV FST is (expensively) traversed for each char of the input. That takes some CPU time, up to 15% for English.
Extract ICONV/OCONV analysis into a new `ConvTable` class
Keep there hashes of first chars of all keys to quickly check if this table would do anything at all
Initialize FST stuff lazily on traversal
Add `Dictionary.needsInputCleaning(word)` to check if input conversion may do anything, and use it to avoid calling it where possible
No behavior change; `TestDictionary` adapted to the new architecture
=> LUCENE-9778: Hunspell: speed up input conversion

lucene/core/src/java/org/apache/lucene/util/fst/BytesStore.java
It's a hot spot, called a lot during FST arc reading
Go to ArrayList only when it's necessary. This speeds up org.apache.lucene.analysis.hunspell.TestPerformance#en by ~8%
No new tests
=> LUCENE-9781: Speed up BytesStore reader setPosition

gradle/validation/jar-checks.gradle
https://issues.apache.org/jira/browse/LUCENE-9780
=> LUCENE-9780: Only validate JARs for tasks that are enabled

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/GeneratingSuggester.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestSpellChecking.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/maxNGramSugsDefault.dic, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/maxNGramSugsDefault.sug, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/maxNGramSugsDefault.wrong
MAXNGRAMSUGS has a default value of 4 (undocumented and not easy to find in source)
Hardcode this 4
`maxNGramSugsDefault` added
=> LUCENE-9783: Hunspell: don't suggest more than 4 ngram corrections by default

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/ModifyingSuggester.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/sug.aff, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/sug.sug, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/sug.wrong
Suggest replacing English "ina" with "in a"
Fix off-by-one error
`sug` expanded
=> LUCENE-9782: Hunspell suggestions: split by space (but not dash) also before last char

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Hunspell.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestAllCaps.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestKeepCase.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/forbiddenword.dic, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/forbiddenword.good, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/forbiddenword.wrong, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/keepcase.dic, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/keepcase.good, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/keepcase.sug, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/keepcase.wrong
If an inflected form is listed in the dictionary like KEEPCASE, its other variations should be considered misspelled, even if affix removal would result in a non-KEEPCASE root
Move case check to the `RootProcessor` and make the spellchecking's one stop if it isn't satisfied. Disregard `KEEPCASE` in `Stemmer` to make it more consistent with "hunspell -s", move the code to `Hunspell`
`keepcase` appended with the scenario in question. `forbiddenword` appended as well, with a non-unit-tested case that started to fail on a real corpus after some intermediate version of the keepcase change.
=> LUCENE-9769: Hunspell: KEEPCASE should take precedence over affixed forms

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestAllDictionaries.java, lucene/core/src/java/org/apache/lucene/analysis/CharArrayMap.java, lucene/core/src/java/org/apache/lucene/util/CharsRef.java
FST traversal is the hottest spot in Hunspell, let's call it less frequently
Add a hash-based Bloom filter before FST traversal to avoid it.
None. `TestPerformance.de` became ~30% faster, `fr` and `en` — ~15% faster.
=> LUCENE-9790: Hunspell: avoid slow dictionary lookup if the word's hash isn't there

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/GeneratingSuggester.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestPerformance.java
We only need 100 first elements, not need to compare the thousands of other roots among themselves
Use a PriorityQueue, trim it once it becomes larger then the limit
Nothing failing, but added suggestion checks in `TestPerformance` to track progress. For now suggesting is horribly slow :(
=> LUCENE-9787: Hunspell: speed up suggesting a bit by not creating a huge TreeSet

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/ModifyingSuggester.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/sug.aff, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/sug.dic, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/sug.sug, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/sug.wrong
Suggest abcde for abecd
Adapt "long char move" loop to this case
`sug` expanded
=> LUCENE-9786: Hunspell suggestions: try moving the last character into the middle

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Hunspell.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/keepcase.aff, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/keepcase.dic, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/keepcase.good, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/keepcase.sug, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/keepcase.wrong
Like Hunspell does
Check for the context before checking the case
`keepcase` and `forbiddenword` expanded
=> LUCENE-9785: Hunspell: don't check case in compound middle and end

dev-docs/dev-utilities.adoc, solr/cloud-dev/cloud.sh
Make cloud.sh work with gradle on master
=> SOLR-15160 update cloud.sh

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestPerformance.java
Two-stage affix removal is quite expensive and can result on O(n^2) performance, especially with many zero affixes like in French
Don't go to the second stage if on the first one we've removed an affix which definitely isn't compatible with any other affix on the second stage; create a set of all continuation flags to check that quickly.
No new tests. `TestPerformance.de/fr` show about 2x speedups.
=> LUCENE-9799: Hunspell: don't check second-level affixes when the first level isn't a continuation

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Hunspell.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/ModifyingSuggester.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/SuggestionTimeoutException.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/TimeoutPolicy.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestHunspell.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestPerformance.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestSpellChecking.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestStemmer.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/timelimit.aff
Hunspell has a number of time limits to ensure it doesn't take forever applying potentially exponential rules
Add an equivalent of its `#define TIMELIMIT_GLOBAL (CLOCKS_PER_SEC / 4)` for suggestions. Later we'll see if we need other time limits.
`TestHunspell.testSuggestionTimeLimit`. It also became possible to raise the number of checked words in `TestPerformance.fr`: before even the second misspelled word took 15 seconds to `suggest`.
=> LUCENE-9800: Hunspell: put a time limit on suggestion calculation

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/ModifyingSuggester.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/sug.dic, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/sug.sug, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/sug.wrong
e.g. in English, for "ESPs" Hunspell suggests "ESP s" while Lucene suggests "ESP S". The former seems better.
Fix inaccuracies in reproducing Hunspell's logic
`sug` expanded
=> LUCENE-9805: Hunspell: fix space + mixed case heuristics on suggestions

solr/core/src/test-files/solr/collection1/conf/schema_codec.xml
=> SOLR-15181: update schema to not specify the docValuesFormat

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Hunspell.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/ModifyingSuggester.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/sug2.aff, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/sug2.dic, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/sug2.sug, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/sug2.wrong
Hunspell suggests space/dash-separated words if there's no "good" suggestions, where "good" is calculated separately for each case variation. We should do the same.
Make `hasGoodSuggestions` a local variable instead of a field.
Also fix suggestion order mismatch found by the test: Hunspell moves uppercase-after-space suggestions to the top.
`sug2` (being about space/dash separation) expanded
=> LUCENE-9808: Hunspell suggestions: consider space/dash-separated words for each case variation

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/GeneratingSuggester.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestPerformance.java
we skip roots longer than misspelled+4 anyway, so there's no need to read their arcs
When we visit a node longer than needed, use `IntsRefFSTEnum#seekCeil` to speed up rewinding to the next shorter node.
No new tests. `TestPerformance.de_suggest` has become ~40% faster
=> LUCENE-9810: Hunspell: when generating suggestions, skip too deep word FST subtrees

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/GeneratingSuggester.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/ngram.aff, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/ngram.dic, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/ngram.sug, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/ngram.wrong
e.g. inflect German "kennen" into "kenne"
Process empty affixes as well, remove strip before checking affix conditions
Enriched `ngram` test
=> LUCENE-9812: Hunspell: honor empty stripping affixes when generating suggestions

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/search/facet/FacetRangeProcessor.java, solr/core/src/test/org/apache/solr/schema/EnumFieldTest.java
=> SOLR-15191: Fix faceting on EnumFieldType

gradle/testing/slowest-tests-at-end.gradle
=> LUCENE-9818: print slowest suites, add an option to enable/ disable the function.

solr/core/src/java/org/apache/solr/core/CoreContainer.java
https://issues.apache.org/jira/browse/SOLR-15206
=> SOLR-15206: improve CoreContainer constructor javadocs

solr/solr-ref-guide/src/authentication-and-authorization-plugins.adoc, solr/solr-ref-guide/src/command-line-utilities.adoc, solr/solr-ref-guide/src/kerberos-authentication-plugin.adoc
Prefer the bin/solr zk command where possible over zkcli.sh.
Updating docs.  Maybe will also extend in seperate tickets adding more commands to bin/solr zk if needed???
doc change only, manual testing!
- [X ] I have developed this patch against the `master` branch.
- [ …
=> SOLR-15204: Document bin solr zk and zkcli

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/GeneratingSuggester.java
The loop is called a lot of times, and some allocations and method calls can be spared
Extract some code outside the loop
No new tests, ~5% speedup in `TestPerformance.en_suggest`
=> LUCENE-9687: Hunspell suggestions: reduce work in the findSimilarDictionaryEntries loop

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/GeneratingSuggester.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/TrigramAutomaton.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestTrigramAutomaton.java
`ngram` is expensive (O(`N*M*M`)) but we can make it O(N) by precompiling some automatons, specialized for the case `n=3` and `weighted=false`
Collect all substrings with length <= 3 of the misspelled word being checked against all dictionary entries, build an automaton matching them all, run it as we go along each dictionary entry, check which substrings match and add the score accordingly.
`TestTrigramAutomaton` checks the algorithm equivalence. `TestPerformance.en_suggest` becomes ~13% faster.
=> LUCENE-9824: Hunspell suggestions: speed up ngram score calculation for each dictionary entry

solr/contrib/analysis-extras/build.gradle, solr/contrib/analysis-extras/src/java/org/apache/solr/schema/ICUCollationField.java, solr/contrib/analysis-extras/src/test/org/apache/solr/schema/TestICUCollationField.java, solr/core/src/test/org/apache/solr/backcompat/TestLuceneIndexBackCompat.java, solr/core/src/test/org/apache/solr/search/TestXmlQParser.java
Rewrite one, ignore the other two.
=> SOLR-14759 fix tests that need on lucene test-src

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/IndexFetcher.java, solr/core/src/java/org/apache/solr/handler/component/HttpShardHandlerFactory.java, solr/core/src/test/org/apache/solr/handler/TestReplicationHandler.java, solr/core/src/test/org/apache/solr/handler/TestReplicationHandlerDiskOverFlow.java
I didn't update the doc as I'm not sure where/what to update. Should I?
=> SOLR-15217: Use shardsWhitelist in ReplicationHandler.

lucene/common-build.xml
See https://issues.apache.org/jira/browse/LUCENE-9912
=> LUCENE-9912 Disable HTML doclint in Lucene/Solr 8

solr/core/src/java/org/apache/solr/core/ConfigOverlay.java, solr/core/src/java/org/apache/solr/core/PluginInfo.java, solr/core/src/java/org/apache/solr/core/SolrConfig.java, solr/core/src/java/org/apache/solr/core/XmlConfigFile.java, solr/core/src/java/org/apache/solr/handler/DumpRequestHandler.java, solr/core/src/java/org/apache/solr/schema/FieldTypePluginLoader.java, solr/core/src/java/org/apache/solr/schema/IndexSchema.java, solr/core/src/java/org/apache/solr/schema/IndexSchemaFactory.java, solr/core/src/java/org/apache/solr/search/CacheConfig.java, solr/core/src/java/org/apache/solr/update/SolrIndexConfig.java, solr/core/src/java/org/apache/solr/update/VersionInfo.java, solr/core/src/java/org/apache/solr/util/DOMConfigNode.java, solr/core/src/java/org/apache/solr/util/DataConfigNode.java, solr/core/src/resources/EditableSolrConfigAttributes.json, solr/core/src/test/org/apache/solr/core/TestBadConfig.java, solr/core/src/test/org/apache/solr/core/TestCodecSupport.java, solr/core/src/test/org/apache/solr/core/TestConfLoadPerf.java, solr/core/src/test/org/apache/solr/core/TestConfig.java, solr/core/src/test/org/apache/solr/core/TestConfigOverlay.java, solr/core/src/test/org/apache/solr/core/TestSimpleTextCodec.java, solr/core/src/test/org/apache/solr/handler/component/SuggestComponentTest.java, solr/core/src/test/org/apache/solr/update/SolrIndexConfigTest.java, solr/solrj/src/java/org/apache/solr/cluster/api/SimpleMap.java, solr/solrj/src/java/org/apache/solr/common/ConfigNode.java, solr/solrj/src/java/org/apache/solr/common/util/DOMUtil.java, solr/solrj/src/java/org/apache/solr/common/util/LinkedSimpleHashMap.java, solr/solrj/src/java/org/apache/solr/common/util/WrappedSimpleMap.java
=> SOLR-15337 Avoid XPath in solrconfig.xml parsing

lucene/analysis/common/src/java/org/apache/lucene/analysis/miscellaneous/DropIfFlaggedFilter.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/miscellaneous/DropIfFlaggedFilterFactory.java, lucene/analysis/common/src/resources/META-INF/services/org.apache.lucene.analysis.util.TokenFilterFactory, lucene/analysis/common/src/test/org/apache/lucene/analysis/miscellaneous/TestDropIfFlaggedFilter.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/miscellaneous/TestDropIfFlaggedFilterFactory.java
=> LUCENE-9574 - Add a token filter to drop tokens based on flags.

solr/CHANGES.txt, solr/contrib/prometheus-exporter/conf/grafana-solr-dashboard.json, solr/contrib/prometheus-exporter/conf/solr-exporter-config.xml, solr/core/src/java/org/apache/solr/handler/admin/ZookeeperStatusHandler.java, solr/core/src/test/org/apache/solr/handler/admin/ZookeeperStatusHandlerFailureTest.java
Backport of https://issues.apache.org/jira/browse/SOLR-15397
=> SOLR-15397 Expose zookeeper status in the exporter

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/cloud/ReplicateFromLeader.java, solr/core/src/test/org/apache/solr/cloud/TestPullReplica.java, solr/core/src/test/org/apache/solr/cloud/TestPullReplicaWithAuth.java
Backport from main, see: https://github.com/apache/solr/commit/c731873aef43e81224caafdf02a1ba2f3b3a99e7
=> SOLR-15399: IndexFetcher should not issue a local commit for PULL replicas when leader's version is zero

lucene/CHANGES.txt, lucene/facet/src/test/org/apache/lucene/facet/TestStringValueFacetCounts.java
Backport a test case bug fix into branch_8x
=> LUCENE-9991: Address bug in TestStringValueFacetCounts

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/search/facet/FacetRangeProcessor.java, solr/core/src/test/org/apache/solr/schema/EnumFieldTest.java
Returning EnumFieldValue again instead of ordinal value of IntCalc.
Adding EnumCalc to return EnumFieldValue in faceting result.
Verify that the correct buckets are returned.
=> SOLR-15457: Returning EnumFieldValue in faceting buckets again.

solr/solrj/src/java/org/apache/solr/common/cloud/SolrZkClient.java
It's impossible for the "prettyPrint" code to be reached.  This has been so for 9 years.
=> SolrZkClient: remove dead code

lucene/CHANGES.txt, lucene/facet/src/java/org/apache/lucene/facet/taxonomy/IntTaxonomyFacets.java, lucene/facet/src/java/org/apache/lucene/facet/taxonomy/TaxonomyReader.java
Backported from the original [PR](https://github.com/apache/lucene/pull/62) in apache/lucene
=> Backport LUCENE-9902 Minor fixes to the faceting API (#62)

solr/CHANGES.txt, solr/solr-ref-guide/src/distributed-requests.adoc, solr/solrj/src/java/org/apache/solr/client/solrj/routing/NodePreferenceRulesComparator.java, solr/solrj/src/java/org/apache/solr/common/params/ShardParams.java, solr/solrj/src/test/org/apache/solr/client/solrj/routing/NodePreferenceRulesComparatorTest.java, solr/solrj/src/test/org/apache/solr/client/solrj/routing/RequestReplicaListTransformerGeneratorTest.java
Backport to 8x, see original PR: https://github.com/apache/solr/pull/188
=> SOLR-15472: New shards.preference option for preferring replicas based on their leader status

dev-tools/scripts/releaseWizard.yaml
- update Lucene wiki for release process
- add advice to look for PMC help for bulk update of JIRA issues
=> Small edits for release process

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/sql/SolrFilter.java, solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java, solr/solr-ref-guide/src/parallel-sql-interface.adoc
Backport of https://github.com/apache/solr/pull/173 to branch_8x
=> SOLR-15460: Implement LIKE, IS NOT NULL, IS NULL, and support wildcard * in equals string literal

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/sql/SolrSchema.java, solr/core/src/java/org/apache/solr/request/SolrRequestInfo.java, solr/core/src/java/org/apache/solr/security/PKIAuthenticationPlugin.java, solr/core/src/test/org/apache/solr/handler/sql/SQLWithAuthzEnabledTest.java, solr/solr-ref-guide/src/parallel-sql-interface.adoc, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/SolrStream.java
Backport of https://github.com/apache/solr/pull/168 to branch_8x
=> SOLR-15451: SolrSchema (for Parallel SQL) should use PKI principal for internal request to /admin/luke to get table metadata

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/sql/SolrEnumerator.java, solr/core/src/java/org/apache/solr/handler/sql/SolrFilter.java, solr/core/src/java/org/apache/solr/handler/sql/SolrSchema.java, solr/core/src/test-files/solr/configsets/sql/conf/schema.xml, solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java
Backport of https://github.com/apache/solr/pull/181
=> SOLR-15456: Get field type info from luke for custom fields instead of defaulting to String in Parallel SQL

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/sql/LimitStream.java, solr/core/src/java/org/apache/solr/handler/sql/SolrMethod.java, solr/core/src/java/org/apache/solr/handler/sql/SolrRel.java, solr/core/src/java/org/apache/solr/handler/sql/SolrSort.java, solr/core/src/java/org/apache/solr/handler/sql/SolrTable.java, solr/core/src/java/org/apache/solr/handler/sql/SolrToEnumerableConverter.java, solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java, solr/solr-ref-guide/src/parallel-sql-interface.adoc
Backport https://github.com/apache/solr/pull/191 to branch_8x
=> SOLR-15489: Implement OFFSET & FETCH for LIMIT SQL queries

solr/CHANGES.txt, solr/solrj/src/java/org/apache/solr/client/solrj/io/Lang.java, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/FacetStream.java, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/StatsStream.java, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/TimeSeriesStream.java, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/metrics/CountDistinctMetric.java, solr/solrj/src/test/org/apache/solr/client/solrj/io/TestLang.java, solr/solrj/src/test/org/apache/solr/client/solrj/io/stream/StreamExpressionTest.java
=> SOLR-15208: Add the countDist aggregation to the stats, facet and timeseries Streaming Expressions

solr/CHANGES.txt, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/FacetStream.java, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/ParallelMetricsRollup.java, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/StatsStream.java, solr/solrj/src/test/org/apache/solr/client/solrj/io/stream/ParallelFacetStreamOverAliasTest.java
Backport https://github.com/apache/solr/pull/197 to branch_8x
=> SOLR-15499: StatsStream implement ParallelMetricsRollup to allow for tiered computation of SQL metrics over collection aliases

solr/core/src/test/org/apache/solr/cloud/LeaderTragicEventTest.java
https://issues.apache.org/jira/projects/SOLR/issues/SOLR-15526
Not thrilled with this solution, but it seems to work for now.
=> SOLR-15526 Use new cluster for each LeaderTragicEvent test

solr/CHANGES.txt, solr/core/src/test/org/apache/solr/cloud/VMParamsZkACLAndCredentialsProvidersTest.java, solr/solr-ref-guide/src/zookeeper-access-control.adoc, solr/solrj/src/java/org/apache/solr/common/cloud/VMParamsAllAndReadonlyDigestZkACLProvider.java, solr/solrj/src/java/org/apache/solr/common/cloud/VMParamsSingleSetCredentialsDigestZkCredentialsProvider.java
=> SOLR-15525: Read ZK credentials from a file specified using a system property instead of exposing plain-text credentials

solr/CHANGES.txt, solr/solrj/src/java/org/apache/solr/common/cloud/ZkStateReader.java, solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudHttp2SolrClientTest.java, solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudSolrClientTest.java
https://issues.apache.org/jira/browse/SOLR-15549
=> SOLR-15549: Add support for Solr 9.0 clouds in ZkStateReader

lucene/CHANGES.txt, lucene/facet/src/java/org/apache/lucene/facet/DrillSidewaysScorer.java
=> LUCENE-10030: Lazily evaluate score in DrillSidewaysScorer.doQueryFirstScoring

solr/core/src/java/org/apache/solr/handler/sql/SolrSchema.java, solr/core/src/test-files/solr/configsets/sql/conf/schema.xml, solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java
This is an additional change needed for:
https://github.com/apache/lucene-solr/commit/1acb34753bcb771586b8b4010417e79f80952205
=> SOLR-15570: Check stored or docValues when merging fields from the Luke schema response

solr/CHANGES.txt, solr/bin/solr, solr/core/src/java/org/apache/solr/util/SolrCLI.java, solr/solr-ref-guide/src/basic-authentication-plugin.adoc, solr/solr-ref-guide/src/security-ui.adoc, solr/webapp/web/js/angular/app.js, solr/webapp/web/js/angular/controllers/schema-designer.js, solr/webapp/web/js/angular/controllers/security.js, solr/webapp/web/partials/security.html
backport of https://github.com/apache/solr/pull/245
=> SOLR-15573: bin/solr auth tool should provide role bindings for security-read and config-edit by default

lucene/CHANGES.txt, lucene/facet/src/java/org/apache/lucene/facet/StringValueFacetCounts.java, lucene/facet/src/test/org/apache/lucene/facet/TestStringValueFacetCounts.java
=> LUCENE-10046: Fix counting bug in StringValueFacetCounts

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/sql/SolrEnumerator.java, solr/core/src/java/org/apache/solr/handler/sql/SolrSchema.java, solr/core/src/test-files/solr/configsets/sql/conf/schema.xml, solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java, solr/solr-ref-guide/src/parallel-sql-interface.adoc, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/JDBCStream.java, solr/solrj/src/test/org/apache/solr/client/solrj/io/sql/JdbcTest.java
Backport of https://github.com/apache/solr/pull/252
=> SOLR-9853: Ability to project multi-valued fields in SQL query results

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/sql/CalciteSolrDriver.java, solr/core/src/java/org/apache/solr/handler/sql/SolrFilter.java, solr/core/src/java/org/apache/solr/handler/sql/SolrSchema.java, solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java, solr/solr-ref-guide/src/filter-descriptions.adoc, solr/solr-ref-guide/src/parallel-sql-interface.adoc
backport of https://github.com/apache/solr/pull/249
=> SOLR-15579: Re-configure calcite to allow more values in an IN clause

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/MultiDocValues.java, lucene/facet/src/java/org/apache/lucene/facet/StringValueFacetCounts.java, lucene/facet/src/java/org/apache/lucene/facet/sortedset/ConcurrentSortedSetDocValuesFacetCounts.java, lucene/facet/src/java/org/apache/lucene/facet/sortedset/SortedSetDocValuesFacetCounts.java, lucene/facet/src/test/org/apache/lucene/facet/TestStringValueFacetCounts.java, lucene/facet/src/test/org/apache/lucene/facet/sortedset/TestSortedSetDocValuesFacets.java
=> LUCENE-5309: Optimize facet counting for single-valued SSDV / StringValueFacetCounts

lucene/benchmark/src/java/org/apache/lucene/benchmark/byTask/feeds/ReutersContentSource.java
This bug is the same as LUCENE-10058, I filed a PR for each.
=> LUCENE-10051 Fix lucene branch_8x run ant run-task error

solr/CHANGES.txt, solr/webapp/web/js/angular/controllers/schema-designer.js
=> SOLR-15620: Download Config button in Schema Designer screen should not require user to re-login when already authenticated

solr/webapp/web/js/angular/controllers/security.js
backport of https://github.com/apache/solr/pull/299
=> SOLR-15637: Set scope.tls for security UI based on data.security.tls in response from server

solr/webapp/web/js/angular/controllers/security.js
=> SOLR-15637: Set .tls for security UI based on data.security.tls in response from server

dev-tools/scripts/poll-mirrors.py
Backport of https://github.com/apache/solr/pull/318 to 8x
=> SOLR-15665: Move polling logic under main

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/core/CoreContainer.java, solr/core/src/java/org/apache/solr/security/BasicAuthPlugin.java, solr/core/src/java/org/apache/solr/security/MultiAuthPlugin.java, solr/core/src/java/org/apache/solr/security/MultiAuthRuleBasedAuthorizationPlugin.java, solr/core/src/test-files/solr/security/multi_auth_plugin_security.json, solr/core/src/test/org/apache/solr/security/BasicAuthStandaloneTest.java, solr/core/src/test/org/apache/solr/security/MultiAuthPluginTest.java, solr/solr-ref-guide/src/basic-authentication-plugin.adoc, solr/solr-ref-guide/src/jwt-authentication-plugin.adoc, solr/solr-ref-guide/src/rule-based-authorization-plugin.adoc, solr/solrj/src/resources/apispec/cluster.security.MultiPluginAuth.Commands.json
backport of https://github.com/apache/solr/pull/355
=> SOLR-12666: Add authn & authz plugins that supports multiple authentication schemes, such as Bearer and Basic

solr/CHANGES.txt, solr/webapp/web/css/angular/security.css, solr/webapp/web/js/angular/controllers/security.js, solr/webapp/web/partials/security.html
backport of https://github.com/apache/solr/pull/393
=> SOLR-15721: Support editing Basic auth config when using the MultiAuthPlugin

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/security/MultiAuthPlugin.java, solr/core/src/test-files/solr/security/multi_auth_plugin_security.json, solr/core/src/test/org/apache/solr/security/MultiAuthPluginTest.java
backport of https://github.com/apache/solr/pull/394
=> SOLR-15766: MultiAuthPlugin should send non-AJAX anonymous requests to the plugin that allows anonymous requests

solr/CHANGES.txt, solr/webapp/web/js/angular/controllers/schema-designer.js, solr/webapp/web/js/angular/controllers/security.js, solr/webapp/web/partials/schema-designer.html, solr/webapp/web/partials/security.html
backport of https://github.com/apache/solr/pull/404
=> SOLR-15774: Avoid weird off-by-one errors with Angular's 'chosen' select box directive for the security and schema-designer screens in Admin UI
