apache/lucene-solr

solr/core/src/java/org/apache/solr/cloud/BackupCmd.java, solr/core/src/java/org/apache/solr/cloud/RestoreCmd.java, solr/core/src/java/org/apache/solr/core/backup/BackupManager.java, solr/core/src/java/org/apache/solr/core/backup/repository/BackupRepository.java, solr/core/src/java/org/apache/solr/core/backup/repository/HdfsBackupRepository.java, solr/core/src/java/org/apache/solr/core/backup/repository/LocalFileSystemRepository.java, solr/core/src/java/org/apache/solr/handler/ReplicationHandler.java, solr/core/src/java/org/apache/solr/handler/RestoreCore.java, solr/core/src/java/org/apache/solr/handler/SnapShooter.java, solr/core/src/java/org/apache/solr/handler/admin/CoreAdminOperation.java, solr/core/src/test/org/apache/solr/cloud/TestLocalFSCloudBackupRestore.java
- Refactored code using URI.getPath() API to use URI instance
uniformly.
- During serialization of URI instance, used toASCIIString() API
to generate the appropriate String representation.
=> [SOLR-9444] Fix path usage for cloud backup/restore

lucene/core/src/java/org/apache/lucene/search/GraphQuery.java, lucene/core/src/java/org/apache/lucene/util/QueryBuilder.java, lucene/core/src/java/org/apache/lucene/util/graph/GraphTokenStreamFiniteStrings.java, lucene/core/src/test/org/apache/lucene/search/TestGraphQuery.java, lucene/core/src/test/org/apache/lucene/util/TestQueryBuilder.java, lucene/core/src/test/org/apache/lucene/util/graph/TestGraphTokenStreamFiniteStrings.java, lucene/queryparser/src/java/org/apache/lucene/queryparser/classic/QueryParserBase.java, lucene/queryparser/src/test/org/apache/lucene/queryparser/classic/TestMultiFieldQueryParser.java, lucene/queryparser/src/test/org/apache/lucene/queryparser/classic/TestQueryParser.java
Adds support for handling graph token streams inside the
QueryBuilder util class used by query parsers.  This is a backport to `branch_6x`.
=> LUCENE-7603: branch_6x Support Graph Token Streams in QueryBuilder

lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/KoreanPartOfSpeechStopFilterFactory.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/KoreanReadingFormFilterFactory.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/KoreanTokenizerFactory.java
Example schema settings for `KoreanTokenizerFactory`, `KoreanPartOfSpeechStopFilterFactory`, `KoreanReadingFormFilterFactory`.
=> Add example schema settings for Korean analyzer.

lucene/core/src/java/org/apache/lucene/index/FilterDirectoryReader.java, lucene/core/src/test/org/apache/lucene/index/TestSoftDeletesDirectoryReaderWrapper.java
Today we can only wrap readers in SubReaderWrapper but never filter them out
entirely. This causes a invariant for soft-deletes that exposes fully deleted
segments with SoftDeletesDirectoryReaderWrapper. This change drops fully deleted readers after they are wrapped.
=> LUCENE-8484: Drop fully deleted reader in SubReaderWrapper

lucene/core/src/java/org/apache/lucene/index/FilterCodecReader.java, lucene/core/src/test/org/apache/lucene/index/TestFilterCodecReader.java
FilterCodecReader doesn't allow access to it's delegate like other
filter readers. This adds a new getDelegate method to access the
wrapped reader.
=> LUCENE-8502: Allow access to delegate in FilterCodecReader

lucene/core/src/java/org/apache/lucene/index/FilterCodecReader.java, lucene/core/src/java/org/apache/lucene/index/FilterDirectoryReader.java, lucene/core/src/java/org/apache/lucene/index/FilterLeafReader.java
Filter*Reader instances access the member or the delegate directly instead of
calling getDelegate(). In order to track access of the delegate these methods
should call #getDelegat()
=> LUCENE-8503: Call #getDelegate instead of direct member access during unwrap

lucene/CHANGES.txt, lucene/MIGRATE.txt, lucene/highlighter/build.xml, lucene/highlighter/src/java/org/apache/lucene/search/highlight/QueryScorer.java, lucene/highlighter/src/java/org/apache/lucene/search/highlight/WeightedSpanTermExtractor.java, lucene/highlighter/src/java/org/apache/lucene/search/vectorhighlight/FastVectorHighlighter.java, lucene/highlighter/src/java/org/apache/lucene/search/vectorhighlight/FieldQuery.java, lucene/highlighter/src/test/org/apache/lucene/search/highlight/HighlighterTest.java, lucene/highlighter/src/test/org/apache/lucene/search/vectorhighlight/FieldQueryTest.java, solr/core/src/java/org/apache/solr/highlight/DefaultSolrHighlighter.java
Highlighter doesn't support ToParent and ToChildBlockJoinQuery out of the
box anymore. In oder to highlight on Block-Join Queries a custom WeightedSpanTermExtractor
should be used.
=> LUCENE-8535: Drop out of the box Block-Join highlight support

lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
Today we count the actual soft-deletes during a merge which is
unnecessary if there are no hard-deletes present. In this case, which
is considered to be the common case we can get accurate counts by substracting
the number of deleted docs in the wrapped reader from the number of soft-deletes
in that reader.
=> LUCENE-8569: Never count soft-deletes if reader has no hard-deletes

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/BufferedUpdates.java, lucene/core/src/java/org/apache/lucene/index/BufferedUpdatesStream.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterDeleteQueue.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThread.java, lucene/core/src/java/org/apache/lucene/index/FieldUpdatesBuffer.java, lucene/core/src/java/org/apache/lucene/index/FrozenBufferedUpdates.java, lucene/core/src/test/org/apache/lucene/index/TestFieldUpdatesBuffer.java
Today we are using a LinkedHashMap to buffer doc-values updates in
BufferedUpdates. This on the one hand uses an Object based datastructure
and on the other requires re-encoding the data into a more compact representation
once the BufferedUpdates are frozen. This change uses a more compact represenation
for the updates already in the BufferedUpdates in a parallel-array like datastructure
that can be reused in FrozenBufferedDeletes. It also adds an much simpler to use
API to consume the updates and allows for internal memory optimization for common
case updates.
=> LUCENE-8590: Optimize DocValues update datastructures

lucene/core/src/java/org/apache/lucene/index/DocValuesFieldUpdates.java, lucene/core/src/java/org/apache/lucene/index/FieldUpdatesBuffer.java, lucene/core/src/java/org/apache/lucene/index/FrozenBufferedUpdates.java, lucene/core/src/java/org/apache/lucene/index/NumericDocValuesFieldUpdates.java, lucene/core/src/test/org/apache/lucene/index/TestFieldUpdatesBuffer.java
The case when all values are the the same on a numeric field update
is common for soft_deletes. With the new infrastucture for buffering
DV updates we can gain an easy win by specializing the applied updates
if all values are the same.
=> LUCENE-8593: Specialize single value numeric DV updates

lucene/backward-codecs/src/java/org/apache/lucene/codecs/lucene70/Lucene70Codec.java, lucene/backward-codecs/src/test/org/apache/lucene/index/TestBackwardsCompatibility.java
A segmemnt written with Lucene70Codec failes if it ties to update
a DV field that didn't exist in the index before it was upgraded to
Lucene80Codec. We bake the DV format into the FieldInfo when it's used
the first time and therefor never go to the codec if we need to update.
yet on a field that didn't exist before and was added during an indexing
operation we have to consult the coded and get an exception.
This change fixes this issue and adds the relevant bwc tests.
=> LUCENE-8594: DV update are broken for updates on new field

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/DocValuesFieldUpdates.java, lucene/core/src/java/org/apache/lucene/index/FieldUpdatesBuffer.java, lucene/core/src/java/org/apache/lucene/index/FrozenBufferedUpdates.java, lucene/core/src/java/org/apache/lucene/index/NumericDocValuesFieldUpdates.java, lucene/core/src/java/org/apache/lucene/util/packed/AbstractPagedMutable.java, lucene/core/src/test/org/apache/lucene/index/TestFieldUpdatesBuffer.java
DocValuesFieldUpdats are using compact settings for packet ints that causes
dramatic slowdowns when the updates are finished and sorted. Moving to the default
accepted overhead ratio yields up to 4x improvements in applying updates. This change
also improves the packing of numeric values since we know the value range in advance and
can choose a different packing scheme in such a case.
Overall this change yields a good performance improvement since 99% of the times of applying
DV field updates are spend in the sort method which essentially makes applying the updates
4x faster.
=> LUCENE-8598: Improve field updates packed values

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/DocValuesFieldUpdates.java, lucene/core/src/test/org/apache/lucene/index/TestDocValuesFieldUpdates.java
Using a sparse bitset in SingleValueDocValuesFieldUdpates allows storing
which documents have an update much more efficient and prevents the need
to sort the docs array altogether that showed to be a significant bottleneck
in LUCENE-8598. Using the spares bitset yields another 10x performance improvement
in applying updates versus the changes proposed in LUCENE-8598.
=> LUCENE-8599: Use sparse bitset to store docs in SingleValueDocValuesFieldUpdates

lucene/core/src/java/org/apache/lucene/index/BufferedUpdates.java, lucene/core/src/java/org/apache/lucene/index/FreqProxTermsWriter.java, lucene/core/src/java/org/apache/lucene/index/FrozenBufferedUpdates.java, lucene/core/src/java/org/apache/lucene/util/BytesRefArray.java, lucene/core/src/java/org/apache/lucene/util/BytesRefIterator.java, lucene/core/src/test/org/apache/lucene/index/TestFrozenBufferedUpdates.java
Today we re-implement the same algorithm in various places
when we want to consume all docs for a set/list of terms. This
caused serious slowdowns for instance in the case of applying
updates fixed in LUCENE-8602. This change extracts the common
usage and shares the interation code including logic to reuse
Terms and PostingsEnum instances as much as possble and adds
tests for it.
=> LUCENE-8608: Extract utility class to iterate over terms docs

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterFlushControl.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java, lucene/core/src/java/org/apache/lucene/index/FrozenBufferedUpdates.java, lucene/core/src/java/org/apache/lucene/index/NumericDocValuesFieldUpdates.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriter.java
This prevents an edge case where suddenly a lot of threads start indexing
while we carry over sequence ids from the previous to the new delete queue.
We now lock creation of new thread states for a very short time until we created and assigned
a new delete queue.
=> LUCENE-8639: Prevent new threadstates from being created while we cut over to a new delete queue

README.md
This PR is to show some solr-wiki-page-links on the README.md page.
The instructions mentioned on the README.md page is not enough to set up the project in the IDEs.  
The wiki pages are very helpful, but are not easily accessible.
Having their references on the `README.md` page will be quite helpful for beginners.
=> docs(intelliJSetup): Mention the link related to project-setup in IDE

lucene/core/src/java/org/apache/lucene/search/TotalHits.java, lucene/core/src/test/org/apache/lucene/search/TestSynonymQuery.java, lucene/core/src/test/org/apache/lucene/search/TestTopDocsCollector.java, lucene/core/src/test/org/apache/lucene/search/TestTopDocsMerge.java, lucene/core/src/test/org/apache/lucene/search/TestTopFieldCollector.java, lucene/core/src/test/org/apache/lucene/search/TestTotalHits.java, lucene/sandbox/src/test/org/apache/lucene/search/TestBM25FQuery.java
Adding equals/hashcode to TotalHits is convenient for quick comparisons, especially for users that may use it as part of bigger objects that have their own equals/hashcode. 
Fixes https://issues.apache.org/jira/browse/LUCENE-8664
=> LUCENE-8664: Add equals/hashcode methods to TotalHits class

solr/solr-ref-guide/src/collections-api.adoc, solr/solr-ref-guide/src/docvalues.adoc, solr/solr-ref-guide/src/indexing-and-basic-data-operations.adoc, solr/solr-ref-guide/src/major-changes-in-solr-7.adoc, solr/solr-ref-guide/src/managed-resources.adoc, solr/solr-ref-guide/src/reindexing.adoc, solr/solr-ref-guide/src/schema-api.adoc, solr/solr-ref-guide/src/shards-and-indexing-data-in-solrcloud.adoc, solr/solr-ref-guide/src/solr-tutorial.adoc, solr/solr-ref-guide/src/updating-parts-of-documents.adoc
While Solr frequently recommends to users that they reindex in various situations, we've had no central place in the Ref Guide that stated when they must or should do that, or how to do it.
This PR adds a new page `reindexing.adoc` under the section "Indexing and Basic Data Operations".
It also adds links to this new section in a few places (but probably not everywhere it could), and standardizes spelling on "reindex" instead of "re-index" throughout the guide.
=> SOLR-13259: Add new section on Reindexing in Solr

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/core/HdfsDirectoryFactory.java, solr/core/src/test-files/solr/collection1/conf/solrconfig-minhash.xml, solr/core/src/test-files/solr/collection1/conf/solrconfig.xml, solr/core/src/test/org/apache/solr/cloud/MoveReplicaHDFSFailoverTest.java, solr/core/src/test/org/apache/solr/cloud/MoveReplicaHDFSTest.java, solr/core/src/test/org/apache/solr/cloud/UnloadDistributedZkTest.java, solr/core/src/test/org/apache/solr/cloud/api/collections/HdfsCollectionsAPIDistributedZkTest.java, solr/core/src/test/org/apache/solr/cloud/api/collections/TestHdfsCloudBackupRestore.java, solr/core/src/test/org/apache/solr/cloud/autoscaling/HdfsAutoAddReplicasIntegrationTest.java, solr/core/src/test/org/apache/solr/cloud/hdfs/HDFSCollectionsAPITest.java, solr/core/src/test/org/apache/solr/cloud/hdfs/HdfsBasicDistributedZkTest.java, solr/core/src/test/org/apache/solr/cloud/hdfs/HdfsRecoverLeaseTest.java, solr/core/src/test/org/apache/solr/cloud/hdfs/HdfsRecoveryZkTest.java, solr/core/src/test/org/apache/solr/cloud/hdfs/HdfsRestartWhileUpdatingTest.java, solr/core/src/test/org/apache/solr/cloud/hdfs/HdfsTestUtil.java, solr/core/src/test/org/apache/solr/cloud/hdfs/HdfsThreadLeakTest.java, solr/core/src/test/org/apache/solr/cloud/hdfs/HdfsTlogReplayBufferedWhileIndexingTest.java, solr/core/src/test/org/apache/solr/cloud/hdfs/HdfsUnloadDistributedZkTest.java, solr/core/src/test/org/apache/solr/cloud/hdfs/HdfsWriteToMultipleCollectionsTest.java, solr/core/src/test/org/apache/solr/cloud/hdfs/StressHdfsTest.java, solr/core/src/test/org/apache/solr/core/HdfsDirectoryFactoryTest.java, solr/core/src/test/org/apache/solr/handler/TestHdfsBackupRestoreCore.java, solr/core/src/test/org/apache/solr/index/hdfs/CheckHdfsIndexTest.java, solr/core/src/test/org/apache/solr/search/TestRecoveryHdfs.java, solr/core/src/test/org/apache/solr/update/TestHdfsUpdateLog.java
Related JIRAs:
* SOLR-11010
* SOLR-11381
* SOLR-12040
* SOLR-13297
Changes:
* Consolidate hdfs configuration into HdfsTestUtil
* Ensure socketTimeout long enough for HDFS tests
* Ensure HdfsTestUtil.getClientConfiguration used in tests
* Replace deprecated HDFS calls
* Use try-with-resources to ensure closing of HDFS resources
=> SOLR-13330: Improve HDFS tests

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/codecs/blocktree/BlockTreeTermsReader.java, lucene/core/src/java/org/apache/lucene/codecs/blocktree/FieldReader.java, lucene/core/src/java/org/apache/lucene/index/CheckIndex.java, lucene/core/src/java/org/apache/lucene/index/DefaultIndexingChain.java, lucene/core/src/java/org/apache/lucene/index/ReadersAndUpdates.java, lucene/core/src/java/org/apache/lucene/index/SegmentCoreReaders.java, lucene/core/src/java/org/apache/lucene/index/SegmentDocValues.java, lucene/core/src/java/org/apache/lucene/index/SegmentMerger.java, lucene/core/src/java/org/apache/lucene/index/SegmentReadState.java, lucene/core/src/java/org/apache/lucene/index/SegmentReader.java, lucene/core/src/java/org/apache/lucene/index/StandardDirectoryReader.java, lucene/core/src/test/org/apache/lucene/codecs/lucene50/TestBlockPostingsFormat.java, lucene/core/src/test/org/apache/lucene/index/TestCodecs.java, lucene/core/src/test/org/apache/lucene/index/TestDemoParallelLeafReader.java, lucene/core/src/test/org/apache/lucene/index/TestDoc.java, lucene/core/src/test/org/apache/lucene/index/TestDocumentWriter.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterThreadsToSegments.java, lucene/core/src/test/org/apache/lucene/index/TestSegmentMerger.java, lucene/core/src/test/org/apache/lucene/index/TestSegmentReader.java, lucene/core/src/test/org/apache/lucene/index/TestSegmentTermDocs.java, lucene/test-framework/src/java/org/apache/lucene/index/BaseIndexFileFormatTestCase.java, lucene/test-framework/src/java/org/apache/lucene/index/RandomPostingsTester.java
Today we never load FSTs of ID-like fields off-heap since we need
very fast access for updates. Yet, a reader that is not loaded from
an index wirter can also leave the FST on disk. This change adds
this information to SegmentReadState to allow the postiings format
to make this decision without configuration.
=> LUCENE-8671: Load FST off-heap if reader is not opened from an index writer

lucene/CHANGES.txt, lucene/codecs/src/java/org/apache/lucene/codecs/simpletext/SimpleTextCompoundFormat.java, lucene/core/src/java/org/apache/lucene/codecs/lucene50/Lucene50CompoundReader.java, lucene/core/src/java/org/apache/lucene/store/ByteBuffersDirectory.java, lucene/core/src/java/org/apache/lucene/store/Directory.java, lucene/core/src/java/org/apache/lucene/store/FilterDirectory.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriter.java, lucene/test-framework/src/java/org/apache/lucene/index/BaseMergePolicyTestCase.java, solr/core/src/java/org/apache/solr/store/hdfs/HdfsDirectory.java
FilterDirectory.getPendingDeletions() did not delegate the call, which
resulted in a new IndexWriter on same directory not considering pending
delete files. This could in turn result in a FileAlreadyExistsException
when running windows.
=> LUCENE-8735: Avoid FileAlreadyExistsException on windows.

lucene/CHANGES.txt, lucene/codecs/src/java/org/apache/lucene/codecs/simpletext/SimpleTextSegmentInfoFormat.java, lucene/core/src/java/org/apache/lucene/codecs/lucene50/Lucene50PostingsFormat.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThread.java, lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/java/org/apache/lucene/index/SegmentInfo.java, lucene/core/src/test/org/apache/lucene/index/TestDemoParallelLeafReader.java, lucene/misc/src/java/org/apache/lucene/index/IndexSplitter.java, lucene/test-framework/src/java/org/apache/lucene/codecs/cheapbastard/CheapBastardCodec.java, lucene/test-framework/src/java/org/apache/lucene/index/BaseCompoundFormatTestCase.java, lucene/test-framework/src/java/org/apache/lucene/index/BaseFieldInfoFormatTestCase.java, lucene/test-framework/src/java/org/apache/lucene/index/BaseIndexFileFormatTestCase.java, lucene/test-framework/src/java/org/apache/lucene/index/BaseSegmentInfoFormatTestCase.java, lucene/test-framework/src/java/org/apache/lucene/index/RandomCodec.java, lucene/test-framework/src/java/org/apache/lucene/util/TestUtil.java
In order to prevent ConcurrentModificationException this change makes
an unmodifiable copy on write for all maps in SegmentInfo. MergePolicies
can access these maps without synchronization and cause exceptions if
it's modified in the merge thread.
=> LUCENE-8754: Prevent ConcurrentModificationException in SegmentInfo

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/admin/MetricsHistoryHandler.java, solr/core/src/test/org/apache/solr/cloud/MetricsHistoryWithAuthIntegrationTest.java
This gets rid of the 401 errors currently seen when using e.g. basic auth.
=> SOLR-12860: MetricsHistoryHandler now always uses PKI Auth

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/util/AbstractAnalysisFactory.java, lucene/core/src/java/org/apache/lucene/index/FrozenBufferedUpdates.java, lucene/core/src/java/org/apache/lucene/index/IndexWriterConfig.java, lucene/core/src/java/org/apache/lucene/index/SegmentInfo.java, lucene/core/src/java/org/apache/lucene/index/SegmentReadState.java, lucene/core/src/java/org/apache/lucene/index/StandardDirectoryReader.java, lucene/core/src/test/org/apache/lucene/index/TestSegmentInfos.java
This cuts over several places that use the pattern of creating a copy of
the supplied map with Map.copyOf.
=> Use Map.copyOf in lucene core

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java
Ensure new threadstates are locked before retrieving the
number of active threadstates. This causes assertion errors
and potentially broken field attributes in the IndexWriter when
IndexWriter#deleteAll is called while actively indexing.
=> LUCENE-8785: Ensure threadstates are locked before iterating

solr/solr-ref-guide/src/monitoring-solr-with-prometheus-and-grafana.adoc
Getting the Solr-Prometheus-Exporter to work with a secure Solr is possible, but not straight-forward.
This pull request extends the documentation to show how it can be done.
=> SOLR-12584: Describe getting Prometheus metrics from a secure Solr

lucene/CHANGES.txt, lucene/sandbox/src/java/org/apache/lucene/document/LatLonShapeBoundingBoxQuery.java, lucene/sandbox/src/java/org/apache/lucene/geo/Rectangle2D.java, lucene/sandbox/src/test/org/apache/lucene/document/BaseLatLonShapeTestCase.java
The current problem is the implementation in Rectangle2D but looking into other shape implementations like Line2D or Polygon2D, they do not implement has code, equals or toString methods. To keep symmetry on the implementations this PR removes those implementation in Rectangle2D and uses the provided Rectangle object in LatLonShapeBoundingBoxQuery to generate the hashCode.
=> LUCENE-8831: Fix bug on hashCode for LatLonShapeBoundingBoxQuery

dev-tools/scripts/poll-mirrors.py
Runs polling in 5 parallell processes
Adds -once option to exit after one poll
=> LUCENE-8827: Speed up poll-mirrors.py and add -once option

lucene/core/src/java/org/apache/lucene/util/IOUtils.java, lucene/core/src/test/org/apache/lucene/util/TestIOUtils.java
Today in the method IOUtils#fsync we ignore IOExceptions when fsyncing a directory. However, the catch block here is too broad, for example it would be ignoring IOExceptions when we try to open a non-existent file. This commit addresses that by scoping the ignored exceptions only to the invocation of FileChannel#force. This prevents us from suppressing an exception in case we run into an unexpected issue when opening the file.
However, fsyncing directories on Windows is not possible. We always suppressed this by allowing that an AccessDeniedException is thrown when attemping to open the directory for reading. Yet, per the above, this suppression also allowed other IOExceptions to be suppressed, and that should be considered a bug (e.g., not only the directory not existing, but any …
=> LUCENE-8843: Only ignore IOException on dirs when invoking force

solr/webapp/web/partials/query.html
Due to a typo in the webapp query interface, the used query string is incorrect.
=> SOLR-13546: Fix typo 'hightlight' in webapp query interface

solr/core/ivy.xml
Adds a dependency on opentracing-mock for the Solr core tests
This is just a build fix.
Solr builds using maven now.
- [n/a] I have added tests for my changes.
- [n/a] I have added documentation for the Ref Guide (for Solr changes only).
=> SOLR-13549: Fix opentracing mock dependency for Solr core tests

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java
Today we don't utilize the incoming thread for a search when IndexSearcher
has an executor. This thread is only idling but can be used to execute a search
once all other collectors are dispatched.
=> LUCENE-8865: Use incoming thread for execution if IndexSearcher has an executor

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java, lucene/core/src/java/org/apache/lucene/search/SearcherFactory.java, lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java, lucene/test-framework/src/java/org/apache/lucene/search/ScorerIndexSearcher.java
In order to simplify testing this change moves to use the Executor
interface instead of ExecutorService. This change also simplifies
customizing execute methods for use-cases that need to add additional
logic for forking to new threads. This change also adds a test for
the optimization added in LUCENE-8865.
This change is fully backwards compatible since ExecutorService implements
Executor.
=> LUCENE-8865: Move to executor in IndexSearcher

lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java
Today if an executor was added to the IndexSearcher it's impossible to
clone the searcher with it's cache, similarity and caching policy since
the executor is not exposed. This adds a simple getter to make cloning
easier.
=> Expose IndexSearchers executor in order to enable searcher cloning

lucene/core/src/test/org/apache/lucene/search/TestPointQueries.java
This commit beefs up equality tests for PointRangeQuery by deep checking range points as well. This also serves to have an internal usage of the API so it does not seem orphaned within the code base.
=> LUCENE-8889: Add Tests For Accessors Of Ranges in PointRangeQuery

lucene/CHANGES.txt, lucene/MIGRATE.txt, lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java, lucene/core/src/java/org/apache/lucene/search/TopDocs.java, lucene/core/src/test/org/apache/lucene/search/TestMultiSliceMerge.java, lucene/core/src/test/org/apache/lucene/search/TestTopDocsMerge.java, lucene/test-framework/src/java/org/apache/lucene/search/ShardSearchingTestBase.java
This commit introduces custom tiebreakers which allows users to
specify custom tiebreakers when ordering hits to return. A
default tiebreaker is introduced for tie breaking on shard index
first and then docID.
=> LUCENE-8857: Introduce Custom Tiebreakers in TopDocs#merge

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/document/LatLonPointDistanceQuery.java, lucene/core/src/java/org/apache/lucene/document/LatLonPointInPolygonQuery.java, lucene/core/src/java/org/apache/lucene/document/RangeFieldQuery.java, lucene/core/src/java/org/apache/lucene/search/PointInSetQuery.java, lucene/core/src/java/org/apache/lucene/search/PointRangeQuery.java, lucene/core/src/test/org/apache/lucene/search/TestPointQueries.java, lucene/sandbox/src/java/org/apache/lucene/document/LatLonShapeQuery.java, lucene/sandbox/src/test/org/apache/lucene/document/BaseLatLonShapeTestCase.java, lucene/test-framework/src/java/org/apache/lucene/geo/BaseGeoPointTestCase.java, lucene/test-framework/src/java/org/apache/lucene/search/BaseRangeFieldQueryTestCase.java
The following queries have been implemented:
- LatLonShapeQuery
- RangeFieldQuery
- LatLonPointInPolygonQuery
- LatLonPointDistanceQuery
- PointRangeQuery
- PointInSetQuery
=> LUCENE-8896: Override default implementation of IntersectVisitor#visit(DocIDSetBuilder, byte[]) for several queries

solr/core/src/java/org/apache/solr/schema/AbstractEnumField.java, solr/core/src/java/org/apache/solr/schema/TrieDateField.java, solr/core/src/test/org/apache/solr/schema/DateFieldTest.java
* get the string from charsequence and avoid casting
=> SOLR-13538: Fix classcastEx in TrieDateField for atomic updates

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/admin/ZookeeperInfoHandler.java
SOLR-13507: Remove support for addr parameter from the /solr/admin/zookeeper endpoint. (#759)
back-port from master https://github.com/anshumg/lucene-solr/commit/b7090d9c25ba430442628b0dc77c7c700cb35b33
=> SOLR-13507: Remove support for addr parameter from the /solr/admin/zookeeper endpoint. (#759)

lucene/core/src/java/org/apache/lucene/codecs/lucene50/Lucene50PostingsReader.java, lucene/core/src/java/org/apache/lucene/search/ExactPhraseMatcher.java, lucene/core/src/java/org/apache/lucene/search/MultiPhraseQuery.java, lucene/core/src/java/org/apache/lucene/search/PhraseMatcher.java, lucene/core/src/java/org/apache/lucene/search/PhraseQuery.java, lucene/core/src/java/org/apache/lucene/search/PhraseScorer.java, lucene/core/src/java/org/apache/lucene/search/PhraseWeight.java, lucene/core/src/java/org/apache/lucene/search/SloppyPhraseMatcher.java, lucene/core/src/test/org/apache/lucene/search/TestPhraseQuery.java, lucene/queries/src/java/org/apache/lucene/queries/intervals/TermIntervalsSource.java
This PR adds and leverages impacts for phrase queries. It contains two commits that are unrelated but getting them at the same time helps preserve performance: currently impacts don't specialize at all. After doing some digging, I noticed that one reason why the change made things slower is that postings specialize both the docs(+freqs) and docs+freqs+positions cases, while impacts don't specialize anything at all. So I removed the specialization for docs+freqs+positions with postings and added specialization for docs+freqs+positions with impacts instead. The assumption is that phrases are more often used for ranking than for filtering.
=> LUCENE-8311: Phrase impacts

lucene/analysis/nori/build.xml, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/BinaryDictionary.java, lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/TokenInfoDictionary.java, lucene/analysis/nori/src/tools/java/org/apache/lucene/analysis/ko/util/BinaryDictionaryWriter.java, lucene/analysis/nori/src/tools/java/org/apache/lucene/analysis/ko/util/TokenInfoDictionaryBuilder.java, lucene/analysis/nori/src/tools/test/org/apache/lucene/analysis/ko/dict/TokenInfoDictionaryTest.java, lucene/analysis/nori/src/tools/test/org/apache/lucene/analysis/ko/dict/UnknownDictionaryTest.java
It is the Nori version of LUCENE-8863.
This patch has two changes.
1) Improve exception handling
2) Enable external dictionary for testing
Please check the following link:
https://issues.apache.org/jira/browse/LUCENE-8904
=> LUCENE-8904: enhance Nori DictionaryBuilder tool

lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java, lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java
During Flattening, BooleanQuery will always try to flatten
nested clauses during rewrite. However, this can cause the
maximum number of clauses to be violated by the new query.
This commit disables flattening in the specific case.
Supersedes #784
=> LUCENE-8810: Honor MaxClausesCount in BooleanQuery

lucene/analysis/nori/build.xml, lucene/analysis/nori/src/tools/java/org/apache/lucene/analysis/ko/util/TokenInfoDictionaryBuilder.java
It is the Nori version of LUCENE-8866.
Nori doesn't need the ICU library because it uses Normalizer2 only for NFKC normalization like Kuromoji.
Please check the following link:
https://issues.apache.org/jira/browse/LUCENE-8912
=> LUCENE-8912: remove nori/tools dependency on ICU

solr/core/src/test/org/apache/solr/TestDistributedGrouping.java
using ignoreException
SOLR-13404 added a test that expects Solr to fail if grouping is called with group.offset < 0. When the test runs it succeeds but the whole stack trace is printed out in the logs. 
This small patch avoid the stack trace by using ignoreException. I also replaced an `assertTrue` with a more specific check. 
This patch is improving a test.
- [...] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).
=> SOLR-13676: Reduce log verbosity in TestDistributedGrouping 

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/admin/ZookeeperStatusHandler.java, solr/core/src/test/org/apache/solr/handler/admin/ZookeeperStatusHandlerTest.java, solr/webapp/web/js/angular/controllers/cloud.js, solr/webapp/web/partials/cloud.html
Admin UI/ZK Status page: Zookeeper 3.5 : 4lw.commands.whitellist error
Turned out that there is a new line `membership:` in `conf` 4lw response for a quorum that does not follow the `key=value` format, so our parsing crashed.
* Be more lenient when parsing zk response and disregard the known `membership:` line
* Do not stop parsing when one error occurs, but continue reading response from other ZK hosts, gathering up errors in the errors array to display on top
Added a new test that mocks the raw response for `ruok`, `mntr` and `conf` from zk, so we can test how the handler parses the response and maps them to error messages etc.
=> SOLR-13672: Zk Status page now parses response from Zookeeper 3.5.5 correctly

lucene/analysis/kuromoji/src/test/org/apache/lucene/analysis/ja/dict/UserDictionaryTest.java
Use `LuceneTestCase#expectThrows()` instead of `expected`.
=> LUCENE-8933: Use expectThrows instead of expected.

solr/core/src/java/org/apache/solr/core/PackageManager.java, solr/core/src/java/org/apache/solr/core/PluginBag.java, solr/core/src/java/org/apache/solr/core/PluginInfo.java, solr/core/src/java/org/apache/solr/core/SolrConfig.java, solr/core/src/java/org/apache/solr/core/SolrCore.java, solr/core/src/java/org/apache/solr/handler/SolrConfigHandler.java, solr/core/src/java/org/apache/solr/metrics/SolrMetrics.java, solr/core/src/java/org/apache/solr/search/CacheConfig.java, solr/core/src/java/org/apache/solr/search/FastLRUCache.java, solr/core/src/java/org/apache/solr/search/LFUCache.java, solr/core/src/java/org/apache/solr/search/LRUCache.java, solr/core/src/java/org/apache/solr/search/SolrCache.java, solr/core/src/java/org/apache/solr/search/SolrCacheHolder.java, solr/core/src/test/org/apache/solr/handler/TestContainerReqHandler.java, solr/solrj/src/java/org/apache/solr/common/util/StrUtils.java, solr/solrj/src/resources/apispec/core.config.json
API to expose the currently used package name, details for each plugin
=> SOLR-13707: API to expose the currently used package name, details for each plugin

lucene/CHANGES.txt, lucene/sandbox/src/java/org/apache/lucene/search/LatLonPointPrototypeQueries.java, lucene/sandbox/src/java/org/apache/lucene/search/NearestNeighbor.java, lucene/sandbox/src/test/org/apache/lucene/search/TestNearest.java
This commit addresses a TODO in `NearestNeighbors` around switching to
`SloppyMath.haversinSortKey`. When comparing candidate hits, we now only compute
a distance sort key. The sort key is converted to a true distance only when returning
the final set of `FieldDocs` and when calculating the bbox for the current search area.
=> LUCENE-8952: Use a sort key instead of true distance in NearestNeighbor.

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/document/LatLonDocValuesField.java, lucene/core/src/java/org/apache/lucene/document/LatLonDocValuesPointInPolygonQuery.java, lucene/core/src/java/org/apache/lucene/document/LatLonPointInPolygonQuery.java, lucene/core/src/test/org/apache/lucene/search/TestLatLonDocValuesQueries.java
Adds a new query that iterates over LatLonPoint docValues and test if the point is within a provided polygon. In addition, `LatLonPointInPolygonQuery` is rewritten so it can be used efficiently with the new added query using `IndexOrDocValuesQuery`.
=> LUCENE-8960: Add LatLonDocValuesPointInPolygonQuery

lucene/core/src/java/org/apache/lucene/index/DirectoryReader.java, lucene/core/src/java/org/apache/lucene/index/IndexFileDeleter.java, lucene/core/src/java/org/apache/lucene/index/IndexFileNames.java, lucene/core/src/java/org/apache/lucene/index/SegmentInfos.java, lucene/replicator/src/java/org/apache/lucene/replicator/IndexReplicationHandler.java
This file isn't used anymore since 4.0, so I tried to contain references to
`segments.gen` to the minimum that is required to get the right exception when
opening a too old index.
=> LUCENE-8150: Remove references to `segments.gen`.

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/geo/SimpleGeoJSONPolygonParser.java, lucene/core/src/test/org/apache/lucene/geo/TestPolygon.java
The builtin geo shape parser throws an exception when the properties contains an array of strings.
Allow parsing of such arrays by reading strings.
Add unit test has been added for this case.
=> LUCENE-8964: Fix geojson shape parsing on string arrays in properties

lucene/CHANGES.txt, lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/dict/UserDictionary.java, lucene/core/src/java/org/apache/lucene/search/spans/SpanWeight.java, solr/contrib/analytics/src/java/org/apache/solr/analytics/facet/PivotNode.java, solr/core/src/java/org/apache/solr/cloud/api/collections/CreateCollectionCmd.java, solr/core/src/java/org/apache/solr/core/CoreDescriptor.java, solr/core/src/java/org/apache/solr/handler/admin/CollectionsHandler.java, solr/core/src/java/org/apache/solr/handler/admin/ZookeeperInfoHandler.java, solr/core/src/java/org/apache/solr/logging/log4j2/Log4j2Watcher.java, solr/core/src/java/org/apache/solr/request/json/RequestUtil.java, solr/core/src/java/org/apache/solr/rest/schema/analysis/ManagedSynonymGraphFilterFactory.java, solr/core/src/java/org/apache/solr/schema/FieldType.java, solr/core/src/java/org/apache/solr/search/DisMaxQParser.java, solr/core/src/java/org/apache/solr/search/ExtendedDismaxQParser.java, solr/core/src/java/org/apache/solr/search/facet/FacetRequest.java, solr/core/src/java/org/apache/solr/search/mlt/SimpleMLTQParser.java, solr/core/src/java/org/apache/solr/update/processor/AtomicUpdateDocumentMerger.java, solr/core/src/java/org/apache/solr/util/SolrCLI.java, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/KnnStream.java, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/RandomFacadeStream.java, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/RandomStream.java, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/SearchStream.java
https://issues.apache.org/jira/browse/LUCENE-8975
Some simple cleanup. No need to spend company/personal time reviewing this, would be good if someone had some spare time. If you don't, feel free to close this tab.
It's a very simple PR: just changing `keySet()` to `entrySet()` **when possible**. In general just the better choice. Only really a performance gain when going over a TreeMap(as I recall at least), but in general a good idea to consistent with it.
2 exceptions where it gets changed to `values()`.
All changes done automatically by Intellij.
And 1 String construction in a loop that got turned into a Stringbuilder because that's just wasteful.
That's over in solr/core/src/java/org/apache/solr/search/facet/FacetRequest.java
All tests have run locally and succeeded.
=> LUCENE-8975: Code Cleanup: Use entryset for map iteration wherever possible.

solr/CHANGES.txt, solr/contrib/prometheus-exporter/bin/solr-exporter, solr/contrib/prometheus-exporter/bin/solr-exporter.cmd, solr/solr-ref-guide/src/monitoring-solr-with-prometheus-and-grafana.adoc
The startup options for the Prometheus Exporter are pretty sparse compared to what the Solr start script offers.
I've added some options that mirror what Solr offers, such as:
- SOLR_HEAP
- SOLR_JAVA_MEM
- GC_TUNE
Having just the memory settings available would let us start the prometheus exporter with more than 500 Mb of heap, which right now isn't possible as the max heap is hard coded here.
I have started the metrics-exporter locally with this script, although I do not have access to a windows host to test the `solr-exporter.cmd` script. That code came from `solr.cmd` so I would imagine that it works, however I would appreciate if someone on windows could make sure that it works as expected.
=> SOLR-13773: Prometheus Exporter GC and Heap options

.github/PULL_REQUEST_TEMPLATE.md
By default, when a Solr contributor creates their own fork, only they
have access to that fork.  This creates a bit of a roadblock when users
contribute PRs from these forks - others can't build off of their work -
something that is done often with patches.  An initial user might
contribute a feature, a committer might add tests or change formatting,
etc.
This change introduces a bullet point to our PR checklist to nudge users
towards making their PR branches more open.
N/A
=> SOLR-13775: Add note about permissions to "PR Template"

lucene/core/src/java/org/apache/lucene/search/BottomValueChecker.java, lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java, lucene/core/src/java/org/apache/lucene/search/TopScoreDocCollector.java, lucene/core/src/test/org/apache/lucene/search/TestTopDocsCollector.java
This commit introduces a mechanism for early termination where,
for indices sorted by relevance, hits are collected in per thread
queue. Full PQs publish their bottom values and the maximum of
them is then used by the corresponding collectors to filter further
hits
=> LUCENE-8978: Maximal Of Minimum Scores Based Concurrent Early Termination

lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java, lucene/core/src/test/org/apache/lucene/search/TestIndexSearcher.java
When executing queries using Executors, we should gracefully handle the case when Executor rejects a task and run the task on the caller thread.
=> LUCENE-8989: Allow IndexSearcher To Handle Rejected Execution

lucene/analysis/common/src/java/org/apache/lucene/analysis/synonym/WordnetSynonymParser.java
The link to the description of the Wordnet prolog database files seems outdated.
This change replaces it with a working link.
=> Update Wordnet file format description link

solr/core/src/java/org/apache/solr/cloud/api/collections/TimeRoutedAlias.java, solr/core/src/test/org/apache/solr/update/processor/DimensionalRoutedAliasUpdateProcessorTest.java, solr/core/src/test/org/apache/solr/update/processor/TimeRoutedAliasUpdateProcessorTest.java
Fix Date math parsing for TRA start
Invoke the DateMathParser.parseMath method rather than using the parseRouteKey method.
Added a test that fails without the fix to ensure support for date math is not lost again.
=> SOLR-13760 - restore viability of date math in TRA start property

dev-tools/maven/pom.xml.template, lucene/CHANGES.txt, lucene/common-build.xml
This PR is just for maintenance:
- Update forbiddenapis to v2.7 (support for Java 12 and Java 13; allows to use `FileWriter` and `FileReader` since Java 11)
- Update Groovy to 2.4.17
=> Update forbiddenapis to v2.7 and Groovy to v2.4.17

lucene/core/src/java/org/apache/lucene/util/SetOnce.java, lucene/core/src/test/org/apache/lucene/util/TestSetOnce.java
This change fixes race condition in SetOnce class that can cause code like below throw `NullPointerException`
```java
SetOnce<String> setOnce = new SetOnce<>();
new Thread(() -> setOnce.set("thread")).start();
try{
setOnce.set("main");
} catch (SetOnce.AlreadySetException e){
setOnce.get().hashCode(); //possible NPE!
}
```
It also adds `boolean trySet(T obj)` method that doesn't throw exception when something was set before, it returns false in that case.
`AtomicBoolean` and `volatile T obj` was replaced with single `AtomicReference` that serves both purposes: checking if something was set and actually storing object. That way update is atomic - no race condition can occur.
`Wrapper` is used to allow null object to be stored, the same way it was possible before.
All tests from …
=> LUCENE-9001: Fix race condition in SetOnce

lucene/CHANGES.txt, lucene/join/src/java/org/apache/lucene/search/join/GlobalOrdinalsWithScoreQuery.java
Today we disable caching for GlobalOrdinalsQuery (https://issues.apache.org/jira/browse/LUCENE-8062) but not GlobalOrdinalsWithScoreQuery. However the GlobalOrdinalsWithScoreQuery is sometimes executed in a filter context (despite the name, e.g. when min/max are provided) so we should protect this query for the same reasons invoked in LUCENE-8062.
=> LUCENE-9022: Never cache GlobalOrdinalsWithScoreQuery

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/update/DirectUpdateHandler2.java
From the Jira description:
> DUH2 stats not populated in PluginInfoHandler: I believe this is related to the changes in SOLR-13677. DirectUpdateHandler2 seems to be missing to implement SolrMetricsContext getSolrMetricsContext(), which causes SolrInfoBean.getMetricsSnapshot() to be null
=> SOLR-13866: Override getSolrMetricsContext in DirectUpdateHandler2

solr/solr-ref-guide/src/performance-statistics-reference.adoc
I haven't created a Solr Ticket for this minor change, if really necessary, I can and would update PR and commit message.
Wanted to know the unit of warmUpTime, but it was not included.
Added it, so other people don't have to dig.
None, but you can quickly verify by checking source.
https://github.com/apache/lucene-solr/search?l=Java&q=warmupTime
=> Add temporal unit to warmupTime in ref guide

lucene/core/src/java/org/apache/lucene/util/IntroSelector.java, lucene/core/src/test/org/apache/lucene/util/TestIntroSelector.java
Today, `IntroSelector.slowSelect` falls back to a heap sort; This PR moves that implementation to use a median of medians approach, suggested by a TODO in the code.
Implemented a median of medians algorithm.
I didn't add any new tests for this as I believe the current test cases, `TestIntroSelector`, should cover the basic functionality. However, one thing I'd like input on: Today, `select(int from, int to, int k)`, the `to` parameter is _exclusive_. Since it's also a specified parameter in the test, the test never checks the case where the full array should be used. `doTestSelect` has a call to `Arrays.sort(expected, from, to);`, but `to` will never be the last index in the array because the size of the array is allocated to `from + to + random().nextInt(5)`, so the actual size of the …
=> LUCENE-9024 Optimize IntroSelector to use median of medians

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/cloud/ZkShardTerms.java, solr/core/src/test/org/apache/solr/cloud/ZkShardTermsTest.java
Currently if a recovering replica is deleted, the term for that core in the shard's terms in ZK is removed. However the `<core>_recovering` term is not removed as well. This can create clutter and confusion in the shard terms ZK node.
When a core is removed from the shardTerms, the corresponding recovering term is removed if it exists.
Added a test to make sure that corresponding terms are removed.
=> SOLR-13844: Remove replica recovery terms with the replica term

lucene/tools/src/groovy/install-markdown-filter.groovy, solr/CHANGES.txt, solr/core/src/java/org/apache/solr/util/SolrPluginUtils.java, solr/core/src/test/org/apache/solr/util/SolrPluginUtilsTest.java
Traps error that arises when the < operator is used at the end of a query field.
Also handles NumberFormatException when the operand isn't a number.
When < operator is used with no operand after it (i.e. at the end of the query field) or with a non-numeric operand, an HTTP 500 error arises caused by an ArrayIndexOutOfBoundsException or NumberFormatException respectively.
Throws a SolrException with BAD_REQUEST as the error code when either situation arises, since the query is malformed.
Added 2 cases in SolrPluginUtilsTest.testMinShouldMatchCalculator, for queries "1<" and "1<x". Both use the try-fail-catch pattern.
Manually tested the example from the bug description; the error is now a 400 error.
=> SOLR-13207: Handle query errors in calculateMinShouldMatch

solr/core/src/test/org/apache/solr/cloud/ZkShardTermsTest.java
Fixes `ZkShardTermsTest.testCoreRemovalWhileRecovering()` test.
Collection nam was shared with another test case in the class. Changed the test to use a unique collection name.
=> SOLR-13844: Fixing tests related to ShardTerms recovery removal

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/LRUQueryCache.java, lucene/core/src/test/org/apache/lucene/search/TestLRUQueryCache.java, lucene/core/src/test/org/apache/lucene/search/TestUsageTrackingFilterCachingPolicy.java, lucene/test-framework/src/java/org/apache/lucene/util/LuceneTestCase.java
We have dozens of ES clusters(based on Lucene) for metric scenarios. Most of the queries are like this: host_ip:10.10.10.10 AND timestamp:[2019-10-01 00:00:00 TO 2019-10-05 23:59:59]. And we frequently encounter some absurdly slow queries.
For a long time range query(e.g. 5 days), each range query will consume tens of megabytes of memory and spend hundreds of milliseconds to cache, but the benefits are not obvious. And those large cache entries will cause frequent cache eviction. So it's better to skip the caching action directly when large range query appears with a selective lead iterator.
Related to [LUCENE-9002](https://issues.apache.org/jira/projects/LUCENE/issues/LUCENE-9002)
=> LUCENE-9002: Query caching leads to absurdly slow queries

lucene/CHANGES.txt, lucene/analysis/common/src/java/org/apache/lucene/analysis/synonym/WordnetSynonymParser.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/synonym/TestSolrSynonymParser.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/synonym/TestWordnetSynonymParser.java
This fixes an issue where sets of equivalent synonyms in the Wordnet format are
parsed and added to the SynonymMap in a way that leads to the original input
token not being typed as "word" but as SYNONYM instead. Also the original token
doesn't appear first in the token stream output, which is the case for
equivalent solr formatted synonym files.
Currently the WordnetSynonymParser adds all combinations of input/output pairs
of a synset entry into the synonym map, while the SolrSynonymParser excludes
those where input and output term are the same. This change adds the same
behaviour to WordnetSynonymParser and adds tests that show the two formats are
outputting the same token order and types now.
=> LUCENE-9030: Fix different Solr- and WordnetSynonymParser behaviour

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/TermInSetQuery.java
This PR is about the javadoc of TermInSetQuery.
There is a wrong example.
It is minor but should be fixed.
Please refer to the following JIRA link:
[LUCENE-9046](https://issues.apache.org/jira/browse/LUCENE-9046)
=> LUCENE-9046: Fix wrong example in Javadoc of TermInSetQuery

solr/CHANGES.txt, solr/solrj/src/java/org/apache/solr/common/cloud/ZkStateReader.java
InterruptedException is being swallowed in ZkStateReader’s getLeaderRetry method
Catch InterruptedException separately, interrupt current thread, and throw
No tests added but ran and got a passing test suite locally
=> SOLR-13950: Fix getLeaderRetry swallowing interrupt in ZkStateReader

solr/core/src/java/org/apache/solr/handler/StreamHandler.java, solr/solr-ref-guide/src/streaming-expressions.adoc
Fix incorrect JavaDocs on `StreamHandler` on how to add your own expressions
JavaDoc fixes and Ref Guide section.
n/a
- [ X] I am authorized to contribute this code to the ASF and have removed any code I do not have a license to distribute.
- [ X] I have developed this …
=> SOLR-13947 document how to load your own streaming plugins

lucene/backward-codecs/src/test/org/apache/lucene/codecs/lucene50/Lucene50SkipWriter.java, lucene/core/src/java/org/apache/lucene/codecs/CompetitiveImpactAccumulator.java, lucene/core/src/java/org/apache/lucene/codecs/lucene84/Lucene84SkipWriter.java, lucene/core/src/test/org/apache/lucene/codecs/TestCompetitiveFreqNormAccumulator.java
The current design of CompetitiveImpactAccumulator treats norms in -128..127
as a special case that should be optimized. This commit goes a bit further by
treating it as the normal case, and only ever adding impacts to the TreeSet if
the norm is outside of the byte range. It avoids a number of operations on
TreeSets like adding impacts or removing redundant impacts.
=> LUCENE-9063: Speed up computation of impacts.

solr/solr-ref-guide/src/authentication-and-authorization-plugins.adoc
The deleted sentence contradicts the sentence near the top of this document that says “All authentication and authorization plugins can work with Solr whether they are running in SolrCloud mode or standalone mode.”
=> Correct inconsistency on plugin support

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/geo/EdgeTree.java, lucene/core/src/java/org/apache/lucene/geo/Polygon2D.java
This PR adds an early termination exception for the case a point lies on the boundary of an edge tree.
=> LUCENE-9067: Polygon2D#contains is now thread safe

solr/CHANGES.txt, solr/solrj/src/java/org/apache/solr/common/annotation/SolrSingleThreaded.java, solr/solrj/src/java/org/apache/solr/common/annotation/SolrThreadSafe.java
Add thread safety annotations to classes. 
The current commit only introduces the annotations, but the actual annotations will take some time but are wip. We can then use these to add information to existing classes, as well as new classes.
=> SOLR-13998: Add thread safety annotations to classes

solr/CHANGES.txt, solr/server/solr/zoo.cfg, solr/solrj/src/test-files/solrj/solr/multicore/zoo.cfg
See https://issues.apache.org/jira/browse/SOLR-13954
Fix is to disable zk adminserver, we don't use it yet.
Once we start using it (to replace 4LW) we can add needed jars.
=> SOLR-13954: Embedded ZK in Solr now does not try to load JettyAdminServer

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/component/ExpandComponent.java, solr/core/src/test/org/apache/solr/handler/component/TestExpandComponent.java
Applications of ExpandComponent that do not involve prior collapsing of results on the expand field had been throwing NPE in `getGroupQuery` due to different count/size tracking.
=> SOLR-7798 ExpandComponent support for non-collapsed results

solr/core/src/java/org/apache/solr/store/blob/process/CorePullerThread.java, solr/core/src/java/org/apache/solr/update/processor/DistributedZkUpdateProcessor.java, solr/core/src/test/org/apache/solr/store/shared/SimpleSharedStoreEndToEndPushTest.java, solr/core/src/test/org/apache/solr/update/processor/DistributedZkUpdateProcessorTest.java
-Don't invoke push to shared store for isolated commits.
-Disable the noisy "going back to task queue" log line.
=> SOLR-13101: Don't invoke push to shared store for isolated commits.

solr/bin/solr, solr/core/src/java/org/apache/solr/core/CoreContainer.java
Solr should warn users on startup if insecure settings are being used.
Currently I've added the detection and message for this in bin/solr.  I'm not sure this is the best place for this logic - I'd like to keep logic out of bash/powershell where possible, and a smarter check would look at security.json in ZooKeeper, which is easier to do within the JVM.
But this PR is still worth reviewing if anyone has feedback on the language or appearance of the warning.
I've done manual testing, but that's it.  If we had a `bin/solr` test framework as SOLR-11749 proposes, we could conceivably write tests for this, but that's a major task and isn't going to happen anytime soon.
=> SOLR-13972: Warn about insecure settings on startup

solr/CHANGES.txt, solr/solr-ref-guide/src/adding-custom-plugins-in-solrcloud-mode.adoc
=> SOLR-14072: Deprecate Blob API and runtimeLib

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/cloud/OverseerConfigSetMessageHandler.java, solr/core/src/java/org/apache/solr/cloud/OverseerMessageHandler.java, solr/core/src/java/org/apache/solr/cloud/OverseerSolrResponse.java, solr/core/src/java/org/apache/solr/cloud/OverseerTaskProcessor.java, solr/core/src/java/org/apache/solr/cloud/api/collections/OverseerCollectionMessageHandler.java, solr/core/src/java/org/apache/solr/handler/admin/CollectionsHandler.java, solr/core/src/java/org/apache/solr/handler/admin/ConfigSetsHandler.java, solr/core/src/test/org/apache/solr/cloud/OverseerCollectionConfigSetProcessorTest.java, solr/core/src/test/org/apache/solr/cloud/OverseerSolrResponseTest.java, solr/core/src/test/org/apache/solr/cloud/OverseerSolrResponseUnsafeSerializationTest.java, solr/core/src/test/org/apache/solr/cloud/OverseerTaskQueueTest.java, solr/solrj/src/java/org/apache/solr/client/solrj/SolrResponse.java, solr/solrj/src/java/org/apache/solr/common/util/Utils.java
The Overseer currently uses java serialization to store command responses in ZooKeeper. This commit changes the code to use Javabin instead, while allowing Java serialization with a System property in case it's needed for compatibility.
This PR is for merge into master and branch_8. I'll have a new PR after this is merged to remove the back compat code from master.
=> SOLR-14095: Let the overseer use javabin to store responses in ZooKeeper

solr/core/src/java/org/apache/solr/core/CoreContainer.java, solr/core/src/java/org/apache/solr/store/blob/process/CorePullTask.java, solr/core/src/java/org/apache/solr/store/blob/process/CorePusher.java, solr/core/src/java/org/apache/solr/store/blob/util/BlobStoreUtils.java, solr/core/src/java/org/apache/solr/store/shared/SharedCoreConcurrencyController.java, solr/core/src/java/org/apache/solr/update/processor/DistributedZkUpdateProcessor.java, solr/core/src/test/org/apache/solr/store/shared/SharedCoreConcurrencyTest.java
-Concurrency tests for SHARED collection.
-On core container shutdown, shutdown the background blob delete manager too.
-Use correct casing for SharedCoreStage enum.
-Added INDEXING_BATCH_FINISHED to indicate the end of a batch (BLOB_PUSH_FINISHED does not help if push itself runs into error)
=> SOLR-13101: Concurrency tests for SHARED collection.

solr/bin/solr, solr/bin/solr.cmd, solr/bin/solr.in.cmd, solr/bin/solr.in.sh, solr/server/etc/jetty-requestlog.xml, solr/server/etc/jetty.xml, solr/server/modules/requestlog.mod
Today you have to edit XML to enable the jetty request log. This makes it work via environment variable.
It also gets this thing off the currently deprecated RequestLog class.
SOLR_LOGS_DIR is now respected by default (today it uses hardcoded `logs/`)
=> SOLR-14138: enable request log via environ var

dev-tools/scripts/releaseWizard.py, dev-tools/scripts/releaseWizard.yaml
Instead of a hard 3 working day requiremet, we use the ASF standard of 72 clock hours.
But use the holiday logic to warn the RM about upcoming holidays and that she may want to extend the deadline.
=> Change 72h voting rules for release wizard

lucene/CHANGES.txt, lucene/test-framework/src/java/org/apache/lucene/util/TestSecurityManager.java
This is just a small improvement in Lucene/Solr master (Java 11) to detect exit of JVM in our test framework. There are other places in Lucene that use ineffective ways to inspect the stack trace.
This one optimizes the implementation of TestSecurityManager#checkExit(status) to disallow all JVM exits outside of the official test runner by using StackWalker. In addition this needs no additional permissions, because we do not instruct StackWalker to fetch all crazy stuff like Class instances of stack elements.
The way how this works is: Walk through stack trace:
- skip all internal frames (those which come before the actual exit call)
- skip all frmes with the actual exit call
- limit to one more frame (the method calling System.exit())
- check if that remaining frame is on our whitelist …
=> LUCENE-9109: Use stack walker to implement TestSecurityManager's detection of test JVM exit

lucene/CHANGES.txt, lucene/core/src/test/org/apache/lucene/TestMergeSchedulerExternal.java, lucene/core/src/test/org/apache/lucene/index/TestConcurrentMergeScheduler.java, lucene/core/src/test/org/apache/lucene/index/TestDirectoryReaderReopen.java, lucene/core/src/test/org/apache/lucene/index/TestIndexFileDeleter.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriter.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterDelete.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterExceptions.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterOnDiskFull.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterOnVMError.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterReader.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterWithThreads.java, lucene/core/src/test/org/apache/lucene/index/TestPersistentSnapshotDeletionPolicy.java, lucene/highlighter/src/test/org/apache/lucene/search/uhighlight/TestUnifiedHighlighterTermVec.java, lucene/test-framework/src/java/org/apache/lucene/index/BaseFieldInfoFormatTestCase.java, lucene/test-framework/src/java/org/apache/lucene/index/BaseSegmentInfoFormatTestCase.java, lucene/test-framework/src/java/org/apache/lucene/util/LuceneTestCase.java
There are a lot of tests (especially around IndexWriter) that look into stack traces to inject failures or check that some methods were called in their call stack.
This issue will refactor all those tests by adding a few methods to LuceneTestCase that make it easy to verify if some method call/class is in stack trace. On master (Java 11) we can use StackWalker to do this checks, which has a speedup of sometimes >>2 times (depending on how deep you dive into call stack).
There are a few tests (only 3) that do more complex stack trace analysis. Those should be refactored at some point. For now I added a deprecated method to get the whole StackTrace in Java 11, which is still 2 times faster than using an Exception.
For branch 8.x i will apply the same patch, just the LuceneTestCase methods …
=> LUCENE-9110: Switch tests to use StackWalker

solr/solr-ref-guide/src/collection-management.adoc
The `name` parameter is madatory on BACKUP and RESTORE commands, but isn't listed, though it is in the example URLs...
Added the parameter.
n/a, though manually tested the commands to confirm needed, and reviewed the Java code.
- [ X] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ X] I have developed this patch …
=> SOLR-14157-backup-restore-docs-missing-parameter

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/codecs/DocValuesConsumer.java
This makes the merged view call `TermsEnum#next` on its subs rather than `#lookupOrd`.
=> LUCENE-9113: Speed up merging doc values' terms dictionaries.

lucene/core/src/java/org/apache/lucene/codecs/lucene84/package-info.java
The name was wrong here. Also, added a link to make this doc more
fun to navigate in HTML form and make sure it doesn't go bad again.
=> MINOR: Fix Incorrect Constant Name in Codec Docs

lucene/core/src/java/org/apache/lucene/codecs/compressing/CompressingTermVectorsWriter.java
**Description**
In CompressingTermVectorsWriter.flushOffsets, the calculation of sumPos and sumOffsets is a little redundant
**Solution**
Simplify the process.
**Tests**
I have no idea how to test it, I‘m really appreciate anyone giving me ideas. I have compared before&after, the result is same.
**Checklist**
=> LUCENE-9096: Implementation of CompressingTermVectorsWriter.flushOffsets can be simpler

solr/solrj/src/java/org/apache/solr/client/solrj/SolrResponse.java
The serialVersionUID of SolrResponse changed in https://github.com/apache/lucene-solr/pull/929 making Solr nodes before/after that change mutually incompatible for some operations.
This sets the serialVersionUID of SolrResponse explicitly to its previous value.
I've run manual builds with/without this patch and seen that /solr/admin/collections?action=overseerstatus against stops giving the exception `java.io.InvalidClassException: org.apache.solr.client.solrj.SolrResponse; local class incompatible: stream classdesc serialVersionUID = -7931100103360242645, local class serialVersionUID = 2239939671435624715` for hybrid clusters when the patch is in place.
- (n/a) I have added tests for my changes.
- (n/a) I have added documentation for …
=> SOLR-14165 set SolrResponse's serialVersionUID explicitly

lucene/core/src/java/org/apache/lucene/codecs/blocktree/SegmentTermsEnumFrame.java
See https://issues.apache.org/jira/browse/LUCENE-9118.
The diff is easier to read when ignoring whitespaces: https://github.com/apache/lucene-solr/pull/1150/files?w=1.
=> LUCENE-9118: BlockTreeTermsReader uses `Arrays#compareUnsigned` to compare suffixes.

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/store/NRTCachingDirectory.java, lucene/core/src/test/org/apache/lucene/store/TestNRTCachingDirectory.java
See https://issues.apache.org/jira/browse/LUCENE-9115.
=> LUCENE-9115: NRTCachingDirectory shouldn't cache files of unknown size.

lucene/core/src/java/org/apache/lucene/search/DisjunctionMaxQuery.java, solr/core/src/java/org/apache/solr/search/facet/FacetRange.java
I only fixed two small typo errors in the JavaDocs
=> [docs]: fixed two small errors in JavaDoc

build.gradle, gradle/validation/precommit.gradle, gradle/validation/rat-sources.gradle, gradle/validation/validate-source-patterns.gradle, versions.props
Still a WIP, but most of the way there.
Need to move the task invocation out to the modules where it belongs. I didn't completely understand the logic for what was included and excluded and how we made those decisions initially.
Am not sure if we should be printing all the violations by default or hiding that behind a `--info` or `--verbose` flag.
=> Add RAT check using Gradle

lucene/benchmark/src/java/org/apache/lucene/benchmark/byTask/feeds/TrecDocParser.java, lucene/classification/src/test/org/apache/lucene/classification/Test20NewsgroupsClassification.java, lucene/core/src/java/org/apache/lucene/search/MaxScoreAccumulator.java, lucene/core/src/java/org/apache/lucene/util/StringHelper.java, lucene/core/src/test/org/apache/lucene/analysis/TestCharArraySet.java, lucene/core/src/test/org/apache/lucene/index/Test2BPoints.java, lucene/core/src/test/org/apache/lucene/index/TestFieldReuse.java, lucene/core/src/test/org/apache/lucene/index/TestTransactions.java, lucene/core/src/test/org/apache/lucene/store/TestBufferedIndexInput.java, lucene/core/src/test/org/apache/lucene/util/bkd/Test2BBKDPoints.java, lucene/monitor/src/java/org/apache/lucene/monitor/ConcurrentQueryLoader.java, lucene/sandbox/src/test/org/apache/lucene/document/TestLatLonShape.java, lucene/test-framework/src/java/org/apache/lucene/mockfile/MockFileSystemTestCase.java, solr/core/src/java/org/apache/solr/core/ZkContainer.java, solr/core/src/java/org/apache/solr/util/SolrCLI.java, solr/core/src/test/org/apache/solr/cloud/cdcr/CdcrBidirectionalTest.java, solr/core/src/test/org/apache/solr/cloud/cdcr/CdcrTestsUtil.java, solr/core/src/test/org/apache/solr/schema/TestCloudSchemaless.java, solr/core/src/test/org/apache/solr/schema/TestPointFields.java, solr/core/src/test/org/apache/solr/security/MockAuthorizationPlugin.java, solr/core/src/test/org/apache/solr/security/PKIAuthenticationIntegrationTest.java, solr/core/src/test/org/apache/solr/update/processor/TestNamedUpdateProcessors.java, solr/core/src/test/org/apache/solr/util/SolrCliUptimeTest.java, solr/solrj/src/java/org/apache/solr/common/luke/FieldFlag.java, solr/solrj/src/java/org/apache/solr/common/util/Utf8CharSequence.java, solr/test-framework/src/java/org/apache/solr/cloud/AbstractFullDistribZkTestBase.java
Fixed a bunch of the smaller warnings found by error-prone compiler
plugin, while ignoring a lot of the bigger ones.
This is just the warnings found by #1176 without the build changes
=> LUCENE-9145 First pass addressing static analysis

dev-docs/README.adoc, dev-docs/pmc-chair.adoc, lucene/dev-docs/README.adoc, solr/dev-docs/README.adoc
Docs for project contributors and committers has historically lived in the wiki (MoinMoin and now Confluence) but there has been discussion over the past 2 years to move this content into the source repository. We also have a low amount of developer-specific documentation for various features, creating barriers for new contributors to participate, and also for existing committers to learn features they are not yet familiar with.
This PR creates a basic structure for project-level and Lucene and Solr specific developer-focused documentation. It includes the following:
- a new top-level directory `dev-docs`, and adds a README file and new documentation geared to PMC Chairs.
- a `lucene/dev-docs` directory, and adds a README as a placeholder (to make Git add the directory)
- a …
=> SOLR-12930: Create developer docs in source repo

.github/workflows/gradle-wrapper-validation.yml
This workflow validates the checksums of Gradle Wrapper JAR files present in the source tree and fails if unknown Gradle Wrapper JAR files are found.
See https://github.com/marketplace/actions/gradle-wrapper-validation
N/A
=> LUCENE-9169: Add Github Workflow for Gradle Wrapper Validation

solr/core/src/java/org/apache/solr/util/TestInjection.java
We track the outstanding Timer but try to remove TimerTask which will never be found in the collection.
Add and remove the same Timer instances.
The javac warning goes away.
=> SOLR-14162 TestInjection can leak Timer objects

solr/core/src/java/org/apache/solr/store/blob/metadata/CorePushPull.java
Number of files and bytes pushed/pulled are logged when pushing to or pulling from blobstore, but values are only accurate when operation is successful. Log expected and actual file count, actual byte count, and add back boolean for whether operation was successful.
Count number of files/bytes actually transferred
Ran ant test, and working on adding additional unit tests.
Logline for successful push:
`PushPullData=[collectionName=gettingstarted shardName=shard1 sharedStoreName=gettingstarted_shard1 coreName=gettingstarted_shard1_replica_s1] action=PUSH storageProvider=LOCAL_FILE_SYSTEM bucketRegion=N/A bucketName=N/A runTime=44325264 startLatency=44325264 bytesTransferred=2076 attempt=0 expectedFilesAffected=10 actualFilesAffected=10 isSuccessful=true localGeneration=2 blobGeneration=-1 ` …
=> SOLR-13101: Log accurate file counts for Push and Pull in CorePushPull

lucene/core/src/test/org/apache/lucene/codecs/lucene60/TestLucene60PointsFormat.java
see https://issues.apache.org/jira/browse/LUCENE-9176
=> LUCENE-9176: Handle the case when there is only one leaf node in TestEstimatePointCount

lucene/CHANGES.txt, lucene/analysis/common/src/java/org/apache/lucene/analysis/core/WhitespaceAnalyzer.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/core/WhitespaceTokenizer.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/core/TestWhitespaceAnalyzer.java
WhitespaceTokenizer defaults to a maximum token length of 255, and WhitespaceAnalyzer
does not allow this to be changed.  This commit adds an optional maxTokenLen parameter
to WhitespaceAnalyzer as well, and documents the existing token length restriction.
=> LUCENE-9153: Allow WhitespaceAnalyzer to set a custom maxTokenLen

lucene/core/src/java/org/apache/lucene/codecs/blocktree/BlockTreeTermsWriter.java, lucene/core/src/java/org/apache/lucene/codecs/blocktree/IntersectTermsEnumFrame.java, lucene/core/src/java/org/apache/lucene/codecs/blocktree/SegmentTermsEnumFrame.java, lucene/core/src/java/org/apache/lucene/codecs/blocktree/Stats.java
Changes include:
- Removed LZ4 compression of suffix lengths which didn't save much space
anyway.
- For stats, LZ4 was only really used for run-length compression of terms whose
docFreq is 1. This has been replaced by explicit run-length compression.
- Since we only use LZ4 for suffix bytes if the compression ration is < 75%, we
now only try LZ4 out if the average suffix length is greater than 6, in order
to reduce index-time overhead.
=> LUCENE-4702: Reduce terms dictionary compression overhead.

solr/core/src/java/org/apache/solr/api/V2HttpCall.java, solr/core/src/java/org/apache/solr/servlet/HttpSolrCall.java
Annotate HttpSolrCall and V2HttpCall as thread-safe
=> SOLR-14206: Annotate HttpSolrCall as thread-safe

lucene/core/src/java/org/apache/lucene/geo/Point2D.java, lucene/core/src/test/org/apache/lucene/geo/TestPoint2D.java
The logic is messed up, this PR fix it. It actually simplifies as well the logic for relateTriangle (I have no idea what I was thinking of in the first implementation :)
=> LUCENE-9197: fix wrong implementation on Point2D#withinTriangle

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/cloud/OverseerSolrResponse.java, solr/core/src/java/org/apache/solr/cloud/OverseerSolrResponseSerializer.java, solr/core/src/java/org/apache/solr/cloud/OverseerTaskProcessor.java, solr/core/src/java/org/apache/solr/handler/admin/CollectionsHandler.java, solr/core/src/java/org/apache/solr/handler/admin/ConfigSetsHandler.java, solr/core/src/test/org/apache/solr/cloud/OverseerCollectionConfigSetProcessorTest.java, solr/core/src/test/org/apache/solr/cloud/OverseerSolrResponseTest.java, solr/core/src/test/org/apache/solr/cloud/OverseerSolrResponseUnsafeSerializationTest.java
This PR is an attempt to fix the serialization incompatibility introduced by SOLR-14095. @andywebb1975 has proposed a different approach in https://github.com/apache/lucene-solr/pull/1210, but I believe this may better resolve the problem. See discussion in https://github.com/apache/lucene-solr/pull/1210
=> SOLR-14219: Revert changes in OverseerSolrRespose and move serialization

solr/core/src/java/org/apache/solr/store/blob/client/BlobCoreMetadata.java, solr/core/src/java/org/apache/solr/store/blob/metadata/CorePushPull.java, solr/core/src/java/org/apache/solr/store/blob/process/BlobDeleterTask.java, solr/core/src/java/org/apache/solr/store/blob/process/CorePullTask.java, solr/core/src/java/org/apache/solr/store/blob/process/CorePullerFeeder.java, solr/core/src/java/org/apache/solr/store/blob/process/CorePusher.java, solr/core/src/java/org/apache/solr/store/blob/util/BlobStoreUtils.java, solr/core/src/test/org/apache/solr/store/blob/client/CoreStorageClientTest.java
Continue logging ms, but use System.nanoTime instead of System.currentTimeMillis for more precise measurement of elapsed time. Specifically updating references from this previous PR: https://github.com/apache/lucene-solr/pull/1117/
Divide nanoseconds by 1000000 to get milliseconds. Converting nanoTime to milliseconds is more precise than using currentTimeMillis because it does not use the system clock time which could face disruptions
Ran ant test and manually examined loglines
=> SOLR-13101: Convert nanotime to ms

solr/core/src/java/org/apache/solr/cloud/Overseer.java, solr/core/src/java/org/apache/solr/cloud/api/collections/DeleteCollectionCmd.java, solr/core/src/java/org/apache/solr/cloud/api/collections/DeleteShardCmd.java, solr/core/src/java/org/apache/solr/store/blob/client/CoreStorageClient.java, solr/core/src/java/org/apache/solr/store/blob/client/LocalStorageClient.java, solr/core/src/java/org/apache/solr/store/blob/client/S3StorageClient.java, solr/core/src/java/org/apache/solr/store/blob/metadata/CorePushPull.java, solr/core/src/java/org/apache/solr/store/blob/process/BlobDeleteManager.java, solr/core/src/java/org/apache/solr/store/blob/process/BlobDeleteProcessor.java, solr/core/src/java/org/apache/solr/store/blob/process/BlobDeleterTask.java, solr/core/src/java/org/apache/solr/store/shared/SharedStoreManager.java, solr/core/src/test/org/apache/solr/store/blob/client/CoreStorageClientTest.java, solr/core/src/test/org/apache/solr/store/blob/process/BlobDeleteProcessorTest.java, solr/core/src/test/org/apache/solr/store/blob/process/SharedStoreDeletionProcessTest.java, solr/core/src/test/org/apache/solr/store/shared/SolrCloudSharedStoreTestCase.java
This PR addS support for shard and collection deletion in shared storage (SOLR-14044) and also includes a major refactor of the existing BlobDeleteManager and deletion code.
The BlobDeleteManager uses refactors the existing async processing machinery and BlobDeleteManager manages two deletion pools now - the existing one for handling normal indexing flow deletion (as we push) and a pool used specifically by the Overseer for handling collection and shard deletion. 
Currently working on a another test that I should add soon but the rest is review-able.
=> SOLR-14044: Support collection and shard deletion in shared storage

lucene/core/src/java/org/apache/lucene/util/automaton/FrozenIntSet.java, lucene/core/src/java/org/apache/lucene/util/automaton/IntSet.java, lucene/core/src/java/org/apache/lucene/util/automaton/Operations.java, lucene/core/src/java/org/apache/lucene/util/automaton/SortedIntSet.java, lucene/core/src/test/org/apache/lucene/util/automaton/TestIntSet.java
Fix a bug where a frozen set could be symmetrically unequal to the
sorted set that created it because we compared the backing array
instead of only the active elements.
=> LUCENE-9142 Refactor IntSet operations for determinize

solr/core/src/test/org/apache/solr/cloud/autoscaling/IndexSizeTriggerMixedBoundsTest.java, solr/test-framework/src/java/org/apache/solr/SolrTestCase.java
This test is slow because it sleeps a lot. Removing the sleeps, it still passes consistently on my machine, but I would like other folks to confirm this on their different hardware as well.
=> SOLR-14247 Remove unneeded sleeps

lucene/core/src/java/org/apache/lucene/util/compress/LZ4.java, lucene/core/src/test/org/apache/lucene/util/compress/LZ4TestCase.java, lucene/core/src/test/org/apache/lucene/util/compress/TestFastLZ4.java, lucene/core/src/test/org/apache/lucene/util/compress/TestHighLZ4.java
This time they would only apply to TestFastLZ4/TestHighLZ4 and avoid slowing
down all tests.
=> Add back assertions removed by LUCENE-9187.

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/geo/Line2D.java, lucene/core/src/java/org/apache/lucene/geo/Polygon2D.java, lucene/core/src/java/org/apache/lucene/geo/Tessellator.java, lucene/core/src/java/org/apache/lucene/geo/XYEncodingUtils.java, lucene/core/src/java/org/apache/lucene/geo/XYLine.java, lucene/core/src/java/org/apache/lucene/geo/XYPoint.java, lucene/core/src/java/org/apache/lucene/geo/XYPolygon.java, lucene/core/src/java/org/apache/lucene/geo/XYRectangle.java, lucene/core/src/java/org/apache/lucene/geo/XYRectangle2D.java, lucene/core/src/test/org/apache/lucene/document/BaseXYShapeTestCase.java, lucene/core/src/test/org/apache/lucene/document/TestXYLineShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestXYMultiLineShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestXYMultiPointShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestXYMultiPolygonShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestXYPointShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestXYPolygonShapeQueries.java, lucene/core/src/test/org/apache/lucene/document/TestXYShape.java, lucene/core/src/test/org/apache/lucene/document/TestXYShapeEncoding.java, lucene/core/src/test/org/apache/lucene/geo/ShapeTestUtil.java, lucene/core/src/test/org/apache/lucene/geo/TestXYLine.java, lucene/core/src/test/org/apache/lucene/geo/TestXYPoint.java, lucene/core/src/test/org/apache/lucene/geo/TestXYPolygon.java, lucene/core/src/test/org/apache/lucene/geo/TestXYRectangle.java, lucene/core/src/test/org/apache/lucene/geo/TestXYRectangle2D.java
Boxing the values to doubles happen when creating component2D objects.
=> LUCENE-9218: XYGeometries should expose values as floats

solr/contrib/analysis-extras/README.txt
Update the analysis-extras README to include reference to including solr-analysis-extras jar.
I struggled to work out what was missing when I was using ICU for the first time, and this caught me out. There may be a better way of phrasing it.
=> Update README.txt for analysis-extras

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/codecs/lucene80/Lucene80DocValuesConsumer.java, lucene/core/src/java/org/apache/lucene/codecs/lucene80/Lucene80DocValuesFormat.java, lucene/core/src/java/org/apache/lucene/codecs/lucene80/Lucene80DocValuesProducer.java, lucene/test-framework/src/java/org/apache/lucene/index/BaseDocValuesFormatTestCase.java
This PR stores groups of 32 doc values in LZ4 compressed blocks. 
Test results for loading 680mb of log data (1.8m docs) are as follows:
Branch | Load time (seconds, single thread) | Resulting index size (mb)
----|----|----
master| 16| 680
this PR| 11| 78
Time taken to read 5,000 random doc IDs from above indices
Branch | Read time (milliseconds, single thread) 
----|----
master| 284
this PR| 63
On this particular test, the read + write speeds and resulting index size were all improved over the current master implementation. Obviously performance will vary with other tests with the main factors for changes being:
* size of fields, 
* compress-ability of field contents,
* read access patterns (hitting same compressed blocks vs different ones)
* variation from doc-to-doc in field value …
=> LUCENE-9211 Add compression for Binary doc value fields

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/codecs/lucene80/Lucene80DocValuesConsumer.java, lucene/core/src/java/org/apache/lucene/codecs/lucene80/Lucene80DocValuesFormat.java, lucene/core/src/java/org/apache/lucene/codecs/lucene80/Lucene80DocValuesProducer.java, lucene/test-framework/src/java/org/apache/lucene/index/BaseDocValuesFormatTestCase.java
(cherry picked from commit ce2959fe4cb1d1e77df04464c46004bf7846f6b5)
=> LUCENE-9211 Add compression for Binary doc value fields (#1234)

solr/core/src/java/org/apache/solr/cloud/api/collections/CreateCollectionCmd.java, solr/core/src/java/org/apache/solr/core/CoreContainer.java, solr/core/src/java/org/apache/solr/core/NodeConfig.java, solr/core/src/java/org/apache/solr/core/SharedStoreConfig.java, solr/core/src/java/org/apache/solr/core/SolrXmlConfig.java, solr/core/src/java/org/apache/solr/store/blob/metadata/ServerSideMetadata.java, solr/core/src/java/org/apache/solr/store/blob/process/BlobProcessUtil.java, solr/core/src/java/org/apache/solr/store/blob/process/CorePullTask.java, solr/core/src/java/org/apache/solr/store/blob/process/CorePullerFeeder.java, solr/core/src/java/org/apache/solr/store/blob/process/CoreSyncFeeder.java, solr/core/src/java/org/apache/solr/store/shared/SharedCoreConcurrencyController.java, solr/core/src/java/org/apache/solr/store/shared/SharedStoreManager.java, solr/core/src/test-files/solr/solr-sharedstore.xml, solr/core/src/test/org/apache/solr/cloud/api/collections/SharedStorageShardMetadataTest.java, solr/core/src/test/org/apache/solr/cloud/api/collections/SimpleSharedStorageCollectionTest.java, solr/core/src/test/org/apache/solr/store/blob/SharedStorageSplitTest.java, solr/core/src/test/org/apache/solr/store/shared/SharedCoreConcurrencyTest.java, solr/core/src/test/org/apache/solr/store/shared/SharedStoreMissingCoreTest.java, solr/core/src/test/org/apache/solr/store/shared/SimpleSharedStoreEndToEndPullTest.java, solr/core/src/test/org/apache/solr/store/shared/SimpleSharedStoreEndToEndPushTest.java, solr/core/src/test/org/apache/solr/store/shared/SolrCloudSharedStoreTestCase.java, solr/core/src/test/org/apache/solr/store/shared/metadata/SharedShardMetadataControllerTest.java, solr/core/src/test/org/apache/solr/update/processor/DistributedZkUpdateProcessorTest.java
This is an initial PR that allows Solr Cloud to be configured to use shared storage or not. Prior to this, shared storage is "on" by default with components be lazily initialized as needed e.g. when a collection of type shared is created. This of course is difficult to do correctly. 
The solution proposed by this PR is check for the presence of a <sharedStorage> section in solr.xml that indicates the user's intention to use shared storage and initiate the components on startup. This also sets the stage for future work we need to do to move some hard coded values into configurable parameters that would be specified in sharedStorage. See the JIRA for further discussion. 
Changes:
- solr.xml supports a bare-bone <sharedStorage></sharedStorage> section that should be added to enable shared …
=> SOLR-14213: Configuring Solr Cloud to use Shared Storage

lucene/core/src/java/org/apache/lucene/util/hnsw/HNSWGraph.java
`if (dist < f.distance() || results.size() < ef) {
Neighbor n = new ImmutableNeighbor(e.docId(), dist);
candidates.add(n);
results.insertWithOverflow(n);
f = results.top();
}` 
If (dist < f.distance()) but results.size() >= ef, the "Neighbor n" would be added to "results" ("results" is a sub-type of PriorityQueue). The actual size of "results" would be between "ef" and results' max queue size, while its expected size is "ef". Moreover, this bug could have negative effect on performance.
Consider the following situation in [HNSWGraphReader](https://github.com/apache/lucene-solr/blob/jira/lucene-9004-aknn-2/lucene/core/src/java/org/apache/lucene/util/hnsw/HNSWGraphReader.java):
`FurthestNeighbors neighbors = new FurthestNeighbors(ef, ep);
for (int l = hnsw.topLevel(); l > 0; l--) { …
=> Lucene-9004: bug fix for searching the nearest one neighbor in higher layers

lucene/core/src/java/org/apache/lucene/index/FilterMergePolicy.java, lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/java/org/apache/lucene/index/IndexWriterConfig.java, lucene/core/src/java/org/apache/lucene/index/IndexWriterEvents.java, lucene/core/src/java/org/apache/lucene/index/LiveIndexWriterConfig.java, lucene/core/src/java/org/apache/lucene/index/MergePolicy.java, lucene/core/src/java/org/apache/lucene/index/MergeTrigger.java, lucene/core/src/java/org/apache/lucene/index/NoMergePolicy.java, lucene/core/src/java/org/apache/lucene/index/OneMergeWrappingMergePolicy.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterMergePolicy.java, lucene/test-framework/src/java/org/apache/lucene/index/MockRandomMergePolicy.java, lucene/test-framework/src/java/org/apache/lucene/util/LuceneTestCase.java
If we have many index writer threads, they will flush their DWPT buffers
on commit, resulting in many small segments, which can be merged before
the commit returns.
This adds a new "findCommitMerges" method to MergePolicy, which can specify merges to be executed as part of preparing a commit. By default, we return null for backward compatibility (i.e. don't merge on commit).
In IndexWriter, we call findCommitMerges from prepareCommitInternal, after we have cloned the SegmentInfos. If we found commit merges, we wrap each OneMerge so that on completion, they update the cloned SegmentInfos and reference counts of segment files. Outside the flush lock, we wait (up to max time specified in IndexWriterConfig) for the commit merges to complete before calling startCommit. 
Also, added an …
=> LUCENE-8962: Add ability to selectively merge on commit

lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterMergePolicy.java
1. TestIndexWriterMergePolicy.testMergeOnCommit will fail if the last
commit (the one that should trigger the full merge) doesn't have any
pending changes (which could occur if the last indexing thread
commits at the end). We can fix that by adding one more document
before that commit.
2. The previous implementation was throwing IOException if the commit
thread gets interrupted while waiting for merges to complete. This
violates IndexWriter's documented behavior of throwing
ThreadInterruptedException.
This fixes intermittent test failures related to the previous commit on LUCENE-8962.
There were two separate bugs in the previous commit:
1. TestIndexWriterMergePolicy.testMergeOnCommit could sometimes fail the last assertion, because the final commit in the test method triggered no merges. …
=> LUCENE-8962: Fix intermittent test failures

lucene/CHANGES.txt, lucene/queries/src/java/org/apache/lucene/queries/function/FunctionValues.java, lucene/queries/src/java/org/apache/lucene/queries/function/ValueSourceScorer.java, lucene/queries/src/test/org/apache/lucene/queries/function/TestFunctionRangeQuery.java
This commit makes ValueSourceScorer's costing algorithm also take the delegated FunctionValues's cost into consideration when calculating its cost.
=> LUCENE-9114: Improve ValueSourceScorer's Default Cost Implementation

lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/java/org/apache/lucene/index/MergePolicy.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterMergePolicy.java
The testMergeOnCommit test case was trying to verify too many things
at once: basic semantics of merge on commit and proper behavior when
a bunch of indexing threads are writing and committing all at once.
Splitting the test into two should make the tests more robust - one
will verify basic behavior, with strict assertions on invariants, while
the other just verifies that everything gets indexed and we don't throw
an exception when multiple threads are indexing and merging on commit.
Also, the part of the test that is now testMultithreadedMergeOnCommit
can take several seconds to run, so moving it to the @Nightly set.
Fixing an intermittent test failure on testMergeOnCommit.
Split the logic from testMergeOnCommit into two test cases. The basic test has consistently passed, and actually …
=> LUCENE-8962: Split test case

dev-tools/scripts/addBackcompatIndexes.py
This is dead code in a python script. We don't use svn anymore. I did not add corresponding git commands since the releaseWizard explicitly does an add after running the script, and noone has complained for so long time :) 
Tagging @sarowe since it seems you have touched this script in the past
=> Remove some unused lines from addBackcompatIndexes.py related to svn

lucene/core/src/java/org/apache/lucene/codecs/blocktree/BlockTreeTermsReader.java
See https://issues.apache.org/jira/browse/LUCENE-9272.
=> LUCENE-9272: Move checksum verification of the `.tip` file to `checkIntegrity()`.

lucene/CHANGES.txt, lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/util/DictionaryBuilder.java
The normalizeEntry option is missing from the Javadoc of Kuromoji DictionaryBuilder.
Without this explanation, users don't know what it means until they see the code.
Also, if user follows the usage of Javadoc, it will not be built.
Please check the following JIRA issue:
[LUCENE-9270](https://issues.apache.org/jira/browse/LUCENE-9270)
=> LUCENE-9270: Update Javadoc about normalizeEntry in the Kuromoji DictionaryBuilder

solr/CHANGES.txt, solr/solrj/src/java/org/apache/solr/common/util/JavaBinCodec.java, solr/solrj/src/test/org/apache/solr/common/util/TestJavaBinCodec.java
there was an unchecked type conversion warning in JavaBinCodec's readMapEntry's equals() method
fixed an unchecked type conversion warning in JavaBinCodec's readMapEntry's equals() method
added tests per @noblepaul 's comments on the previous pr [https://github.com/apache/lucene-solr/pull/1335]
- please do note that no tests existed for this api prior to this so I had to think how to set a baseline here
- however now we have a a test case for this api oh JavaBinCodec, with decent boundary value code coverage
- I tested for backward compatibility between the code change by running the same boundary value analysis of tests, with the new and old api implementation and the test results are the same
Some Observations
- so from these tests, one can surmise that the JavaBinCodec.readMapEntry() …
=> SOLR-14316 Remove unchecked type conversion warning in JavaBinCodec's readMapEntry's equals() squashed

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThread.java, lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterExceptions.java
Today we have a large amount of duplicated code that is rather of
complex nature. This change consolidates the code-paths to always
use the updateDocuments path.
=> LUCENE-9276: Use same code-path for updateDocuments and updateDocument

solr/solr-ref-guide/src/solr-upgrade-notes.adoc, solr/solr-ref-guide/src/the-tagger-handler.adoc
=> SOLR-14254: Docs for text tagger: FST50 trade-off

solr/solr-ref-guide/src/common-query-parameters.adoc
I was trying to explain Solr's not-completely-deterministic `sort` param resolution to a coworker this week, and realized that this behavior wasn't documented afaict.
A short ref-guide change to mention the tie-break behavior.
=> Document sort param tiebreak logic

solr/core/src/java/org/apache/solr/cloud/api/collections/CreateCollectionCmd.java, solr/core/src/java/org/apache/solr/cloud/api/collections/CreateShardCmd.java, solr/core/src/java/org/apache/solr/cloud/api/collections/SplitShardCmd.java, solr/core/src/java/org/apache/solr/handler/admin/RequestApplyUpdatesOp.java, solr/core/src/java/org/apache/solr/store/shared/SharedCoreConcurrencyController.java, solr/core/src/java/org/apache/solr/store/shared/SharedStoreManager.java, solr/core/src/java/org/apache/solr/store/shared/metadata/SharedShardMetadataController.java, solr/core/src/test/org/apache/solr/cloud/api/collections/SimpleSharedStorageCollectionTest.java, solr/core/src/test/org/apache/solr/store/blob/metadata/CorePushPullTest.java, solr/core/src/test/org/apache/solr/store/shared/SharedCoreConcurrencyTest.java, solr/core/src/test/org/apache/solr/store/shared/metadata/SharedShardMetadataControllerTest.java
Shared collections make use of something called the metadataSuffix znode per shard in ZooKeeper to understand what core.metadata file to pull from blob store and hydrate a replica with the most up-to-date and correct index data. Shared collections would create the node on-demand with a default value (e.g. indexing) but this is not correct behavior when considering restore operations in the future. We'll want to create the node with a non-default value down the line. 
This change initiates the node when we create the shard in common collection API commands and includes CREATE, CREATESHARD, SPLITSHARD. Other operations such as RESTORE are not currently supported by solr shared storage so are not in scope of this change.
=> SOLR-13101: Create metadataSuffix znode only at common shard creating api calls

lucene/core/src/java/org/apache/lucene/index/DefaultIndexingChain.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThread.java
DWPT had some complicated logic to account for failures etc.
This change cleans up this logic and simplifies the document processing
loop.
=> Cleanup DWPT for readability

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/component/ExpandComponent.java, solr/core/src/java/org/apache/solr/search/DocSlice.java, solr/core/src/test/org/apache/solr/handler/component/DistributedExpandComponentTest.java, solr/core/src/test/org/apache/solr/handler/component/TestExpandComponent.java, solr/solr-ref-guide/src/collapse-and-expand-results.adoc
Enables ExpandComponent to allow expand.hits=0 for those who don't want an expanded document returned and only want the numFound returned from the expand section.
We have been using this patch in our internal fork of SOLR for years so this has been thoroughly tested to ensure this functionality works as desired. Unit tests have been added for this functionality and all tests pass.
=> SOLR-8306: Enhance ExpandComponent to allow expand.hits=0

lucene/default-nested-ivy-settings.xml
The ivy settings config has a local maven repo resolver (added by @dweiss 8 years ago).  It's commented out so it's not essential that we get it right.  It has a bug in the pattern that forgot the classifier.
https://stackoverflow.com/questions/8617963/ivysettings-xml-add-local-maven-path
Locally I configure the build to use the local maven repo and this has been a problem because spatial4j's main JAR file is resolved when trying to get the test JAR!
(I don't think I need a JIRA for this but I can create one if someone really wants that ceremony)
=> ivy settings: local maven repo pattern needs classifier

solr/bin/solr, solr/core/src/java/org/apache/solr/core/SharedStoreConfig.java, solr/core/src/java/org/apache/solr/core/SolrXmlConfig.java, solr/core/src/test-files/solr/solr-sharedstore.xml, solr/core/src/test/org/apache/solr/cloud/api/collections/SimpleSharedStorageCollectionTest.java
Enhancing the configuration section to allow shared storage feature to be enabled via system properties vs just checking for presence of <sharedStore> section in solr.xml.
```
<sharedStore>
<bool name="sharedStoreEnabled">${sharedStoreEnabled:false}</bool>
</sharedStore>
```
Shared storage is now only enabled if cloud mode is on, <sharedStore> section is present, and the field sharedStoreEnabled is present and set to true. If <sharedStore> is present but the field isn't, startup fails. The field supports system properties overriding whatever default is specified. This can be passed in via the solr binary such as 
`bin/solr start -e cloud -noprompt -DsharedStoreEnabled=true` 
or set by specifying the environment variable SHARE_STORE_ENABLED.
=> SOLR-14213: Allow enabling shared store to be scriptable

solr/core/src/java/org/apache/solr/store/blob/metadata/ServerSideMetadata.java, solr/core/src/java/org/apache/solr/store/blob/process/CorePullTask.java, solr/core/src/java/org/apache/solr/store/blob/process/CorePusher.java, solr/core/src/java/org/apache/solr/store/blob/util/BlobStoreUtils.java, solr/core/src/test/org/apache/solr/store/blob/metadata/CorePushPullTest.java
Slight optimizations in ServerSideMetadata given that push operations do not require computing a directory hash of a core's index directory. This change makes the computation optional and resilient by also moving the optional computation to the latest commit capture's retry loop. 
If we hit an exception (file not found, etc) either capturing files from the latest commit or during the hash computation (if captureDirHash=true), we should try and recompute both snapshots anyway.
=> SOLR-13101: Make dir hash computation optional and resilient

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/UsageTrackingQueryCachingPolicy.java, lucene/core/src/test/org/apache/lucene/search/TestUsageTrackingFilterCachingPolicy.java
see https://issues.apache.org/jira/browse/LUCENE-9287
=> LUCENE-9287:Add DocValuesFieldExistsQuery as a never cache query in UsageTrackingQueryCachingPolicy

solr/core/src/java/org/apache/solr/util/SolrLogPostTool.java, solr/core/src/test/org/apache/solr/util/SolrLogPostToolTest.java
The SolrLogParseTool parses most log records containing the string "QTime=" as being a query. While this is useful, the designation would be a little more helpful if operations with a different performance profile were broken out into their own "type_s" value. That gives users the ability to view them together or separately, as they prefer.
Change the parsing code in SolrLogParseTool to check specifically for "/get" requests when parsing query requests.  Other than settings "type_s" and "id_s" all other fields are handled in a way identical to other queries
A unit test for the new "rtg" type_s value.
=> SOLR-14363: Separate /get requests into their own type designation

gradle/render-javadoc.gradle, gradle/validation/missing-docs-check.gradle
For gradle build, use absolute urls instead of relative paths to make inter-project links so that javadoc destination directory can be moved under `_project_/build/`.
- docs of ":lucene:core" prj will go to `lucene/core/build/docs/javadoc/`
- docs of ":lucene:analysis:common" will go to `lucene/analysis/common/build/docs/javadoc/`
- docs of ":solr:core" prj will go to `solr/core/build/docs/javadoc/`
- ... and so on
Also, this directly calls [javadoc tool](https://docs.oracle.com/en/java/javase/11/tools/javadoc.html) rather than Ant javadoc task - Ant javadoc task doesn't recognize `element-list`, the successor to `package-list` up until Java 8, so `<link offline="true" ...>` no longer correctly work with JDK11 (https://issues.apache.org/jira/browse/SOLR-14352).
All generated docs passed …
=> LUCENE-9278: Use -linkoffline instead of relative paths to make links to other projects

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/BufferedUpdates.java, lucene/core/src/test/org/apache/lucene/index/TestBufferedUpdates.java
the method clearDeletedDocIds in BufferedUpdates.java has a bug, it can't reset bytesUsed correctly.
```java
void clearDeletedDocIds() {
deleteDocIDs.clear();
bytesUsed.addAndGet(-deleteDocIDs.size() * BufferedUpdates.BYTES_PER_DEL_DOCID);
}
```
this PR will fix it.
=> LUCENE-9298: Improve RAM accounting in BufferedUpdates when deleted doc IDs and terms are cleared

lucene/core/src/java/org/apache/lucene/util/fst/FST.java
This fixes some compiler warnings popped up recently.
=> LUCENE-9286: In FST, avoid using raw types.

lucene/core/src/java/org/apache/lucene/index/BufferedUpdates.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThread.java, lucene/core/src/java/org/apache/lucene/index/FrozenBufferedUpdates.java, lucene/core/src/test/org/apache/lucene/index/TestBufferedUpdates.java
This change moves the deletes tracked by FrozenBufferedUpdates that
are private to the DWPT and never used in a global context out of
FrozenBufferedUpdates.
=> Move DWPT private deletes out of FrozenBufferedUpdates

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/ConcurrentMergeScheduler.java, lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/test/org/apache/lucene/index/TestConcurrentMergeScheduler.java
CMS today releases it's lock after finishing a merge before it re-acquires it to update
the thread accounting datastructures. This causes threading issues where concurrently
finishing threads fail to pick up pending merges causing potential thread starvation
on forceMerge calls.
=> LUCENE-9337: Ensure CMS updates it's thread accounting datastructures consistently

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/ConcurrentMergeScheduler.java, lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/java/org/apache/lucene/index/MergeScheduler.java, lucene/core/src/java/org/apache/lucene/index/NoMergeScheduler.java, lucene/core/src/java/org/apache/lucene/index/SerialMergeScheduler.java, lucene/core/src/test/org/apache/lucene/TestMergeSchedulerExternal.java, lucene/core/src/test/org/apache/lucene/index/TestConcurrentMergeScheduler.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterMerging.java, lucene/core/src/test/org/apache/lucene/index/TestNoMergeScheduler.java, lucene/test-framework/src/java/org/apache/lucene/index/BaseMergePolicyTestCase.java
IW#maybeMerge calls the MergeScheduler even if it didn't find any merges we should
instead only do this if there is in-fact anything there to merge and safe the call
into a sync'd method.
=> LUCENE-9339: Only call MergeScheduler when we actually found new merges

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java, lucene/core/src/java/org/apache/lucene/search/TopFieldCollector.java, lucene/core/src/java/org/apache/lucene/search/TopScoreDocCollector.java, lucene/core/src/test/org/apache/lucene/search/TestTopDocsCollector.java, lucene/core/src/test/org/apache/lucene/search/TestTopFieldCollector.java
While looking at SOLR-13289 I noticed this situation. If I create a collector with `numHits` greater than `totalHitsThreshold`, and the number of hits in the query is somewhere between those two numbers, collector’s `totalHitRelation` will be `TotalHits.Relation.GREATER_THAN_OR_EQUAL_TO`, however I expect the count to be accurate in this situation, right? Should this be `TotalHits.Relation.EQUAL_TO`? Maybe make `totalHitsThreshold = Max(totalHitsThreshold, humHits)` on creation? Added a test that fails.
=> LUCENE-9342: Collector's totalHitsThreshold should not be lower than numHits

lucene/CHANGES.txt, lucene/expressions/src/java/org/apache/lucene/expressions/ExpressionValueSource.java, lucene/expressions/src/java/org/apache/lucene/expressions/SimpleBindings.java, lucene/expressions/src/test/org/apache/lucene/expressions/TestExpressionValidation.java
Replaces SimpleBindings' `Map<String, Object>` with a map of 
`Supplier<DoubleValuesSource>` to improve type safety.  Also moves cycle
detection directly into ExpressionValuesSource.
=> LUCENE-9338: Clean up type safety in SimpleBindings

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/ConcurrentMergeScheduler.java, lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/java/org/apache/lucene/index/MergePolicy.java, lucene/core/src/java/org/apache/lucene/index/MergeScheduler.java, lucene/core/src/java/org/apache/lucene/index/NoMergeScheduler.java, lucene/core/src/java/org/apache/lucene/index/SerialMergeScheduler.java, lucene/core/src/test/org/apache/lucene/TestMergeSchedulerExternal.java, lucene/core/src/test/org/apache/lucene/index/TestConcurrentMergeScheduler.java, lucene/core/src/test/org/apache/lucene/index/TestForceMergeForever.java, lucene/core/src/test/org/apache/lucene/index/TestIndexFileDeleter.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriter.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterMerging.java, lucene/core/src/test/org/apache/lucene/index/TestTragicIndexWriterDeadlock.java, lucene/sandbox/src/test/org/apache/lucene/codecs/idversion/TestIDVersionPostingsFormat.java, lucene/test-framework/src/java/org/apache/lucene/index/BaseMergePolicyTestCase.java, lucene/test-framework/src/java/org/apache/lucene/index/SuppressingConcurrentMergeScheduler.java, lucene/test-framework/src/java/org/apache/lucene/util/LuceneTestCase.java, solr/core/src/java/org/apache/solr/update/SolrIndexWriter.java, solr/test-framework/src/java/org/apache/solr/core/MockConcurrentMergeScheduler.java
This change extracts the methods that are used by MergeScheduler into
a MergeSource interface. This allows IndexWriter to better ensure
locking, hide internal methods and removes the tight coupling between the two
complex classes. This will also improve future testing.
=> LUCENE-9345: Separate MergeSchedulder from IndexWriter

lucene/core/src/java/org/apache/lucene/index/BufferedUpdatesStream.java, lucene/core/src/java/org/apache/lucene/index/FrozenBufferedUpdates.java, lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
Today we still have one class that runs some tricky logic that should
be in the IndexWriter in the first place since it requires locking on
the IndexWriter itself. This change inverts the API and now FrozendBufferedUpdates
does not get the IndexWriter passed in, instead the IndexWriter owns most of the logic
and executes on a FrozenBufferedUpdates object. This prevent locking on IndexWriter out
side of the writer itself and paves the way to simplify some concurrency down the road
=> Consolidate all IW locking inside IndexWriter

lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterFlushControl.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThread.java, lucene/core/src/java/org/apache/lucene/index/IndexFileDeleter.java, lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/test/org/apache/lucene/index/TestAddIndexes.java, lucene/core/src/test/org/apache/lucene/index/TestConcurrentMergeScheduler.java, lucene/core/src/test/org/apache/lucene/index/TestFlushByRamOrCountsPolicy.java, lucene/core/src/test/org/apache/lucene/index/TestForceMergeForever.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriter.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterDelete.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterExceptions.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterExceptions2.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterMaxDocs.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterOnDiskFull.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterWithThreads.java, lucene/core/src/test/org/apache/lucene/index/TestPerSegmentDeletes.java, lucene/core/src/test/org/apache/lucene/index/TestSoftDeletesRetentionMergePolicy.java, lucene/core/src/test/org/apache/lucene/index/TestTieredMergePolicy.java, lucene/core/src/test/org/apache/lucene/index/TestTragicIndexWriterDeadlock.java, lucene/test-framework/src/java/org/apache/lucene/index/BaseIndexFileFormatTestCase.java
Today it looks like wild wild west inside IndexWriter and some of it's
associated classes. This change makes sure all non-final members have
private visibility, methods that are not used outside of IW today are
made private unless they have been public. This change also removes
some unused or unnecessary members where possible and deleted some dead
code from previous refactoring.
=> Fix visibility on member variables in IndexWriter and friends

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java, lucene/core/src/java/org/apache/lucene/search/QueryVisitor.java, lucene/core/src/java/org/apache/lucene/search/TermInSetQuery.java, lucene/core/src/java/org/apache/lucene/util/automaton/CompiledAutomaton.java, lucene/core/src/test/org/apache/lucene/search/TermInSetQueryTest.java, lucene/highlighter/src/java/org/apache/lucene/search/uhighlight/MultiTermHighlighting.java
TermInSetQuery currently iterates through all its prefix-encoded terms 
in order to build an array to pass back to its visitor when visit() is called.  
This seems like a waste, particularly when the visitor is not actually 
consuming the terms (for example, when doing a clause-count check 
before executing a search).  This commit changes TermInSetQuery to use 
consumeTermsMatching(), and also changes the signature of this method so 
that it takes a BytesRunAutomaton supplier to allow for lazy instantiation.  In
addition, IndexSearcher's clause count check wasn't counting leaves that
called consumeTermsMatching().
=> LUCENE-9349: TermInSetQuery should use consumeMatchingTerms in visit()

gradle/render-javadoc.gradle
This should fix the missing escaping of options in the javadocs options task.
=> LUCENE-9278: Fix javadocs task to work on windows and with whitespace in project folder

gradle/generation/snowball.gradle, lucene/CHANGES.txt, lucene/analysis/common/src/resources/org/apache/lucene/analysis/snowball/french_stop.txt
This new version removed some French homonyms from the list
Sync French stop words with latest version from Snowball.
This new version removed some French homonyms from the list
None, I am a French native speaker and reviewed the stop words myself.
=> LUCENE-9354: Sync French stop words with latest version from Snowball.

gradle/render-javadoc.gradle
Improved version of the options file creator in the renderJavadocs task: All parameters are escaped automatically, arguments don't need to be strings (they are converted during building options file). This makes it easy to use (adding new options) and e.g., filenames are escaped correctly
=> LUCENE-9278: Improved options file creation

lucene/core/src/java/org/apache/lucene/search/FuzzyAutomatonBuilder.java, lucene/core/src/java/org/apache/lucene/search/FuzzyQuery.java, lucene/core/src/java/org/apache/lucene/search/FuzzyTermsEnum.java, lucene/core/src/java/org/apache/lucene/search/MultiTermQuery.java, lucene/core/src/test/org/apache/lucene/search/TestFuzzyQuery.java
LUCENE-9068 moved fuzzy automata construction into FuzzyQuery itself.  However,
this has the nasty side-effect of blowing up query caches that expect queries to be 
fairly small.  This commit restores the previous behaviour of caching the large automata
on an AttributeSource shared between segments, while making the construction a
bit clearer by factoring it out into a package-private `FuzzyAutomatonBuilder`.
=> LUCENE-9350: Don't hold references to large automata on FuzzyQuery

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/codecs/CodecUtil.java, lucene/core/src/test/org/apache/lucene/codecs/TestCodecUtil.java, lucene/core/src/test/org/apache/lucene/util/TestOfflineSorter.java
See https://issues.apache.org/jira/browse/LUCENE-7822.
=> LUCENE-7822: CodecUtil#checkFooter should throw a CorruptIndexException as the main exception.

lucene/core/src/java/org/apache/lucene/search/FuzzyQuery.java, lucene/core/src/test/org/apache/lucene/search/TestFuzzyQuery.java
Fix for Jira issue [9365](https://issues.apache.org/jira/browse/LUCENE-9365) where search for `abc` doesn't match doc `abcd` if prefixlength = 3 and edit distance =1.
The solution is to rewrite the FuzzyQuery as a RegExpQuery given this condition.
Added related test to TestFuzzyQuery.
=> Bug fix for false negatives produced by FuzzyQuery

lucene/core/src/java/org/apache/lucene/search/FuzzyQuery.java, lucene/core/src/test/org/apache/lucene/search/TestFuzzyQuery.java
This reverts commit 28e47549c8ba1a7c17ffe7d9e791e88983ef46c2.
The use of RegExpQuery as a fallback has to consider that the search string may contain characters which are illegal regex syntax and need escaping.
Will rethink the approach.
=> Revert "Bugfix for FuzzyQuery false negative (#1493)"

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/FuzzyAutomatonBuilder.java, lucene/core/src/java/org/apache/lucene/search/FuzzyQuery.java, lucene/core/src/java/org/apache/lucene/search/FuzzyTermsEnum.java, lucene/core/src/java/org/apache/lucene/search/MultiTermQuery.java, lucene/core/src/test/org/apache/lucene/search/TestFuzzyQuery.java, solr/core/src/java/org/apache/solr/handler/component/QueryComponent.java, solr/core/src/test/org/apache/solr/search/FuzzySearchTest.java
It may be worthwhile to review this by individual commits instead of all at once. I do not intend to squash these when committing.
I'm most concerned about whether the changes in commit 3363df7 are sufficient - they are enough for API and compilation, but it's not clear if I needed to update some implementations of QueryVisitor to tie all of this together.
=> Backport LUCENE-9350 to branch_8_5

solr/core/src/java/org/apache/solr/update/CommitTracker.java
Adding this to https://issues.apache.org/jira/browse/SOLR-14351 even though it's not a perfect fit.
As an aside, I've seen MDC missing logs from searcher warming QuerySenderListener.  There's another JIRA issue for that one indirectly fixed via stacking SolrRequestInfo.
=> SOLR-14351: commitScheduler was missing MDC logging

lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java, lucene/core/src/test/org/apache/lucene/search/TestRegexpQuery.java, lucene/core/src/test/org/apache/lucene/util/automaton/TestRegExp.java
Jira Issue [9336](https://issues.apache.org/jira/browse/LUCENE-9336) proposes adding support for common regex character classes like `\w`.
This PR adds the code to RegExp.java and associated tests.
One other consideration is that the shorthand expressions list could perhaps be made configurable e.g. `\h` might be shorthand used to represent hashtags of the form `#\w*` if that was something users routinely searched for and wanted to add to the regex vocabulary.
=> RegEx querying - add support for Java’s predefined character classes like \d for digits

lucene/CHANGES.txt, lucene/MIGRATE.md, lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java, lucene/core/src/test/org/apache/lucene/search/TestRegexpQuery.java, lucene/core/src/test/org/apache/lucene/util/automaton/TestRegExp.java
This prevents illegal backslash syntax from user searches being accepted now and throws an error instead.
This echoes the [Java Pattern policy](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html#bs) which is designed to allow future expansion to the regex syntax without conflict. It also corrects any misconceptions users might have about predefined character classes we do not support.
This PR also fixes a bug introduced in Lucene-9336 where searches for `\\` would crash.
=> Lucene 9370: Remove leniency on illegal backslashes in RegExp query

lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java
The RegExp parser holds a useful representation of the parsed logic in a regular expression but does not have a public API that would allow the objects to be transformed to new forms e.g. to render to an English explanation of the logic.
This PR exposes that capability by making the internal fields public and final. I toyed with the idea of just adding getter methods but the internal state of this class should ideally be made immutable anyway so instead I opted for making the parsed fields final.
=> Lucene-9371: Allow external access to RegExp's parsed structure

build.gradle, gradle/validation/check-broken-links.gradle, gradle/validation/documentation-lint.gradle
~This adds `documentationLint` task to gradle build.~ This adds `checkBrokenLinks` task to gradle build. The task is a placeholder for `:lucene:checkBrokenLinks` and `:solr:checkBrokenLinks` that detect broken or invalid links in docs under `_project_/build/documentation`. 
For now, both check tasks fail as there are broken links in the javadocs.
See also https://issues.apache.org/jira/browse/LUCENE-9374
```
./gradlew checkBrokenLinks
```
or 
```
./gradlew :lucene:checkBrokenLinks
./gradlew :solr:checkBrokenLinks
```
- I added `documentationLint` task that wraps `checkBrokenLinks` to align semantics with `documentation` task, but it can be removed if not needed.
- `documentation-lint.gradle` could be placed under `gradle/documentation` ?
=> LUCENE-9374: Add checkBrokenLinks gradle task

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java, solr/core/src/test/org/apache/solr/search/SolrIndexSearcherTest.java, solr/core/src/test/org/apache/solr/search/TestCollapseQParserPlugin.java
Fixes a bug @dsmiley pointed out to in [SOLR-13289](https://issues.apache.org/jira/browse/SOLR-13289?focusedCommentId=17103601&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17103601)
=> SOLR-13289: Use the final collector's scoreMode

solr/core/src/java/org/apache/solr/util/SolrLogPostTool.java, solr/core/src/test/org/apache/solr/util/SolrLogPostToolTest.java
SolrLogPostTool is relatively brittle in how it indexes log records to Solr.  A single error from Solr causes the tool to crash.  Further, when user requests have duplicate or unnecessary parameters, the tool attempts to record all of these (even when the field used is singlevalued).
As a result, a single "oddball" request crashes the whole ingestion run.
This PR makes two related changes.  First, it changes SolrLogPostTool's batching code to log (but ultimately ignore) errors.  This allows an indexing run to survive malformed records or other indexing blips.  Second, it changes the record-parsing code to only record single values for single-valued log record fields.  This prevents a common cause of malformed records.   
Manual testing, in addition to a test case added to …
=> SOLR-14443: Make SolrLogPostTool resilient to odd requests

solr/solr-ref-guide/src/cluster-node-management.adoc, solr/solr-ref-guide/src/distributed-requests.adoc
Actual functionality implemented here: https://issues.apache.org/jira/browse/SOLR-13445
This PR just adds docs to it in two places: CLUSTERPROP documentation (for cluster defaults) and shard preferences (for per-request preferences).
=> SOLR-14511: Documented node.sysprop shard preference

solr/core/src/java/org/apache/solr/search/facet/UniqueBlockQueryAgg.java, solr/core/src/java/org/apache/solr/search/join/BlockJoinChildQParser.java, solr/core/src/java/org/apache/solr/search/join/BlockJoinParentQParser.java, solr/core/src/java/org/apache/solr/search/join/ChildFieldValueSourceParser.java, solr/core/src/test/org/apache/solr/search/join/another/BJQFilterAccessibleTest.java
https://issues.apache.org/jira/browse/SOLR-14494
In this PR I may have over-reached the refactorings beyond the scope a bit; it could be scaled back.  I didn't get why the cache interaction was as complex as it was so I simplified it but I may be wrong on this.
CC @mkhludnev
=> SOLR-14494: Refactor BlockJoin to not use Filter

solr/core/src/java/org/apache/solr/core/CachingDirectoryFactory.java, solr/core/src/java/org/apache/solr/core/CoreContainer.java, solr/core/src/java/org/apache/solr/core/CoreDescriptor.java, solr/core/src/java/org/apache/solr/core/CorePropertiesLocator.java, solr/core/src/java/org/apache/solr/core/DirectoryFactory.java, solr/core/src/java/org/apache/solr/core/NodeConfig.java, solr/core/src/java/org/apache/solr/core/SolrCore.java, solr/core/src/java/org/apache/solr/handler/admin/CoreAdminOperation.java, solr/core/src/test/org/apache/solr/core/TestCoreDiscovery.java
Fixes relative path ambiguities when the current working directory is atypical.
I discovered this problem when running Solr standalone from IntelliJ using a CWD that was maybe slightly unexpected. Some relative paths like the core instance dir were getting resolved relative to the CWD instead of the solr home or core root dir.  So I think it's preferable to make the major directories of Solr be absolute to avoid this problem.  Not worth a CHANGES.txt entry, I think.
BTW I *thought* maybe this might be related to https://issues.apache.org/jira/browse/SOLR-7323 because I was trying to reproduce it but no it's not.
=> SOLR: Use absolute paths for server paths.

lucene/core/src/java/org/apache/lucene/search/FuzzyQuery.java, lucene/core/src/test/org/apache/lucene/search/TestFuzzyQuery.java
when prefix length == search term length 
Co-Authored-By: markharwood <markharwood@gmail.com>
=> LUCENE-9365 FuzzyQuery false negative

solr/core/src/test/org/apache/solr/cloud/MultiThreadedOCPTest.java
Make MultiThreadedOCPTest.testFillWorkQueue() less vulnerable to timing issues when test or overseer code are being slowed down by external factors (load, GC etc).
A combination of verifying preconditions (to fail with a meaningful messages helping pinpoint issues for future test hardening), longer task execution time (that **does not delay** total test runtime) and do light synchronization between test steps and Overseeer processing progress. 
This _is_ a test.
=> SOLR-14524: Harden MultiThreadedOCPTest testFillWorkQueue()

lucene/CHANGES.txt, lucene/queries/src/java/org/apache/lucene/queries/function/FunctionScoreQuery.java, lucene/queries/src/test/org/apache/lucene/queries/function/TestFunctionScoreQuery.java
FunctionScoreQuery can't really use WAND algorithm even if TOP_DOCS score mode is requested. This commit makes the inner weight created use COMPLETE in this case.
=> LUCENE-9393: FunctionScoreQuery turns TOP_DOCS to COMPLETE in inner weights

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/search/ExtendedDismaxQParser.java, solr/core/src/test/org/apache/solr/search/TestExtendedDismaxParser.java
The RuntimeException that the DynamicField parser throws is never caught. In at least one case this results in a 500 error being thrown.
Replaced the RuntimeException with a SOLRException with an error code set to 400
Added TestExtendedDismaxParser.testInvalidDynamicField which covers DynamicField for an invalid input that can cause this bug
=> SOLR-13203: Added 400 status code to exception in DynamicField

solr/solrj/src/java/org/apache/solr/common/cloud/ZkStateReader.java, solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudHttp2SolrClientTest.java, solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudSolrClientTest.java, solr/solrj/src/test/org/apache/solr/client/solrj/impl/TestCloudSolrClientConnections.java
Fix test failures in CloudHttp2SolrClientTest CloudSolrClientTest TestCloudSolrClientConnections due to previous SOLR-12823 commit.
ZkStateReader returns a specific SolrException when expected nodes in the cluster created during cluster initialization do not exist.
Fixes the tests mentioned above.
=> SOLR-12823: fix test failures

lucene/core/src/test/org/apache/lucene/index/TestAllFilesDetectBitFlips.java
Opening a reader and then calling checkIntegrity must throw a `CorruptIndexException` or an `IndexFormatToo(Old|New)Exception`.
=> LUCENE-9356: Add a test that verifies that Lucene catches bit flips.

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriter.java
IndexWriter incorrectly calls closeMergeReaders twice when the
merged segment is 100% deleted ie. would produce a fully deleted
segment.
=> LUCENE-9405: Ensure IndexWriter only closes merge readers once.

solr/core/src/java/org/apache/solr/util/SolrLogPostTool.java, solr/core/src/test/org/apache/solr/util/SolrLogPostToolTest.java
Previously, SolrLogPostTool ignored all log-lines that didn't fall into a narrow handful of known "types".  This change adds a new "other" type, to hold all previously-ignored log records.  This allows all log records to be searched - not just the whitelisted cluster-traffic event types.(queries, commits, etc.) 
Straightforward implementation.
New test to SolrLogPostToolTest.  Manual testing.
=> SOLR-14558: Record all log lines in SolrLogPostTool

lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/java/org/apache/lucene/index/MergePolicy.java, lucene/core/src/test/org/apache/lucene/index/TestDemoParallelLeafReader.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriter.java, lucene/core/src/test/org/apache/lucene/index/TestMergePolicy.java
This change adds infrastructure to allow straight forward waiting
on one or more merges or an entire merge specification. This is
a basis for LUCENE-8962.
=> LUCENE-8962: Allow waiting for all merges in a merge spec

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/search/TermsQParserPlugin.java, solr/core/src/test/org/apache/solr/search/TestTermsQParserPlugin.java
It will currently throw a NPE, resulting in a server error.
=> SOLR-14577: Return BAD REQUEST when field is missing in terms QP

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/MultiCollector.java, lucene/core/src/test/org/apache/lucene/search/MultiCollectorTest.java
Here is an idea to make MultiCollector be able to handle `minCompetitiveScore`. Looking at this comment in the code:
```
// Ignore calls to setMinCompetitiveScore so that if we wrap two
// collectors and one of them wants to skip low-scoring hits, then
// the other collector still sees all hits. We could try to reconcile
// min scores and take the maximum min score across collectors, but
// this is very unlikely to be helpful in practice.
```
This implementation tries to make it so that all collectors can see all the hits and only allow skipping if all collectors set a min competitive score. The value passed to the inner scorer is the minimum among all collectors (instead of the maximum as the comment suggests).
=> LUCENE-9402: Let MultiCollector handle minCompetitiveScore

lucene/core/src/java/org/apache/lucene/index/DefaultIndexingChain.java, lucene/core/src/java/org/apache/lucene/index/DocConsumer.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThread.java, lucene/core/src/java/org/apache/lucene/index/TermVectorsConsumer.java, lucene/core/src/java/org/apache/lucene/index/TermsHash.java
DWPT.DocState had some history value but today in a little bit more
cleaned up DWPT and IndexingChain there is little to no value in having
this class. It also requires explicit cleanup which is not not necessary
anymore.
=> Replace DWPT.DocState with simple method parameters

solr/core/src/java/org/apache/solr/core/CoreContainer.java, solr/core/src/java/org/apache/solr/core/CoreDescriptor.java, solr/core/src/java/org/apache/solr/core/SolrPaths.java, solr/core/src/java/org/apache/solr/core/SolrResourceLoader.java, solr/core/src/java/org/apache/solr/filestore/DistribPackageStore.java, solr/core/src/test/org/apache/solr/core/DirectoryFactoryTest.java, solr/core/src/test/org/apache/solr/core/ResourceLoaderTest.java, solr/core/src/test/org/apache/solr/util/MockCoreContainer.java, solr/test-framework/src/java/org/apache/solr/BaseDistributedSearchTestCase.java, solr/test-framework/src/java/org/apache/solr/cloud/AbstractDistribZkTestBase.java, solr/test-framework/src/java/org/apache/solr/cloud/AbstractFullDistribZkTestBase.java
Continuation of #1546
Here, we avoid calling toAbsolutePath when not needed because we know it's already absolute.  Look carefully; there's a few other changes.
I liken this to pointless null checks in code when you know the thing isn't null.
=> Remove some needless toAbsolutePath calls

solr/contrib/dataimporthandler/src/test-files/log4j2.xml, solr/contrib/dataimporthandler/src/test-files/solr/collection1/README, solr/contrib/dataimporthandler/src/test-files/solr/configsets/dihconfigset/conf/README, solr/contrib/dataimporthandler/src/test-files/solr/configsets/dihconfigset/conf/schema.xml, solr/contrib/dataimporthandler/src/test-files/solr/configsets/dihconfigset/conf/solrconfig.xml, solr/contrib/dataimporthandler/src/test-files/solr/solr.xml, solr/contrib/dataimporthandler/src/test/org/apache/solr/handler/dataimport/TestZKPropertiesWriter.java
Fix TestZKPropertiesWriter that relied on legacy features of the SolrCloud cluster to work. These features were removed.
Start a MiniSolrCloudCluster (implies config set and other test resources config) and have the test use the core of a created collection.
Test fix.
=> SOLR-12823: fix TestZKPropertiesWriter

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/search/MaxScoreCollector.java, solr/core/src/test/org/apache/solr/search/MaxScoreCollectorTest.java, solr/core/src/test/org/apache/solr/search/SolrIndexSearcherTest.java
MaxScoreCollector now sets the minCompetitiveScore to the number of the current highest score, which allow MultiCollector to skip docs if the main query collector can.
=> SOLR-14554: Let Solr use WAND algorithm when scores are requested

solr/CHANGES.txt
Add a "Bug Fixes" section in the Solr 9.0.0 section in CHANGES.txt and move the fix to SOLR-14546 into it.
Text edit.
=> SOLR-14546: add a Bug Fixes section for Solr 9.0.0 in CHANGES.txt

solr/core/src/java/org/apache/solr/core/CoreContainer.java, solr/core/src/java/org/apache/solr/core/SolrPaths.java, solr/core/src/java/org/apache/solr/handler/CatStream.java, solr/core/src/java/org/apache/solr/servlet/SolrDispatchFilter.java, solr/solrj/src/test/org/apache/solr/client/solrj/io/stream/StreamExpressionTest.java
Convert String and File paths to Path API.
CoreContainer seems to me the proper place for the node to expose key directories at a node level.  It's already doing this.  It looked a bit clumsy to me to have the String constant and extra methods elsewhere for userfiles.  And I'd rather not see SolrDispatchFilter touched whatsoever for this feature, even if it was one line.
Once I moved that, and declared as type Path, I couldn't un-see all the code that did heavy back & forth conversion between String paths and File paths.  Not only is String terrible because it's untyped, but Path is the modern replacement, not File.  I wish we could do forbiddenAPI on File but there's lots of old code.  This userfiles code was only added last year though.
I experimented with using Files.walkTree in …
=> SOLR Move "userfiles" stuff from SolrPaths to CoreContainer.

solr/core/src/java/org/apache/solr/core/SolrPaths.java, solr/core/src/java/org/apache/solr/handler/ReplicationHandler.java, solr/core/src/java/org/apache/solr/handler/SnapShooter.java, solr/core/src/java/org/apache/solr/handler/admin/MergeIndexesOp.java, solr/core/src/test/org/apache/solr/cloud/BasicDistributedZk2Test.java, solr/core/src/test/org/apache/solr/cloud/api/collections/AbstractCloudBackupRestoreTestCase.java, solr/core/src/test/org/apache/solr/core/snapshots/TestSolrCloudSnapshots.java, solr/core/src/test/org/apache/solr/core/snapshots/TestSolrCoreSnapshots.java, solr/core/src/test/org/apache/solr/handler/TestCoreBackup.java, solr/core/src/test/org/apache/solr/handler/TestReplicationHandler.java, solr/core/src/test/org/apache/solr/handler/TestRestoreCore.java, solr/core/src/test/org/apache/solr/handler/V2ApiIntegrationTest.java, solr/core/src/test/org/apache/solr/handler/admin/CoreMergeIndexesAdminHandlerTest.java, solr/solr-ref-guide/src/index-replication.adoc, solr/solrj/src/test/org/apache/solr/client/solrj/MergeIndexesExampleTestBase.java, solr/test-framework/src/java/org/apache/solr/cloud/MiniSolrCloudCluster.java
Now validates path params for backup, restore, snapshot, mergeindexes
Add template to solr.in scripts
Also tested on Windows paths
Added RefGuide documentation to some params
=> SOLR-14561 Followup - validate params for more core operations 

lucene/queries/src/java/org/apache/lucene/queries/intervals/OrderedIntervalsSource.java, lucene/queries/src/test/org/apache/lucene/queries/intervals/TestIntervalQuery.java, lucene/queries/src/test/org/apache/lucene/queries/intervals/TestIntervals.java
Given the input text 'A B A C', an ordered interval 'A B C' will currently return an incorrect
internal [2, 3] in addition to the correct [0, 3] interval.  This is due to a bug in the ORDERED
algorithm, where we assume that after the first interval is returned, the sub-intervals are 
always in-order.  This assumption only holds during minimization, as minimizing an interval
may move the earlier terms beyond the trailing terms.
For example, after the initial [0, 3] interval is found above, the algorithm will attempt to
minimize it by advancing A to [2,2].  Because this is still before C at [3,3], but after B at 
[1,1], we then try advancing B, leaving it at [Inf,Inf].  Minimization has failed, so we return
out original interval of [0,3].  However, when we come to retrieve the next …
=> LUCENE-9418: Fix ordered intervals over interleaved terms

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/highlight/UnifiedSolrHighlighter.java, solr/core/src/test/org/apache/solr/highlight/TestUnifiedSolrHighlighter.java, solr/solr-ref-guide/src/highlighting.adoc, solr/solr-ref-guide/src/solr-upgrade-notes.adoc
Fragments size like <= Solr 8.4 and addresses a significant performance regression
=> SOLR-14628: hl.fragsizeIsMinimum now defaults to true

solr/solrj/src/test/org/apache/solr/client/solrj/cloud/autoscaling/TestPolicy.java
adjust test so less sessions are used even if test runs slowly. fix synchronization issue.
=> SOLR-14462: test fix

lucene/core/src/java/org/apache/lucene/search/RegexpQuery.java, lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java, lucene/core/src/test/org/apache/lucene/search/TestRegexpQuery.java, lucene/core/src/test/org/apache/lucene/util/automaton/TestRegExp.java
Relates to Jira issue [9386](https://issues.apache.org/jira/projects/LUCENE/issues/LUCENE-9386)
Added a new CASE_INSENSITIVE option to the existing flags.
The RegExp class is a little strange because instances represent either the parser or the parsed objects it nests in a tree. The `flags` field is only relevant to the root parser and was left blank in all parsed nodes. This PR's changes require that the flags int is propagated to all nodes so that they can see if it includes the case insensitive option (all other bits in the flag represent parsing options so there was no need to propagate before).
=> RegExp - add case insensitive matching option

lucene/core/src/java/org/apache/lucene/store/NIOFSDirectory.java, lucene/core/src/test/org/apache/lucene/store/TestNIOFSDirectory.java
If we fail to get the size of a file in the constructor of NIOFSIndexInput, then we will leak a FileChannel opened in NIOFSDirectory#openInput.
=> LUCENE-9423: Handle exception in NIOFSDirectory#openInput

solr/core/src/java/org/apache/solr/schema/DatePointField.java, solr/core/src/java/org/apache/solr/schema/PointField.java, solr/core/src/java/org/apache/solr/schema/TrieDateField.java, solr/core/src/java/org/apache/solr/schema/TrieDoubleField.java, solr/core/src/java/org/apache/solr/schema/TrieField.java, solr/core/src/java/org/apache/solr/schema/TrieFloatField.java, solr/core/src/java/org/apache/solr/schema/TrieIntField.java, solr/core/src/java/org/apache/solr/schema/TrieLongField.java, solr/core/src/test/org/apache/solr/schema/WrappedTrieIntField.java
cc: @cpoerschke I can't tag you as a reviewer for some reason, but this is based on your patch and I added two more changes - fixed spelling and removed back link from DatePoint to TrieDate.
=> SOLR-11390 Trie* field javadocs to @see *Point

solr/core/src/test/org/apache/solr/util/TestCircuitBreaker.java
1. Add specific checks for exception message expectation.
2. Ensure that a non triggering value is returned when the fake circuit breaker should not be tripping.
Also adds temporary logging for debugging, to be removed.
=> Harden TestBuildingUpMemoryPressure

solr/core/src/java/org/apache/solr/core/backup/repository/HdfsBackupRepository.java
FileSystem.get can cause FileSystem closed exceptions, especially with S3. Using FileSystem.newInstance should help that case.
=> Use FileSystem.newInstance instead of get in HDFSBackupRepository

solr/solr-ref-guide/src/replica-management.adoc, solr/solrj/src/resources/apispec/collections.collection.Commands.json
- document additional existing parameters, second pass fixing spelling and other details.
(cherry picked from commit b00d747eb6a94ab5775258b032e621f998ec44ba)
SOLR-13169 Improve docs for MOVEREPLICA - better parity with ref guide for v2 api descriptions
(cherry picked from commit 396490b65ca1af6ff1f1157a9896c9528c234eea)
=> SOLR-13169 Improve docs for MOVEREPLICA

solr/solr-ref-guide/src/replica-management.adoc, solr/solrj/src/resources/apispec/collections.collection.Commands.json
- document additional existing parameters, second pass fixing spelling and other details.
(cherry picked from commit b00d747eb6a94ab5775258b032e621f998ec44ba)
SOLR-13169 Improve docs for MOVEREPLICA - better parity with ref guide for v2 api descriptions
(cherry picked from commit 396490b65ca1af6ff1f1157a9896c9528c234eea)
=> SOLR-13169 Improve docs for MOVEREPLICA 

gradle/documentation/documentation.gradle, gradle/documentation/render-javadoc.gradle
JIRA: https://issues.apache.org/jira/browse/LUCENE-9321
This includes two changes in documentation task.
1. Fix Javadoc offline link base url to make snapshot build pass `checkBrokenLinks`.
2. Explicitly disable cross-project link for `:solr:test-framework`, otherwise broken links are generated due to split package issue.
See: https://github.com/apache/lucene-solr/blob/master/solr/test-framework/build.xml#L59
By applying those changes, `./gradlew :solr:checkBrokenLinks` succeeds on snapshot build.
=> LUCENE-9321: Fix Javadoc offline link base url for snapshot build

solr/solr-ref-guide/README.adoc
Documenting need to have ascii doctor version up to date.
=> Found that asciidoctor 1.5.6.2 cause build-site to fail on long anchors

lucene/CHANGES.txt, lucene/highlighter/src/java/org/apache/lucene/search/uhighlight/UnifiedHighlighter.java, lucene/highlighter/src/test/org/apache/lucene/search/uhighlight/TestUnifiedHighlighterTermVec.java
A regression from 8.6.  Don't close the underlying IndexReader.
https://issues.apache.org/jira/browse/LUCENE-9443
Instead of reverting the commit, there's something to be said for closing the wrapped reader since, after all, it's something you're supposed to close.  Since this is a wrapped reader created by the UH, it's easy to make its doClose do nothing.  Furthermore I tweaked a test that would fail prior to this change.  I checked precommit to ensure there is still no warning.
=> LUCENE-9443: UnifiedHighlighter shouldn't close reader

solr/solr-ref-guide/README.adoc
* Found that asciidoctor 1.5.6.2 cause build-site to fail on long anchors, 2.0.10 definitely works.
* Clarity on when an upgrade is required, also fix obsolete wording from when PDFs were generated.
=> Found that asciidoctor 1.5.6.2 cause build-site to fail on long anchors (#1700)

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/ConstantScoreQuery.java, lucene/core/src/java/org/apache/lucene/search/FieldComparator.java, lucene/core/src/java/org/apache/lucene/search/FieldValueHitQueue.java, lucene/core/src/java/org/apache/lucene/search/FilteringFieldComparator.java, lucene/core/src/java/org/apache/lucene/search/FilteringLeafFieldComparator.java, lucene/core/src/java/org/apache/lucene/search/FilteringNumericComparator.java, lucene/core/src/java/org/apache/lucene/search/FilteringNumericLeafComparator.java, lucene/core/src/java/org/apache/lucene/search/LeafCollector.java, lucene/core/src/java/org/apache/lucene/search/MatchAllDocsQuery.java, lucene/core/src/java/org/apache/lucene/search/ScoreMode.java, lucene/core/src/java/org/apache/lucene/search/SortField.java, lucene/core/src/java/org/apache/lucene/search/TopFieldCollector.java, lucene/core/src/java/org/apache/lucene/search/Weight.java, lucene/core/src/test/org/apache/lucene/search/TestFieldSortOptimizationSkipping.java, lucene/test-framework/src/java/org/apache/lucene/search/AssertingLeafCollector.java
Backport for: LUCENE-9280: Collectors to skip noncompetitive documents (#1351)
Similar how scorers can update their iterators to skip non-competitive
documents, collectors and comparators should also provide and update
iterators that allow them to skip non-competive documents.
To enable sort optimization for numeric sort fields,
the following needs to be done:
1) the field should be indexed with both doc_values and points, that
must have the same field name and same data
2) SortField#setCanSkipNonCompetitiveDocs must be set
3) totalHitsThreshold should not be set to max value.
=> LUCENE-9384: Backport for field sort optimization

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java, lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java
Previously, we only removed 'match all' FILTER clauses if there was at least one
MUST clause. Now they're also removed if there is another distinct FILTER clause.
This lets boolean queries like `#field:value #*:*` be written to `#field:value`.
=> LUCENE-9446: In boolean rewrite, remove MatchAllDocsQuery filter clauses

dev-tools/maven/pom.xml.template
Fix for [SOLR-13499](https://issues.apache.org/jira/browse/SOLR-13499).
There are many Java libraries licensed under "Apache License, Version 2.0" that do not use its official spelling.
This causes issues like https://issues.apache.org/jira/browse/MPIR-382: with every library defining its own spelling, it's difficult in large projects to have a clear view of all licenses in use.
This PR changes the license spelling to the official one, as advised by Maven developers.
=> SOLR-13499: Fix "Apache License, Version 2.0" spelling in pom.xml.template

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/update/SolrIndexConfig.java, solr/core/src/test-files/solr/collection1/conf/solrconfig.snippet.randomindexconfig.xml, solr/core/src/test/org/apache/solr/update/SolrIndexConfigTest.java
LUCENE-8962 added the ability to merge segments synchronously on commit. This isn't done by default and the default MergePolicy won't do it, but custom merge policies can take advantage of this. Solr allows plugging in custom merge policies, so if someone wants to make use of this feature they could, however, they need to set IndexWriterConfig.maxCommitMergeWaitSeconds to something greater than 0.
Since this is an expert feature, I plan to document it only in javadoc and not the ref guide.
=> SOLR-14582: Expose IWC.setMaxCommitMergeWaitMillis in Solr's index config

solr/core/src/test/org/apache/solr/core/TestConfig.java
Seems this is likely just an oversight in testing, not a real problem, so Adding AwaitsFix to allow builds to stop failing.
=> SOLR-14582 - Broken test needs fix

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/cloud/autoscaling/sim/SimNodeStateProvider.java, solr/core/src/java/org/apache/solr/cloud/autoscaling/sim/SimScenario.java, solr/solr-ref-guide/src/solr-upgrade-notes.adoc, solr/solrj/src/java/org/apache/solr/client/solrj/cloud/autoscaling/Clause.java
https://issues.apache.org/jira/browse/SOLR-14706
This is to introduce backwards compatibility for the default autoscaling policy that was removed in 8.6.1 (and 8.7).
The upgrade notes now include the steps to remove the default autoscaling policy via the autoscaling API.
I have tested the following upgrade patterns, and am happy with the results. I'll do more tests if y'all think it is necessary.
8.6.0 -> 8.6.1 RC1 (fail)
8.6.0 -> this patch (success)
8.6.0 -> 8.6.1 RCI -> this patch (success)
I will also be porting this with a few documentation tweaks to 8x
=> SOLR-14706: Fix support for default autoscaling policy

lucene/core/src/java/org/apache/lucene/index/DocumentsWriterFlushControl.java
checkoutAndBlock is not synchronized, but has a non-atomic write to numPending. Meanwhile, all of the other writes to numPending are in sync methods.
In this case it turns out to be ok because all of the code paths calling this method are already sync:
`synchronized doAfterDocument -> checkout -> checkoutAndBlock`
`checkoutLargestNonPendingWriter -> synchronized(this) -> checkout -> checkoutAndBlock`
If we make synchronized checkoutAndBlock that protects us against future changes, shouldn't cause any performance impact since the code paths will already be going through a sync block, and will make an IntelliJ warning go away.
Found via IntelliJ warnings. 
https://issues.apache.org/jira/browse/LUCENE-9453
=> LUCENE-9453 Add sync around volatile write

dev-tools/scripts/smokeTestRelease.py
while verifying the 8.6.1 release with the latest python(3.8.5), observed
one SyntaxWarning.
https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/
=> Fix syntax warning in smokeTestRelease.py

solr/CHANGES.txt, solr/solrj/src/java/org/apache/solr/common/cloud/SolrZkClient.java
See https://issues.apache.org/jira/browse/SOLR-14751
Solution is to treat `NoNodeException` not as an unrecoverable exception, but as expected for older ZK versions and return empty string.
A workaround for 8.6.x is to do a
bin/solr zkroot /zookeeper/config
Then the Admin UI in 8.6 will start working with old ZK.
=> SOLR-14751: Zookeeper Admin screen not working for old ZK versions

solr/CHANGES.txt, solr/contrib/dataimporthandler/src/java/org/apache/solr/handler/dataimport/DataSource.java, solr/contrib/dataimporthandler/src/java/org/apache/solr/handler/dataimport/DocBuilder.java, solr/contrib/dataimporthandler/src/java/org/apache/solr/handler/dataimport/EntityProcessor.java
Prior to this commit, the wrapup logic at the end of
DocBuilder.execute() closed out a series of DIH objects, but did so
in a way that an exception closing any of them resulted in the remainder
staying open.  This is especially problematic since Writer.close()
throws exceptions that DIH uses to determine the success/failure of the
run.
In practice this caused network errors sending DIH data to other Solr
nodes to result in leaked JDBC connections.
This PR changes DocBuilder's termination logic to handle exceptions
more gracefully, ensuring that errors closing a DIHWriter (for example)
don't prevent the closure of entity-processor and DataSource objects.
None
=> SOLR-14677: Always close DIH EntityProcessor/DataSource

lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java, lucene/core/src/test/org/apache/lucene/index/TestDocumentsWriterPerThreadPool.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterWithThreads.java
The DWPTPool should not release new DPWTs after it's closed. Yet, if the pool
is in a state where it's preventing new writers from being created in order to swap
the delete queue it might get closed and in that case we miss to throw an AlreadyClosedException
and release a new writer which violates the condition that the pool is empty after it's closed
and all remaining DWPTs have been aborted.
=> Ensure DWPTPool never release any new DWPT after it's closed

solr/core/src/java/org/apache/solr/core/ConfigSetService.java, solr/core/src/java/org/apache/solr/core/SolrCore.java, solr/core/src/java/org/apache/solr/core/SolrResourceLoader.java, solr/core/src/java/org/apache/solr/schema/IndexSchema.java, solr/core/src/test/org/apache/solr/pkg/TestPackages.java
I've isolated the changes that caused schema `TestBulkSchemaConcurrent` tests to fail
This bug was introduced by [SOLR-14151](https://issues.apache.org/jira/browse/SOLR-14680) .
So, in this PR, I have disabled those tests and reopened the ticket. I'll need to do further investigation to see why exactly is it failing. In the worst case, this PR can be merged right away to unblock others and we can add a real fix later.
Though the test that is failing is `TestBulkSchemaConcurrent`, the reason for the failure is that that tests do a lot of core reloads and the bug is pertaining to core reload. No other test stresses core reload so much
=> SOLR-14750: TestBulkSchemaConcurrent passes but schema plugins fail

lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterExceptions.java
Today we might rollback IW more than once if we hit an exception during
the rollback code when we shutdown. This change moves the rollback code outside
of the try block to ensure we always roll back but never roll back twice.
=> Ensure we only rollback IW once

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/core/SolrConfig.java, solr/core/src/java/org/apache/solr/util/circuitbreaker/CPUCircuitBreaker.java, solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreaker.java, solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreakerManager.java, solr/core/src/java/org/apache/solr/util/circuitbreaker/MemoryCircuitBreaker.java, solr/core/src/resources/EditableSolrConfigAttributes.json, solr/core/src/test-files/solr/collection1/conf/solrconfig-memory-circuitbreaker.xml, solr/core/src/test/org/apache/solr/core/SolrCoreTest.java, solr/core/src/test/org/apache/solr/util/TestCircuitBreaker.java, solr/server/solr/configsets/_default/conf/solrconfig.xml, solr/solr-ref-guide/src/circuit-breakers.adoc
This commit introduces CPU based circuit breaker. This circuit breaker
tracks the average CPU load per minute and triggers if the value exceeds
a configurable value.
This commit also adds a specific control flag for Memory Circuit Breaker
to allow enabling/disabling the same.
=> SOLR-14615: Implement CPU Utilization Based Circuit Breaker

lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterDelete.java
We need to disable merges while we wait for running merges since
IW calls timed wait on it's lock that releases the monitor for the time
being which allows new merges to be registered unless we disable them.
=> LUCENE-9473: Ensure merges are stopped during abort merges

lucene/core/src/java/org/apache/lucene/index/SegmentInfos.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterExceptions.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterOnVMError.java, lucene/test-framework/src/java/org/apache/lucene/store/MockDirectoryWrapper.java
If we fail to rollback an already renamed pending segments file during
commit due to a failure in directory syncing we might not fully roll back
to a proper state if we hit a failure during rollback which leaves the index
in a broken state. This is a best effort approach to remove the renamed file
in the case of a failure during sync.
=> LUCENE-9477: Don't leave potentially broken segments file behind

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterDeleteQueue.java, lucene/core/src/test/org/apache/lucene/index/TestDocumentsWriterDeleteQueue.java
In LUCENE-9304 we introduced some fixes that unfortunately hold on to the previous
DWPTDeleteQueue which is essentially leaking IW memory and cause applications to fail.
This fixes the memory leak and adds a test to ensure its not leaking memory.
=> LUCENE-9478: Prevent DWPTDeleteQueue from referencing itself and leaking memory

dev-tools/scripts/buildAndPushRelease.py
This would have saved me many hours of waiting for tests to finish in order to realize that my java-version is not working with jlint as well as an existing RAT issue on the release branch. I think there is no harm in running tests last.
=> Run tests last to fail fast on missing license and doc issues

dev-tools/scripts/smokeTestRelease.py
Simple port check before tests start
See https://issues.apache.org/jira/browse/LUCENE-9485
=> LUCENE-9485: Check early if Solr port 8983 is available

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/core/CoreContainer.java, solr/core/src/java/org/apache/solr/handler/admin/HealthCheckHandler.java, solr/core/src/java/org/apache/solr/handler/admin/InfoHandler.java, solr/core/src/resources/ImplicitPlugins.json, solr/core/src/test/org/apache/solr/core/SolrCoreTest.java, solr/solr-ref-guide/src/implicit-requesthandlers.adoc, solr/solrj/src/resources/apispec/node.Info.json
This allows users to plug-in different implementations of the handler (they must extend HealthCheckHandler)
This PR also removes the HealthCheckHandler from the implicit SolrCore plugins
=> SOLR-14774: Create HealthCheckHandler in CoreContainer

solr/core/src/test/org/apache/solr/update/DirectUpdateHandlerTest.java
The following output occurred BEFORE I modified the test:
````
6322 INFO  (TEST-DirectUpdateHandlerTest.testPrepareCommit-seed#[BECB842E499EAF75]) [     ] o.a.s.u.DirectUpdateHandlerTest FILES before prepareCommit=[_0.cfe, _0.cfs, _0.si, _1.fdm, _1.fdt, _1_Lucene85FieldsIndex-doc_ids_2.tmp, _1_Lucene85FieldsIndexfile_pointers_3.tmp, segments_3]
6371 INFO  (TEST-DirectUpdateHandlerTest.testPrepareCommit-seed#[BECB842E499EAF75]) [     ] o.a.s.u.DirectUpdateHandlerTest FILES after prepareCommit=[_0.cfe, _0.cfs, _0.si, _1.cfe, _1.cfs, _1.si, pending_segments_4, segments_3]
````
=> LUCENE-9456: fix DirectUpdateHandlerTest#testPrepareCommit

solr/solr-ref-guide/src/collection-specific-tools.adoc, solr/solr-ref-guide/src/documents-fields-and-schema-design.adoc, solr/solr-ref-guide/src/implicit-requesthandlers.adoc, solr/solr-ref-guide/src/luke-request-handler.adoc, solr/solr-ref-guide/src/schema-browser-screen.adoc
To replace the old https://cwiki.apache.org/confluence/display/solr/LukeRequestHandler page, and eventually provide a link to the Luke application's getting started page!
=> SOLR-14773 Add LukeRequestHandler to the Solr Ref Guide

lucene/core/src/java/org/apache/lucene/codecs/compressing/CompressingStoredFieldsReader.java
These buffers can use lots of memory when the number of segments,
threads or both is high.
=> LUCENE-9483: Disable per-thread caching of buffers for decompression of stored fields.

lucene/CHANGES.txt, lucene/test-framework/src/java/org/apache/lucene/codecs/asserting/AssertingDocValuesFormat.java, lucene/test-framework/src/java/org/apache/lucene/index/AssertingLeafReader.java
Some queries use DocValues.unwrapSingleton to execute different logic for
single-valued doc values. When tests use AssertingCodec or AssertingLeafReader,
unwrapSingleton will never unwrap the doc values, as they don't have the
expected class. So some queries have code paths that are never exercised with
these asserting wrappers.
This change makes sure to preserve the expected classes when creating asserting
doc values.
=> Improve how Asserting* classes handle singleton doc values.

lucene/core/src/java/org/apache/lucene/codecs/lucene87/BugfixDeflater_JDK8252739.java, lucene/core/src/java/org/apache/lucene/codecs/lucene87/DeflateWithPresetDictCompressionMode.java, lucene/core/src/test/org/apache/lucene/codecs/lucene87/TestLucene87StoredFieldsFormatHighCompression.java
A factory method allows to return a different instance depending on Java version (for now everything after Java 11 is disallowed).
We can improve this when we exactly know which versions are affected. Once the bug is fixed and Lucene uses a later minimum version, we can easily remove the class.
TODO: We should add a forbiddenapis to disallow direct use of deflater by disallowing its constructor.
=> LUCENE-9500: Separate the Deflater hack from the Lucene code to a subclass of java.util.zip.Deflater

lucene/core/src/java/org/apache/lucene/index/SegmentInfos.java
`throw new CorruptIndexException("invalid deletion count: " + softDelCount + delCount + " vs maxDoc=" + info.maxDoc(), input);`
It needs to be changed to:
`throw new CorruptIndexException("invalid deletion count: " + (softDelCount + delCount) + " vs maxDoc=" + info.maxDoc(), input);`
The value of "softDelCount + delCount" must be calculated first.
=> LUCENE-9482: Fix deletion count error message

README.md, lucene/BUILD.md
Current lucene/BUILD.md is somehow mixed-up with information for Solr developers, this is wrong place for them. Solr related information/tips should be moved to the top-level README (or somewhere else).
Also the content could be elaborated for newdevs (required JDK version, and so on).
=> LUCENE-9509: Refine lucene/BUILD.md and top-level README (for newdevs)

lucene/CHANGES.txt, lucene/codecs/src/java/org/apache/lucene/codecs/simpletext/SimpleTextStoredFieldsWriter.java, lucene/core/src/java/org/apache/lucene/codecs/StoredFieldsWriter.java, lucene/core/src/java/org/apache/lucene/codecs/compressing/CompressingStoredFieldsWriter.java, lucene/core/src/java/org/apache/lucene/index/DefaultIndexingChain.java, lucene/core/src/java/org/apache/lucene/index/DocConsumer.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterFlushControl.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThread.java, lucene/core/src/java/org/apache/lucene/index/FreqProxTermsWriter.java, lucene/core/src/java/org/apache/lucene/index/PointValuesWriter.java, lucene/core/src/java/org/apache/lucene/index/SortingStoredFieldsConsumer.java, lucene/core/src/java/org/apache/lucene/index/SortingTermVectorsConsumer.java, lucene/core/src/java/org/apache/lucene/index/StoredFieldsConsumer.java, lucene/core/src/java/org/apache/lucene/index/TermVectorsConsumer.java, lucene/core/src/java/org/apache/lucene/index/TermsHash.java, lucene/core/src/test/org/apache/lucene/index/TestFlushByRamOrCountsPolicy.java, lucene/test-framework/src/java/org/apache/lucene/codecs/asserting/AssertingStoredFieldsFormat.java, lucene/test-framework/src/java/org/apache/lucene/codecs/cranky/CrankyStoredFieldsFormat.java
StoredFieldsWriter might consume some heap space memory that
can have a significant impact on decisions made in the IW if
writers should be stalled or DWPTs should be flushed if memory
settings are small in IWC and flushes are frequent. This change adds
RAM accounting to the StoredFieldsWriter since it's part of the
DWPT lifecycle and not just present during flush.
=> LUCENE-9511: Include StoredFieldsWriter in DWPT accounting

solr/core/src/test/org/apache/solr/core/DirectoryFactoriesTest.java
As part of https://issues.apache.org/jira/browse/LUCENE-8626 I noticed that we have both
* https://github.com/apache/lucene-solr/blob/releases/lucene-solr/8.6.1/solr/core/src/test/org/apache/solr/core/DirectoryFactoryTest.java and
* https://github.com/apache/lucene-solr/blob/releases/lucene-solr/8.6.1/solr/core/src/test/org/apache/solr/core/TestDirectoryFactory.java which is mildly confusing.
Something like "DirectoryFactoriesTest" more accurately describes what the "TestDirectoryFactory" test does.
=> Rename TestDirectoryFactory to DirectoryFactoriesTest

gradle/validation/forbidden-apis/defaults.all.txt, lucene/core/src/java/org/apache/lucene/codecs/lucene87/BugfixDeflater_JDK8252739.java, lucene/core/src/java/org/apache/lucene/codecs/lucene87/DeflateWithPresetDictCompressionMode.java
Bugfix for LUCENE-9517: Instead of subclassing Deflater like in LUCENE-9500, we just provide a method reference (using a functional interface), so code can call Deflater#setDictionary.
The issue was caused by a missing AccessController#setPrivileged() in JDK's code when Deflater was subclassed. This workaround does not subclass, so the missing doPrivileged is not needed.
This also adds the faulty methods to forbiddenapis.
=> LUCENE-9517: Don't subclass Deflater and instead create a patch for setDictionary() using a functional interface

solr/core/src/java/org/apache/solr/response/GeoJSONResponseWriter.java, solr/core/src/java/org/apache/solr/response/JSONResponseWriter.java, solr/core/src/java/org/apache/solr/response/JSONWriter.java, solr/core/src/java/org/apache/solr/response/PHPSerializedResponseWriter.java, solr/core/src/java/org/apache/solr/response/SchemaXmlWriter.java, solr/core/src/java/org/apache/solr/response/TabularResponseWriter.java, solr/core/src/java/org/apache/solr/response/TextResponseWriter.java, solr/core/src/java/org/apache/solr/response/XMLWriter.java, solr/solr-ref-guide/src/major-changes-in-solr-9.adoc
With BMW support, we added a new method to Text response writers to include in the response if the numFound is exact or not. This PR is to remove the previously existing and deprecated methods and makes the new method abstract to force it's implementation in subclasses. This is intended for master branch only.
=> SOLR-14510: Remove deprecations added with BlockMax WAND support

lucene/CHANGES.txt, lucene/sandbox/src/java/org/apache/lucene/search/IndexSortSortedNumericDocValuesRangeQuery.java, lucene/sandbox/src/test/org/apache/lucene/search/TestIndexSortSortedNumericDocValuesRangeQuery.java
Previously the DocIdSetIterator returned an old value for docID even after
advance returned NO_MORE_DOCS. This violates the DocIdSetIterator contract and
made it possible for the iterator's advance method to be called even after it
was already exhausted.
=> LUCENE-9501: Fix invariant violation in IndexSortSortedNumericDocValuesRangeQuery.

solr/core/src/test/org/apache/solr/cloud/hdfs/HdfsTestUtil.java
Workaround. This is test-change only, shouldn't affect anything else.
=> SOLR-14417: Gradle build sometimes fails RE BlockPoolSlice

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/ByteSliceWriter.java, lucene/core/src/java/org/apache/lucene/index/DefaultIndexingChain.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterFlushControl.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThread.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java, lucene/core/src/java/org/apache/lucene/index/FreqProxTermsWriter.java, lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/java/org/apache/lucene/index/SortingTermVectorsConsumer.java, lucene/core/src/java/org/apache/lucene/index/TermVectorsConsumer.java, lucene/core/src/java/org/apache/lucene/index/TermsHash.java, lucene/core/src/test/org/apache/lucene/index/TestDocumentsWriterPerThreadPool.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriter.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterConfig.java
This change removes the DWPT dependency from DefaultIndexingChain
and rather passes on the primitives needed for creating the chain.
=> LUCENE-9515: Detach DWPT from DefaultIndexingChain

solr/CHANGES.txt, solr/docker/build.gradle
This is so that the docker tests do not run by default on the Apache Jenkins test jobs.
=> SOLR-14789: Rename docker tests task, adding missing credit in CHANGES

lucene/core/src/java/org/apache/lucene/index/SortingStoredFieldsConsumer.java
With recent changes to stored fields that split blocks into several sub
blocks, the merge instance has become much slower at random access since
it would decompress all sub blocks when accessing a document. Since
stored fields likely get accessed in random order at flush time when
index sorting is enabled, it's better not to use the merge instance.
On a synthetic benchmark that has one stored field and one numeric
doc-value field that is used for sorting and fed with random values,
this made indexing more than 4x faster.
=> LUCENE-9510: Don't pull a merge instance when flushing stored fields out-of-order.

solr/solr-ref-guide/src/field-types-included-with-solr.adoc, solr/solr-ref-guide/src/other-parsers.adoc
The RefGuide page was missing some types and had too many Deprecated types in the same table as active types, which made it a bit hard to scan.
- Went through the 8.6 javadoc and included missing field types in the Ref Guide page
- Added small placeholder description in other page where the types had no mention at all 
- Moved Deprecated types into their own table
- Added some cross-references, for improved linking and understanding
=> SOLR-14862: Update RefGuide page for support fied types

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/SortingStoredFieldsConsumer.java, lucene/core/src/java/org/apache/lucene/index/SortingTermVectorsConsumer.java
When index sorting is enabled, stored fields and term vectors can't be
written on the fly like in the normal case, so they are written into
temporary files that then get resorted. For these temporary files,
disabling compression speeds up indexing significantly.
On a synthetic test that indexes stored fields and a doc value field
populated with random values that is used for index sorting, this
resulted in a 3x indexing speedup.
=> LUCENE-9510: Don't compress temporary stored fields and term vectors when index sorting is enabled.

lucene/core/src/java/org/apache/lucene/codecs/lucene87/BugfixDeflater_JDK8252739.java, lucene/core/src/java/org/apache/lucene/codecs/lucene87/DeflateWithPresetDictCompressionMode.java, lucene/core/src/java/org/apache/lucene/codecs/lucene87/LZ4WithPresetDictCompressionMode.java, lucene/core/src/java/org/apache/lucene/codecs/lucene87/Lucene87StoredFieldsFormat.java, lucene/test-framework/src/java/org/apache/lucene/codecs/compressing/DeflateWithPresetCompressingCodec.java, lucene/test-framework/src/java/org/apache/lucene/codecs/compressing/LZ4WithPresetCompressingCodec.java
Instead of configuring a dictionary size and a block size, the format
now tries to have 10 sub blocks per bigger block, and adapts the size of
the dictionary and of the sub blocks to this overall block size.
=> LUCENE-9525: Better handle small documents with Lucene87StoredFieldsFormat.

lucene/core/src/java/org/apache/lucene/codecs/compressing/CompressingStoredFieldsReader.java, lucene/core/src/java/org/apache/lucene/codecs/lucene87/Lucene87StoredFieldsFormat.java
The increase of the maximum number of chunks per doc done in previous
issues was mostly random. I'd like to provide users with a similar
trade-off with what the old versions of BEST_SPEED and BEST_COMPRESSION
used to do. So since BEST_SPEED used to compress at most 128 docs at
once, I think we should roughly make it 128*10 now since there are 10
sub blocks. I made it 1024 to account for the fact that there is a preset
dict as well that need decompressing. And similarly BEST_COMPRESSION used
to allow 4x more docs than BEST_SPEED, so I made it 4096.
With such larger numbers of docs per chunk, the decoding of metadata
became a bottleneck for stored field access so I made it a bit faster by
doing bulk decoding of the packed longs.
=> Further tune Lucene87StoredFieldsFormat for small documents.

lucene/core/src/java/org/apache/lucene/codecs/compressing/CompressingStoredFieldsReader.java, lucene/core/src/java/org/apache/lucene/codecs/compressing/CompressingStoredFieldsWriter.java, lucene/core/src/java/org/apache/lucene/codecs/compressing/CompressingTermVectorsReader.java, lucene/core/src/java/org/apache/lucene/codecs/compressing/CompressingTermVectorsWriter.java, lucene/test-framework/src/test/org/apache/lucene/codecs/compressing/TestCompressingStoredFieldsFormat.java, lucene/test-framework/src/test/org/apache/lucene/codecs/compressing/TestCompressingTermVectorsFormat.java
The problem of tracking dirtiness via numbers of chunks is that larger
chunks make stored fields readers more likely to be considered dirty, so
I'm trying to work around it by tracking numbers of docs instead.
=> LUCENE-9529: Track dirtiness of stored fields via a number of docs, not chunks.

lucene/core/src/java/org/apache/lucene/index/DocumentsWriterFlushControl.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThread.java
Consumers of the used RAM of a DWPT should use it's committed bytesUsed
value that's threadsafe.
=> LUCENE-9534: Ensure DWPT#ramBytesUsed is only called unter lock

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/admin/SystemInfoHandler.java
Even if coreRootDirectory was set in solr.xml, external applications could not access it through the API. It was not exposed. This means it is not possible to run a command such as *bin/solr create_core -c test* as the code that pre-populates the core directory is doing it in the wrong place (if at all).
Expose the property if it is defined and is different from solr_home
=> SOLR-14878: Expose solr.xml's coreRootDirectory property via the System Settings API

solr/CHANGES.txt, solr/core/src/resources/ImplicitPlugins.json, solr/core/src/test-files/solr/collection1/conf/solrconfig-minhash.xml, solr/core/src/test-files/solr/collection1/conf/solrconfig-plugcollector.xml, solr/core/src/test-files/solr/collection1/conf/solrconfig.xml, solr/core/src/test/org/apache/solr/handler/component/DistributedTermsComponentTest.java, solr/core/src/test/org/apache/solr/handler/component/TermsComponentTest.java, solr/core/src/test/org/apache/solr/update/TestNestedUpdateProcessor.java, solr/server/solr/configsets/_default/conf/solrconfig.xml, solr/server/solr/configsets/sample_techproducts_configs/conf/solrconfig.xml, solr/solr-ref-guide/src/requesthandlers-and-searchcomponents-in-solrconfig.adoc, solr/solr-ref-guide/src/the-terms-component.adoc
We moved Terms Components and Terms Request Handler into default definition, but the request handler did not define any defaults. Therefore, we still had an overriding definition hanging around in solrconfig.xml, confusing things. Additionally, documentation was out of date too.
1. Updated default definition for /terms request handler to match what solrconfig.xml had (terms=true to actually make that handler useful and distrib=false)
2. Removed definition from default configsets
3. Cleaned up tests that no longer needed to enable the component every time
4. Updated documentation to reflect the implicit aspects and to give an example of using it with other handlers
1. No new tests, but updated the existing ones to rely on updated definition and not to declare it explicitly.
Please review …
=> SOLR-9607: Finalize move of Terms component and request handler into the implicit definitions

solr/core/src/test/org/apache/solr/cloud/TestConfigSetsAPI.java, solr/test-framework/src/java/org/apache/solr/cloud/MiniSolrCloudCluster.java
This PR includes some improvements to TestConfigSetsAPI:
* Extend `SolrCloudTestCase`: This is mainly because before, the test was creating clusters for every unit test vs. a single one for the suite
* Use Mock authentication: This test is not to test the authentication framework, The `ConfigSetHandler` only needs to know if an auth plugin was configured and if credentials were provided, so the Mock components do just that. This makes the tests easier and faster
*Cleanup a bunch of exceptions from the logs
* Enabled back `testUploadWithLibDirective`
=> Improve TestConfigSetsAPI

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/admin/SystemInfoHandler.java
Adjustment based on comments in - merged - #1894
1. Shorten the name solr_core_root->core_root
2. Always return the value, even if not explicitly defined
=> SOLR-14878: Expose solr.xml's coreRootDirectory property via the System Settings API (part 2)

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/util/SolrCLI.java
**bin/solr create_core -c test** was failing if solr.xml for the server defined coreRootDirectory different from solr_home. That's because the utility code was assuming solr_home, but was then failing when invoking the server that expected it somewhere else.
Check for extra parameter being present and fall back to solr_home.
=> SOLR-14880: Support coreRootDirectory setting when create new cores from command line, in standalone mode

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/admin/ConfigSetsHandler.java, solr/core/src/test/org/apache/solr/cloud/TestConfigSetsAPI.java, solr/solr-ref-guide/src/configsets-api.adoc, solr/solrj/src/java/org/apache/solr/common/params/ConfigSetParams.java, solr/solrj/src/test/org/apache/solr/common/util/TestZkMaintenanceUtils.java
When set to `true`, Solr will overwrite an existing configset in ZooKeeper if an UPLOAD action happens on an existing configset. 
A new `cleanup` parameter can also be passed to let Solr know what to do with the files that existed in the old configset, but no longer exist in the new configset (remove or keep)
=> SOLR-10391: Add overwrite option to UPLOAD ConfigSet action

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/request/macro/MacroExpander.java, solr/core/src/test/org/apache/solr/request/macro/TestMacroExpander.java
StringIndexOutOfBoundsException on bad syntax
TODO run tests etc.
https://issues.apache.org/jira/browse/SOLR-13181
=> SOLR-13181: param macro expansion could throw

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/BinaryDocValuesWriter.java, lucene/core/src/java/org/apache/lucene/index/NormValuesWriter.java, lucene/core/src/java/org/apache/lucene/index/NumericDocValuesWriter.java, lucene/core/src/java/org/apache/lucene/index/SortingCodecReader.java, lucene/core/src/test/org/apache/lucene/index/TestSortingCodecReader.java
SortingCodecReader keeps all docvalues in memory that are loaded from this reader.
Yet, this reader should only be used for merging which happens sequentially. This makes
caching docvalues unnecessary.
=> LUCENE-9539: Remove caches from SortingCodecReader

lucene/core/src/java/org/apache/lucene/search/Weight.java, lucene/core/src/java/org/apache/lucene/search/comparators/DocComparator.java, lucene/core/src/java/org/apache/lucene/search/comparators/NumericComparator.java, lucene/core/src/test/org/apache/lucene/search/TestFieldSortOptimizationSkipping.java
Fix bug how iterator with skipping functionality
advances and produces docs
Relates to #1725
=> Fix bug in sort optimization

lucene/core/src/java/org/apache/lucene/store/ByteBuffersDataOutput.java
This is called transitively from `DocumentsWriterFlushControl#doAfterDocument` which is synchronized and appears to be a point of contention.
=> LUCENE-9535: Make ByteBuffersDataOutput#ramBytesUsed run in constant-time.

solr/solrj/src/java/org/apache/solr/client/solrj/impl/BaseCloudSolrClient.java
https://issues.apache.org/jira/browse/SOLR-14828
=> SOLR-14828: reduce 'error' logging noise in BaseCloudSolrClient.requestWithRetryOnStaleState

solr/CHANGES.txt, solr/bin/solr, solr/bin/solr.in.sh
https://issues.apache.org/jira/browse/SOLR-11167
=> SOLR-11167: Avoid $SOLR_STOP_WAIT use during 'bin/solr start' if $SOLR_START_WAIT is supplied.

solr/CHANGES.txt, solr/solr-ref-guide/src/major-changes-in-solr-9.adoc
Upgrade notes have been moved out of changes.txt. While working on PR #1900, I found there were few entries which were still present in changes.txt (most likely added at a later time)
=> Move 9x upgrade notes out of changes.txt

build.gradle, gradle/generation/nori.gradle
There is no script for Nori dictionary after the Ant build was deleted in [LUCENE-9433](https://issues.apache.org/jira/browse/LUCENE-9433).
=> LUCENE-9544: Port Nori dictionary compilation

solr/core/src/java/org/apache/solr/core/RateLimiterConfig.java, solr/core/src/java/org/apache/solr/handler/ClusterAPI.java, solr/core/src/java/org/apache/solr/servlet/QueryRateLimiter.java, solr/core/src/java/org/apache/solr/servlet/RateLimitManager.java, solr/core/src/java/org/apache/solr/servlet/RateLimiterConfig.java, solr/core/src/java/org/apache/solr/servlet/RequestRateLimiter.java, solr/core/src/java/org/apache/solr/servlet/SolrDispatchFilter.java, solr/core/src/test/org/apache/solr/servlet/TestRequestRateLimiter.java, solr/solr-ref-guide/src/rate-limiters.adoc, solr/solrj/src/java/org/apache/solr/client/solrj/request/beans/RateLimiterMeta.java
This commit moves rate limiters configuration from web.xml to clusterprops.json and allows setting the configuration using a newly added command.
=> SOLR-13528: Implement API Based Config For Rate Limiters

lucene/core/src/java/org/apache/lucene/store/ByteBuffersDataOutput.java, lucene/core/src/test/org/apache/lucene/store/TestByteBuffersDataOutput.java
This helps remove the assumption that all blocks have the same size.
=> Compute RAM usage ByteBuffersDataOutput on the fly.

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/schema/IntPointField.java, solr/core/src/java/org/apache/solr/schema/LongPointField.java, solr/core/src/java/org/apache/solr/schema/TrieField.java, solr/core/src/test/org/apache/solr/update/TestUpdate.java
Int and Long fields when passed as a string should consider all possible value formats and not throw NumberFormatException
Use Double.parse as a fallback when it fails
added a test to index with values as `42.2` which should not cause NumberFormatException
=> SOLR-14767 : fix long field parsing from string

solr/CHANGES.txt
Encountered a cherry-pick merge conflict and it seems that these two entries are present in the master branch's solr/CHANGES.txt 8.7 section but (unintentionally?) missing in the branch_8x solr/CHANGES.txt 8.7 section.
=> branch_8x: add two missing(?) solr/CHANGES.txt entries

lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriter.java
Some applications can use the pendingNumDocs from IndexWriter to 
estimate that the number of documents of an index is very close to the
hard limit so that it can reject writes without constructing Lucene
documents.
Backport of #1941
=> LUCENE-9554: Expose IndexWriter#pendingNumDocs

lucene/core/src/java/org/apache/lucene/search/ConjunctionDISI.java, lucene/core/src/test/org/apache/lucene/search/TestConjunctionDISI.java
Ensure sub-iterators of a conjunction iterator don't advance outside
of it.
Add assertions for checking that all sub-iterators are always on the
same document.
=> LUCENE-9541 ConjunctionDISI sub-iterators check

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/Weight.java
PR #1351 introduced a sort optimization where
documents can be skipped.  
But there was a bug in case we were using two phase
approximation, as we would advance it without advancing
an overall conjunction iterator.
This patch fixed it.
Relates to #1351
=> LUCENE-9555: Advance conjuction Iterator for two phase iteration

lucene/core/src/java/org/apache/lucene/search/Weight.java, lucene/core/src/java/org/apache/lucene/search/comparators/DocComparator.java, lucene/core/src/java/org/apache/lucene/search/comparators/NumericComparator.java
PR #1351 introduced a sort optimization where documents can be skipped.
But iteration over competitive iterators was not properly organized,
as they were not storing the current docID, and
when competitive iterator was updated, the current doc ID was lost.
This patch fixes it.
Relates to #1351
=> LUCENE-9565 Fix competitive iteration

lucene/core/src/java/org/apache/lucene/search/comparators/DocComparator.java, lucene/core/src/test/org/apache/lucene/search/TestFieldSortOptimizationSkipping.java
Sort optimization on _doc was introduced in PR #1856,
but it looks unstable and lead to some recent tests failures.
As the release of 8.7 is very soon, we need to temporarily
disable the sort optimization on _doc for this release
with a plan to stabilize it for later releases.
=> LUCENE-9569 Disalbe sort opt on _doc

solr/core/src/java/org/apache/solr/core/CoreContainer.java, solr/core/src/java/org/apache/solr/security/PublicKeyHandler.java, solr/core/src/test/org/apache/solr/cloud/TestCryptoKeys.java, solr/core/src/test/org/apache/solr/cloud/TestSolrCloudWithDelegationTokens.java, solr/core/src/test/org/apache/solr/security/BasicAuthIntegrationTest.java, solr/core/src/test/org/apache/solr/security/JWTAuthPluginIntegrationTest.java, solr/core/src/test/org/apache/solr/security/JWTAuthPluginTest.java, solr/core/src/test/org/apache/solr/security/PKIAuthenticationIntegrationTest.java, solr/core/src/test/org/apache/solr/security/TestAuthorizationFramework.java, solr/core/src/test/org/apache/solr/security/TestPKIAuthenticationPlugin.java, solr/core/src/test/org/apache/solr/security/hadoop/TestDelegationWithHadoopAuth.java, solr/core/src/test/org/apache/solr/security/hadoop/TestImpersonationWithHadoopAuth.java, solr/core/src/test/org/apache/solr/security/hadoop/TestSolrCloudWithHadoopAuthPlugin.java, solr/test-framework/src/java/org/apache/solr/SolrTestCase.java, solr/test-framework/src/java/org/apache/solr/cloud/SolrCloudAuthTestCase.java
The key pair generation is expensive and instead of disabling public key handler We should just reuse a single key pair in the entire test suite.
=> Reuse crypto keys in reference impl

lucene/MIGRATE.md, lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/JapanesePartOfSpeechStopFilterFactory.java, lucene/analysis/kuromoji/src/test/org/apache/lucene/analysis/ja/TestJapanesePartOfSpeechStopFilterFactory.java
If a user does not specify the "tags" argument for
JapanesePartOfSpeechStopFilterFactory, it is unlikely that their
intention was to omit the filter. (Why would they use
JapanesePartOfSpeechStopFilterFactory at all in that case?)
This change loads the stoptags.txt that ships in the Kuromoji
analysis jar if no tags argument is specified.
Loading default stop tags if "tags" argument is not specified in JapanesePartOfSpeechStopFilterFactory.
If the "tags" argument is not specified. then we load the default stop tags (as defined by `JapaneseAnalyzer.getDefaultStopTags()`) in the constructor (rather than waiting for the call to `inform`).
This implementation was chosen to be consistent with KoreanPartOfSpeechStopFilterFactory.
I added a note to MIGRATE.md, in case anyone is currently using …
=> LUCENE-9567: JPOSSFF loads built-in stop tags by default

solr/CHANGES.txt, solr/webapp/web/js/angular/controllers/collections.js, solr/webapp/web/partials/collections.html
As of now we can already add NRT replica from admin UI. Would look to add drop down listing all types of replicas along with the live nodes drop down. With my personal experience replica type, is utmost crucial and it is really annoying to add replica from API every time.
Here is how the interface looks like now. let me know if it's looks good or any other adjustment is required.
=> SOLR-14933: Ability to add T and P type replica from admin UI

lucene/core/src/java/org/apache/lucene/util/automaton/Automata.java, lucene/core/src/test/org/apache/lucene/util/automaton/TestAutomaton.java
Currently a TermRangeQuery with the empty String ("") as lower bound and
includeLower=false leads internally constructs an Automaton that doesn't match
anything. This is unexpected expecially for open upper bounds where any string
should be considered to be "higher" than the empty string.
This PR changes "Automata#makeBinaryInterval" so that for an empty string lower
bound and an open upper bound, any String should match the query regardless or
the includeLower flag.
Added two new tests to `TestAutomaton`.
=> LUCENE-9578: TermRangeQuery empty string lower bound edge case

solr/contrib/dataimporthandler/src/java/org/apache/solr/handler/dataimport/DataImportHandler.java, solr/contrib/velocity/src/java/org/apache/solr/response/VelocityResponseWriter.java, solr/core/src/java/org/apache/solr/core/HdfsDirectoryFactory.java, solr/core/src/java/org/apache/solr/core/backup/repository/HdfsBackupRepository.java, solr/core/src/java/org/apache/solr/store/hdfs/HdfsDirectory.java, solr/core/src/java/org/apache/solr/store/hdfs/HdfsFileWriter.java, solr/core/src/java/org/apache/solr/store/hdfs/HdfsLocalityReporter.java, solr/core/src/java/org/apache/solr/store/hdfs/HdfsLockFactory.java, solr/core/src/java/org/apache/solr/update/HdfsTransactionLog.java, solr/core/src/java/org/apache/solr/update/HdfsUpdateLog.java
For DIH, HDFS, Velocity.
These [will] *move* outside the Solr project, and are not disappearing from a user's standpoint.  Use of Deprecated annotation on a plugin will cause a warning on startup, which will needlessly alarm users for these plugins.
See https://issues.apache.org/jira/browse/SOLR-12987?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=17203524#comment-17203524
And raised recently on the dev list.
=> SOLR Mark only @deprecated tag, not @Deprecated annotation

solr/solr-ref-guide/src/configsets-api.adoc
The previous example in the documentation only used the less-user-friendly `configSetProp.<name>` option.
=> Add example for ConfigSet create with properties map.

solr/docker/build.gradle
https://issues.apache.org/jira/browse/SOLR-14947
After running `./gradlew docker` the following output is given:
```
Solr Docker Image Created
Name: apache/solr:9.0.0-SNAPSHOT
Base Image: openjdk:11-jre-slim
```
=> SOLR-14947: Print out image info after gradle docker task.

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/cloud/ZkController.java, solr/core/src/java/org/apache/solr/core/CoreContainer.java, solr/core/src/java/org/apache/solr/core/SolrCore.java, solr/core/src/java/org/apache/solr/servlet/HttpSolrCall.java, solr/core/src/java/org/apache/solr/update/SolrCoreState.java
This PR is based on the work of @CaoManhDat 
The shutdown process waits for all replicas/cores to be closed before removing the election node of the leader. This can take some time due to index flush or merge activities on the leader cores and delays new leaders from being elected. This leads to long gap of time during which indexing requests fail.
This PR introduces a Phaser that registers and deregisters all update requests. The shutdown process pauses indexing requests, waits for all in-flight indexing requests to complete, removes election nodes (thus triggering leader election) and then closes all replicas.
Since this PR makes changes to Solr's shutdown process, it is difficult to write a unit/integration tests inside Solr itself. This was tested by creating a test harness outside of …
=> SOLR-14942: Reduce leader election time on node shutdown

lucene/core/src/java/org/apache/lucene/index/SortingCodecReader.java, lucene/core/src/java/org/apache/lucene/index/VectorValuesWriter.java, lucene/core/src/test/org/apache/lucene/index/TestSortingCodecReader.java
This ensures that vector values are sorted when sorting an index after-the-fact
using `SortingCodecReader`.
=> LUCENE-9322: Make sure to account for vectors in SortingCodecReader.

solr/solrj/src/test/org/apache/solr/common/cloud/SolrZkClientTest.java
Minor change to speedup `SolrZkClientTest.testWrappingWatches`
=> Remove sleeps from SolrZkClientTest.testWrappingWatches

gradle/testing/defaults-tests.gradle
This adds back the test runner option, so testing is strict with internal APIs.
=> LUCENE-9587: Add '--illegal-access=deny' to test runner

lucene/core/src/java/org/apache/lucene/index/OrdinalMap.java, lucene/core/src/test/org/apache/lucene/index/TestOrdinalMap.java
For doc values that are not too high cardinality, it is common for some large
segments to contain all distinct values. In this case, we can check if the first
segment ords map perfectly to global ords, and if so store the global ord deltas
and first segment indices as `LongValues.ZEROES`
to save some space.
=> LUCENE-9536: Optimize OrdinalMap when one segment contains all distinct values.

lucene/codecs/src/java/org/apache/lucene/codecs/simpletext/SimpleTextVectorReader.java, lucene/core/src/java/org/apache/lucene/codecs/VectorWriter.java, lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90VectorReader.java, lucene/core/src/java/org/apache/lucene/index/RandomAccessVectorValues.java, lucene/core/src/java/org/apache/lucene/index/RandomAccessVectorValuesProducer.java, lucene/core/src/java/org/apache/lucene/index/VectorValues.java, lucene/core/src/java/org/apache/lucene/index/VectorValuesWriter.java, lucene/core/src/test/org/apache/lucene/index/TestVectorValues.java
This moves the random access vector interface out of VectorValues with the idea of making it less prominent. All implementations still support it, and it is required by the codec, but the public-facing VectorValues api becomes cleaner.
=> LUCENE-9583: extract separate RandomAccessVectorValues interface

lucene/codecs/src/java/org/apache/lucene/codecs/simpletext/SimpleTextTermVectorsWriter.java, lucene/codecs/src/java/org/apache/lucene/codecs/simpletext/SimpleTextVectorFormat.java, lucene/codecs/src/java/org/apache/lucene/codecs/simpletext/SimpleTextVectorReader.java, lucene/core/src/java/org/apache/lucene/index/VectorValuesWriter.java
* Make sure the files are unique by renaming the term vectors extension to `tvc`.
* Fix a bug where reading a vector would drop the leading digit of the first element.
=> LUCENE-9322: Some fixes to SimpleTextVectorFormat.

lucene/core/src/java/org/apache/lucene/index/OrdinalMap.java
Previously we only checked that the first segment's ordinal deltas were all
zero. This didn't account for some rare cases where some of the segment's
ordinals are filtered out, so the ordinals aren't contiguous. In these cases we
fill in dummy values for the missing ordinal deltas. So a segment's ordinals
can appear to match the global ordinals perfectly, but not actually contain all
the terms.
Such a case can arise when using a FilteredTermsEnum, for example when merging
a segment with deletions.
=> LUCENE-9536: Correct the OrdinalMap optimization.

lucene/core/src/java/org/apache/lucene/document/FeatureField.java, lucene/core/src/test/org/apache/lucene/document/TestFeatureField.java
This adds a linear function and newLinearQuery for FeatureField
=> LUCENE-9594 Add linear function for FeatureField

lucene/CHANGES.txt, lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene87/Lucene87Codec.java, lucene/core/src/java/org/apache/lucene/codecs/lucene80/Lucene80DocValuesConsumer.java, lucene/core/src/java/org/apache/lucene/codecs/lucene80/Lucene80DocValuesFormat.java, lucene/core/src/java/org/apache/lucene/codecs/lucene80/Lucene80DocValuesProducer.java, lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90Codec.java, lucene/core/src/test/org/apache/lucene/codecs/lucene80/BaseLucene80DocValuesFormatTestCase.java, lucene/core/src/test/org/apache/lucene/codecs/lucene80/TestBestCompressionLucene80DocValuesFormat.java, lucene/core/src/test/org/apache/lucene/codecs/lucene80/TestBestSpeedLucene80DocValuesFormat.java, lucene/core/src/test/org/apache/lucene/codecs/lucene87/TestLucene87StoredFieldsFormatHighCompression.java, lucene/test-framework/src/java/org/apache/lucene/index/RandomCodec.java, lucene/test-framework/src/java/org/apache/lucene/util/TestRuleSetupAndRestoreClassEnv.java, solr/core/src/java/org/apache/solr/core/SchemaCodecFactory.java, solr/core/src/test/org/apache/solr/core/TestCodecSupport.java
This adds a switch to `Lucene80DocValuesFormat` which allows to
configure whether to prioritize retrieval speed over compression ratio
or the other way around. When prioritizing retrieval speed, binary doc
values are written using the exact same format as before more aggressive
compression got introduced.
=> LUCENE-9378: Make it possible to configure how to trade speed for compression on doc values.

lucene/core/src/test/org/apache/lucene/util/TestVectorUtil.java
TestVectorUtil occasionally fails because of floating point errors. This
change slightly increases the epsilon in equality checks -- testing shows that
this will greatly decrease the chance of failure.
=> LUCENE-9592: Loosen equality checks in TestVectorUtil.

solr/CHANGES.txt, solr/contrib/ltr/src/java/org/apache/solr/ltr/interleaving/Interleaving.java, solr/contrib/ltr/src/java/org/apache/solr/ltr/search/LTRQParserPlugin.java, solr/contrib/ltr/src/test/org/apache/solr/ltr/TestLTRQParserPlugin.java, solr/contrib/ltr/src/test/org/apache/solr/ltr/interleaving/TestLTRQParserInterleaving.java, solr/solr-ref-guide/src/learning-to-rank.adoc
This pull requests add a parameter 'interleavingAlgorithm' in Learning To Rank to specify the Interleaving algorithm to use (Only TeamDraft supported)
Added the parameter and defaults
Added a new test class for the  LTR QueryParser, related with interleaving parameters
=> SOLR-15015: added support to parametric Interleaving algorithm

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java, lucene/core/src/java/org/apache/lucene/index/DocumentsWriterStallControl.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriter.java
DWStallControl expects the caller to loop on top of the wait call to make
progress with flushing if the DW is stalled. This logic wasn't applied such that
DW only stalled for one second and then released the indexing thread. This can cause
OOM if for instance during a full flush one DWPT gets stuck and other threads keep on
indexing.
=> LUCENE-9508: Fix DocumentsWriter to block threads until unstalled

solr/CHANGES.txt, solr/solr-ref-guide/src/enabling-ssl.adoc, solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java, solr/solrj/src/test/org/apache/solr/client/solrj/impl/Http2SolrClientTest.java
Based on patch by Andras Salamon in https://issues.apache.org/jira/browse/SOLR-14851
Signed-off-by: Jan Høydahl <janhoy@apache.org>
Make truststore and keystore type configurable in Http2SolrClient 
Extended the existing test case
=> SOLR-14851 Http2SolrClient doesn't handle keystore type

lucene/core/src/java/org/apache/lucene/codecs/lucene84/PForUtil.java
in [LUCENE-9027](https://github.com/apache/lucene-solr/pull/973) lucene introduced SIMD to decode postings, which leaves a very small problem. since this is a hot way when indexing and searching, so fixing it may make a bit sense. i hope i can fix this problem as my first PR on this amazing project :)
detail:
maxUnpatchedValue has already computed apache.lucene.codecs.lucene84.PForUtil#encode line 64
```
final long maxUnpatchedValue = (1L << patchedBitsRequired) - 1;
```
but this value is computed later again:
apache.lucene.codecs.lucene84.PForUtil#encode line 74
```
if (longs[i] > (1L << patchedBitsRequired) - 1) ...
```
convert 
apache.lucene.codecs.lucene84.PForUtil#encode line 74
```
if (longs[i] > (1L << patchedBitsRequired) - 1) ...
```
to 
```
if (longs[i] > maxUnpatchedValue) ... …
```
=> LUCENE-9624: fix duplicate compute on maxUnpatchedValue

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/core/SolrConfig.java, solr/core/src/test/org/apache/solr/core/TestMinimalConfig.java
Fixes https://issues.apache.org/jira/browse/SOLR-15017
=> SOLR-15017: The core's lib/ folder content is not loaded in the classloader anymore when the core's configuration does not define any <lib> element

solr/core/src/java/org/apache/solr/handler/ContentStreamHandlerBase.java, solr/core/src/java/org/apache/solr/servlet/HttpSolrCall.java
This addresses review feedback [1] from David Smiley on Jira. It moves the request registration to the ContentStreamHandlerBase class instead of doing a hack-ish instanceof check inside HttpSolrCall.
[1] - https://issues.apache.org/jira/browse/SOLR-14942?focusedCommentId=17227639&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17227639
=> SOLR-14942: Move request registration to ContentStreamHandlerBase

solr/solr-ref-guide/src/solr-upgrade-notes.adoc
The upgrade notes in ref-guide tends to sometimes be updated in 8.x branches only and not synced to master branch.
This is an attempt, (inspired by and fixes #2102). I diffed the `branch_8x` version with master and saw that the 8x wording in most cases was more up to date. I tried to make sure that the updates are valid for 9.x, and skipped a few refguide links that I I believe may have been since removed, but have not tried to compile the refguide to detect its validity.
=> Reconcile upgrade notes in master

lucene/CHANGES.txt, lucene/queries/src/java/org/apache/lucene/queries/intervals/ConjunctionIntervalIterator.java, lucene/queries/src/java/org/apache/lucene/queries/intervals/IntervalIterator.java, lucene/queries/src/test/org/apache/lucene/queries/intervals/OneTimeIntervalSource.java, lucene/queries/src/test/org/apache/lucene/queries/intervals/TestIntervalQuery.java
* In `ConjunctionIntervalIterator` check whether approximation's returned docId is NO_MORE_DOCS to avoid `nextInterval()` call after NO_MORE_DOCS is returned
* Add a test case to verify the problem is addressed
=> LUCENE-9618: Do not call IntervalIterator.nextInterval after NO_MORE_DOCS returned

lucene/core/src/java/org/apache/lucene/search/FieldComparator.java, lucene/core/src/java/org/apache/lucene/search/FieldValueHitQueue.java, lucene/core/src/java/org/apache/lucene/search/LeafFieldComparator.java, lucene/core/src/java/org/apache/lucene/search/TopFieldCollector.java, lucene/core/src/java/org/apache/lucene/search/comparators/NumericComparator.java
Disable sort optimization in comparators on index sort.
Currently, if search sort is equal or a part of the index sort, we have
an early termination in TopFieldCollector.
But comparators are not aware of the index sort, and may run
sort optimization even if the search sort is congruent with
the index sort.
This patch:
- make leaf comparators aware that search sort is congruent
with the index sort.
- disables sort optimization in comparators in this case.
- removes a private  MultiComparatorLeafCollector class as the only
class that extended that class was TopFieldLeafCollector that
now incorporates the logic of the deleted class.
Relates to #1351
=> LUCENE-9599 Disable sort optim on index sort

solr/CHANGES.txt, solr/core/src/test/org/apache/solr/search/function/AggValueSourceTest.java, solr/solrj/src/java/org/apache/solr/client/solrj/io/SolrClientCache.java, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/CloudSolrStream.java, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/SolrStream.java, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/TupleStream.java, solr/solrj/src/test/org/apache/solr/client/solrj/io/stream/StreamingTest.java
Backport of #2067 to `branch_8x`; see original PR for detailed description and checklist.
=> SOLR-14987: Reuse HttpSolrClient per node vs. one per Solr core when using CloudSolrStream

dev-tools/scripts/releaseWizard.yaml
The release wizard doesn't currently tell the RM to add the new release to the apache release reporter.
This is a simple change to add that one step at the end of announcing the new version.
=> Adding Apache Reporter step in Release Wizard.

lucene/core/src/java/org/apache/lucene/search/comparators/DocComparator.java, lucene/core/src/java/org/apache/lucene/search/comparators/DoubleComparator.java, lucene/core/src/java/org/apache/lucene/search/comparators/FloatComparator.java, lucene/core/src/java/org/apache/lucene/search/comparators/IntComparator.java, lucene/core/src/java/org/apache/lucene/search/comparators/LongComparator.java, lucene/core/src/java/org/apache/lucene/search/comparators/MinDocIterator.java, lucene/core/src/java/org/apache/lucene/search/comparators/NumericComparator.java
Files in org.apache.lucene.search.comparators package
has a wrong indent of 4 spaces instead of 2.
This patch fixes only the indent from 4 to correct 2 spaces
=> Fix format indent from 4 to 2 spaces

gradle/generation/javacc.gradle, lucene/CHANGES.txt, lucene/queryparser/src/java/org/apache/lucene/queryparser/classic/QueryParser.java
This is basically the same as https://issues.apache.org/jira/browse/SOLR-11242 , but for Lucene QueryParser
=> LUCENE-9021 QueryParser: re-use the LookaheadSuccess exception

lucene/core/src/java/org/apache/lucene/codecs/lucene84/ForUtil.java, lucene/core/src/java/org/apache/lucene/codecs/lucene84/gen_ForUtil.py
In `decode6()` `decode7()` `decode12()` `decode14()` `decode15()` `decode24()`, longs always `&` a same mask and do some shift. By printing assemble language, i find that JIT did not optimize them with SIMD instructions. But when we extract all `&` operations and do them first, JIT will use SIMD to optimize them.
Java Version: 
> java version "11.0.6" 2020-01-14 LTS
> Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
> Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)
Using `decode15()` as an example, here is a microbenchmark based on JMH:
**code:**
```
@Benchmark
@BenchmarkMode({Mode.Throughput})
@Fork(1)
@Measurement(iterations = 10, time = 1, timeUnit = TimeUnit.SECONDS)
@Warmup(iterations = 3, time = 1, timeUnit = TimeUnit.SECONDS)
public void decode15a() …
```
=> LUCENE-9636: Extract and operation to get a SIMD optimize

solr/CHANGES.txt, solr/bin/solr
See JIRA: https://issues.apache.org/jira/browse/SOLR-15046
Fix bin/solr IF statement. 
Manual test using:
```
cd solr
ant server
bin/solr start -c
bin/solr create -c test -s 1 -d _default
WARNING: Using _default configset with data driven schema functionality. NOT RECOMMENDED for production use.
To turn off: bin/solr config -c test -p 8983 -action set-user-property -property update.autoCreateFields -value false
Created collection 'test' with 1 shard(s), 1 replica(s) with config-set 'test'
```
=> SOLR-15046: Check if SOLR_SSL_ENABLED strictly equal to true for setting solr.jetty.https.port

lucene/CHANGES.txt, lucene/queryparser/build.xml, lucene/queryparser/src/java/org/apache/lucene/queryparser/classic/QueryParser.java
Same as https://github.com/apache/lucene-solr/pull/962, for branch 8.x
This is basically the same as https://issues.apache.org/jira/browse/SOLR-11242 , but for Lucene QueryParser
=> LUCENE-9021 QueryParser: re-use the LookaheadSuccess exception for branch_8x

solr/core/src/test/org/apache/solr/core/ConfigureRecoveryStrategyTest.java
Backport fix to 8x ... See parent PR -> https://github.com/apache/lucene-solr/pull/2150
=> SOLR-15054: Test should not require private methods to be final

solr/CHANGES.txt
So that 8.8.0 sections match on master and branch_8x branches.
=> Add two solr/CHANGES.txt entries for SOLR-14981 and SOLR-15046.

lucene/CHANGES.txt, lucene/sandbox/src/java/org/apache/lucene/sandbox/search/MultiNormsLeafSimScorer.java, lucene/sandbox/src/test/org/apache/lucene/sandbox/search/TestBM25FQuery.java
Through some experimentation with with the BM25FQuery on long documents, I've discovered that there is a bug that doesn't mask the encoded norm's long value during scoring. For long documents (or long fields) this may cause ArrayIndexOutOfBoundsExceptions.
The line where I suspect the bug is being exposed is here
https://github.com/apache/lucene-solr/blob/master/lucene/sandbox/src/java/org/apache/lucene/sandbox/search/MultiNormsLeafSimScorer.java#L131
Here is a similar use in BM25Similarity with the masking
https://github.com/apache/lucene-solr/blob/c413656b627160d49eb9e9f1f84ec4945db80f0e/lucene/core/src/java/org/apache/lucene/search/similarities/BM25Similarity.java#L233
My experimentation shows that to expose this bug, there must be a match for a token in more than one field (which is …
=> LUCENE-9635: BM25FQuery - Mask encoded norm long value in array lookup

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/FieldInfos.java, lucene/core/src/test/org/apache/lucene/index/TestFieldInfos.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterDelete.java
FieldNumbers.clear() is called from IndexWriter.deleteAll(), which is
supposed to completely reset the state of the index. This includes
clearing all known fields.
Prior to this change, it would allocate progressively higher field
numbers, which results in larger and  larger arrays for
FieldInfos.byNumber, effectively "leaking" field numbers every time
deleteAll() is called.
If you run a loop that repeatedly adds documents to an IndexWriter and calls deleteAll, new fields will be given progressively higher index numbers. Since these index numbers are reflected in the size of the FieldInfos.byNumber array, this is effectively a memory leak.
Reset lowestUnassignedFieldNumber to -1 when FieldNumbers.clear() is called (resetting the state to that of a newly-created FieldNumbers instance). …
=> LUCENE-9617: Reset lowestUnassignedFieldNumber in FieldNumbers.clear()

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/update/processor/DistributedZkUpdateProcessor.java, solr/core/src/test/org/apache/solr/cloud/ForceLeaderTest.java, solr/core/src/test/org/apache/solr/cloud/HttpPartitionTest.java, solr/core/src/test/org/apache/solr/cloud/ReplicationFactorTest.java, solr/solrj/src/java/org/apache/solr/client/solrj/impl/BaseCloudSolrClient.java, solr/solrj/src/java/org/apache/solr/client/solrj/request/UpdateRequest.java
Remove min_rf and MIN_REPFACT references in code, tests and documentation.
Incrementally remove min_rf and MIN_REPFACT references.
./gradlew check
=> SOLR-14034: remove deprecated min_rf references

lucene/suggest/src/java/org/apache/lucene/search/suggest/document/ContextQuery.java, lucene/suggest/src/test/org/apache/lucene/search/suggest/document/TestPrefixCompletionQuery.java, lucene/suggest/src/test/org/apache/lucene/search/suggest/document/TestRegexCompletionQuery.java
Follow-up to https://github.com/apache/lucene-solr/pull/375.
=> LUCENE-8287: In ContextQuery, use a more comprehensive check for an empty prefix automaton

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/response/transform/ChildDocTransformer.java, solr/core/src/java/org/apache/solr/response/transform/ChildDocTransformerFactory.java, solr/core/src/java/org/apache/solr/schema/IndexSchema.java, solr/core/src/test/org/apache/solr/response/transform/TestChildDocTransformer.java, solr/solr-ref-guide/src/transforming-result-documents.adoc
https://issues.apache.org/jira/browse/SOLR-15069
Repeated issue description:
The `parentFilter` param to `[child]` was once required, and then made only optional if you have a `_nest_path_` field, but I think it can be optional (perhaps obsolete) altogether.  All we have to do is grab the uniqueKey field from the document to be transformed, look this up in the `_root_` field, and you'll get the internal Lucene docId of the first child doc.  No problem, and quick.
CC @moshebla  @thomaswoeckinger
I came about doing this because I too-soon documented in #2159 that `_nest_path_` field was no longer required for doing atomic/partial updates in a nested schema.  Instead of removing the documentation I wrote, and then realizing I would then need to add safety prevention (otherwise child docs …
=> SOLR-15069 child parent filter

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/component/RealTimeGetComponent.java, solr/core/src/java/org/apache/solr/schema/IndexSchema.java, solr/core/src/java/org/apache/solr/schema/NestPathField.java, solr/core/src/java/org/apache/solr/search/SolrReturnFields.java, solr/core/src/java/org/apache/solr/update/AddUpdateCommand.java, solr/core/src/java/org/apache/solr/update/DirectUpdateHandler2.java, solr/core/src/java/org/apache/solr/update/DocumentBuilder.java, solr/core/src/java/org/apache/solr/update/UpdateLog.java, solr/core/src/java/org/apache/solr/update/processor/AtomicUpdateDocumentMerger.java, solr/core/src/java/org/apache/solr/update/processor/ClassificationUpdateProcessor.java, solr/core/src/java/org/apache/solr/update/processor/DistributedUpdateProcessor.java, solr/core/src/java/org/apache/solr/update/processor/DistributedZkUpdateProcessor.java, solr/core/src/java/org/apache/solr/update/processor/NestedUpdateProcessorFactory.java, solr/core/src/java/org/apache/solr/update/processor/SkipExistingDocumentsProcessorFactory.java, solr/core/src/test-files/solr/collection1/conf/schema-nest.xml, solr/core/src/test/org/apache/solr/cloud/NestedShardedAtomicUpdateTest.java, solr/core/src/test/org/apache/solr/update/processor/AtomicUpdatesTest.java, solr/core/src/test/org/apache/solr/update/processor/NestedAtomicUpdateTest.java, solr/solr-ref-guide/src/indexing-nested-documents.adoc, solr/solr-ref-guide/src/solr-upgrade-notes.adoc, solr/solr-ref-guide/src/updating-parts-of-documents.adoc, solr/solrj/src/java/org/apache/solr/common/SolrDocument.java, solr/solrj/src/java/org/apache/solr/common/SolrInputDocument.java
https://issues.apache.org/jira/browse/SOLR-14923
* UpdateLog.openRealtimeSearcher() was being called for every incoming document when the schema had _nest_path_.  It is now more limited to in-place-update of a child doc and in /get when a child doc is given, both of which are uncommon.
* Atomic/partial updates to nested documents should be faster. In-place updates of the same might be slower (needs to call openRealtimeSearcher).
Refactoring & minor bugs/improvements:
* Simplified AddUpdateCommand.getLuceneDoc & getLuceneDocsIfNested relationship, and DirectUpdateHandler2 which calls them.
* AddUpdateCommand.getIndexedId needed to be updated when _route_ was specified.
* NestedShardedAtomicUpdateTest no longer extends AbstractFullDistribZkTestBase because it wasn't really leveraging the …
=> SOLR-14923: Nested docs indexing performance.

lucene/CHANGES.txt, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestDictionary.java
Support aff files that don't have `SET encoding` directive
Copy the logic from hunspell C++
Added
=> LUCENE-9665: Hunspell: support default encoding

lucene/CHANGES.txt, lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene70/IndexedDISI.java, lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene70/Lucene70Codec.java, lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene70/Lucene70DocValuesConsumer.java, lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene70/Lucene70DocValuesFormat.java, lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene70/Lucene70DocValuesProducer.java, lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene70/Lucene70NormsConsumer.java, lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene70/Lucene70NormsFormat.java, lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene70/Lucene70NormsProducer.java, lucene/backward-codecs/src/resources/META-INF/services/org.apache.lucene.codecs.Codec, lucene/backward-codecs/src/resources/META-INF/services/org.apache.lucene.codecs.DocValuesFormat, lucene/backward-codecs/src/test/org/apache/lucene/backward_codecs/lucene70/Lucene70RWCodec.java, lucene/backward-codecs/src/test/org/apache/lucene/backward_codecs/lucene70/TestIndexedDISI.java, lucene/backward-codecs/src/test/org/apache/lucene/backward_codecs/lucene70/TestLucene70DocValuesFormat.java, lucene/backward-codecs/src/test/org/apache/lucene/backward_codecs/lucene70/TestLucene70NormsFormat.java, lucene/backward-codecs/src/test/org/apache/lucene/backward_index/TestBackwardsCompatibility.java
This change restores the Lucene70Codec for file format compatibility of
indices that are created within the Lucene 7 major version. These indices
can be opened via an expert API on DirectoryReader in read-only mode. Changes
to these indices are prohibited and will be rejected by the IndexWriter.
In fact, IndexWriter will not open an index that is created with a major version
less than N-1 to the current major version.
=> LUCENE-9669: Restore Lucene70Codec

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/core/SolrCore.java
https://issues.apache.org/jira/browse/SOLR-15081
Copying the description: 
> The core level metrics hold some interesting information, but I don't see information pertaining to the SolrCloud status of the core.  In particular, I'd like to see the leader status here, and also the replica state.  The use-case I have in mind is enabling the Prometheus Exporter to get the doc count (and maybe other basics) of only the leader replicas, thereby counting unique documents instead of a fully replicated figure.  This is an approximation to doing a match-all-docs query on all collections, but is a more sound approach when one has orders of magnitude more collections than nodes.
=> SOLR-15081: Metrics for core: isLeader, status

solr/core/src/java/org/apache/solr/handler/admin/ZookeeperInfoHandler.java
Looks like a bad backport from master for SOLR-12182.
Fix here is to pass the collection metadata through `ClusterStatus#postProcessCollectionJSON` to supply `base_url` from `node_name` as it's required by the UI.
There is no unit test for `ZookeeperInfoHandler` unfortunately, so requires manual testing:
```
cd solr
ant server
bin/solr -c
bin/solr create -c test
```
Visit the Admin UI and click on the Graph View for Cloud. Ensure you see the test collection in the graph.
=> SOLR-15097: Supply base_url in replica data returned to Admin UI

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestDependencies.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/dependencies.aff, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/dependencies.dic
aff:
SFX s Y 1
SFX s 0 s .
PFX p Y 1
PFX p 0 0/s .
dic:
calorie/p
"calories" should be accepted
When applying suffix "s" (which expects "s" flag to be set), check not only the word itself (which only has "p") flag, but the continuation flags of the just applied prefix "p" which has "s" as its continuation.
`TestDependencies` updated
=> LUCENE-9688: Hunspell: consider prefix's continuation flags when applying suffix

gradle/validation/forbidden-apis.gradle, gradle/validation/forbidden-apis/java.solr.txt, solr/core/src/java/org/apache/solr/cloud/Overseer.java, solr/core/src/java/org/apache/solr/cloud/SyncStrategy.java, solr/core/src/java/org/apache/solr/cloud/ZkController.java, solr/core/src/java/org/apache/solr/cloud/api/collections/OverseerRoleCmd.java, solr/core/src/java/org/apache/solr/core/CoreContainer.java, solr/core/src/java/org/apache/solr/handler/IndexFetcher.java, solr/core/src/java/org/apache/solr/handler/SnapShooter.java, solr/core/src/java/org/apache/solr/util/ConcurrentLRUCache.java, solr/solrj/src/java/org/apache/solr/common/cloud/SolrZooKeeper.java, solr/test-framework/src/java/org/apache/solr/BaseDistributedSearchTestCase.java, solr/test-framework/src/java/org/apache/solr/cloud/ChaosMonkey.java
When we are creating a new thread we should give it a name. This doesn't apply to Runnable or Callable objects that we pass to an executor, since those should be getting named by the executor itself.
Also, enforce forbidden APIs on the code. I didn't apply the rule to tests because there's so many of them and I think there is less value in the constraint.
This is especially helpful when doing profiling, otherwise we end up with a bunch of Thread-# that are hard to tell apart and search on.
=> Require Thread Names in Solr

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/cloud/api/collections/DeleteCollectionCmd.java, solr/core/src/java/org/apache/solr/cloud/api/collections/OverseerCollectionMessageHandler.java, solr/core/src/java/org/apache/solr/core/ConfigOverlay.java, solr/core/src/java/org/apache/solr/core/CoreContainer.java, solr/core/src/java/org/apache/solr/core/SolrCore.java, solr/core/src/java/org/apache/solr/metrics/SolrMetricManager.java, solr/core/src/java/org/apache/solr/metrics/reporters/jmx/JmxMetricsReporter.java, solr/core/src/test/org/apache/solr/HelloWorldSolrCloudTestCase.java, solr/core/src/test/org/apache/solr/core/TestCoreContainer.java, solr/solrj/src/java/org/apache/solr/common/cloud/ZkCmdExecutor.java, solr/solrj/src/java/org/apache/solr/common/cloud/ZkOperation.java, solr/solrj/src/java/org/apache/solr/common/cloud/ZkStateReader.java, solr/solrj/src/java/org/apache/solr/common/util/ValidatingJsonMap.java
Use j.u.c collections instead of sync block
Rework how we load implicit handlers
Additional debug and trace logging for zookeeper comms
=> SOLR-15120 Reduce duplicated core creation work

solr/contrib/analytics/src/test/org/apache/solr/analytics/SolrAnalyticsTestCase.java, solr/contrib/analytics/src/test/org/apache/solr/analytics/legacy/LegacyAbstractAnalyticsCloudTest.java, solr/test-framework/src/java/org/apache/solr/cloud/MiniSolrCloudCluster.java
`MiniSolrCloudCluster.waitForAllNodes` ignores passed timeout value and creates a `TimeOut` with 30 seconds.
Pass the provided timeout value to the `TimeOut` 
./gradlew check
=> SOLR-15025: MiniSolrCloudCluster.waitForAllNodes ignores passed timeout value

lucene/misc/src/java/org/apache/lucene/misc/store/DirectIODirectory.java, lucene/misc/src/test/org/apache/lucene/misc/store/TestDirectIODirectory.java
Explicitly handle read past EOF case in DirectIODirectory#readByte to throw EOFException
In DirectIODirectory.readByte, checks for `buffer.limit() == 0” after DirectIODirectory#refill was called.
* Add a new test to for read past EOF scenario
* Passed reported randomized test with `./gradlew test —tests TestDirectIODirectory.testFloatsUnderflow -Dtests.seed=73B56EAB13269C91 -Dtests.slow=true -Dtests.badapples=true -Dtests.locale=haw-US -Dtests.timezone=America/Inuvik -Dtests.asserts=true -Dtests.file.encoding=UTF-8`
* Passed `./gradlew check`
=> LUCENE-9686: Fix read past EOF handling in DirectIODirectory

lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriter.java
We fail to close the merged readers of an aborted merge if its output segment contains no document.
This bug was discovered by a test in Elasticsearch (https://github.com/elastic/elasticsearch/issues/67884).
=> LUCENE-9722: Close merged readers on abort

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestDictionary.java
e.g. `nl` dictionaries first have `KEEPCASE Kc` and only then `FLAG long`
Like Hunspell/C++, read affix twice: first extract important info like encoding and flag format, next — the rest.
Added
=> LUCENE-9716: Hunspell: support flag usage before its format is even specified

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/FieldInfos.java, lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriter.java
https://issues.apache.org/jira/browse/LUCENE-9680
As discussed in [this thread](http://mail-archives.apache.org/mod_mbox/lucene-dev/202101.mbox/browser), the `indexWriter::getFieldNames()` method is useful for enforcing soft/hard limits of index usage. 
I simply re-added `getFieldNames()` we recently removed in [LUCENE-8909](https://issues.apache.org/jira/browse/LUCENE-8909).
Added a unit test on `IndexWriter`
=> LUCENE-9680 - Re-add IndexWriter::getFieldNames

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/admin/AdminHandlersProxy.java, solr/core/src/java/org/apache/solr/handler/admin/LoggingHandler.java, solr/core/src/test/org/apache/solr/handler/admin/AdminHandlersProxyTest.java, solr/solr-ref-guide/src/configuring-logging.adoc, solr/webapp/web/js/angular/controllers/logging.js, solr/webapp/web/js/angular/services.js
=> SOLR-15011: /admin/logging handler is configured logs to all nodes

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/SpellCheckerTest.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/onlyincompound2.aff, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/onlyincompound2.dic, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/onlyincompound2.good, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/onlyincompound2.wrong
Hunspell has some special logic for these suffixes, which are only allowed depending on prefix presence
Replicate this logic
`onlyincompound2` from Hunspell repo
=> LUCENE-9721: Hunspell: disallow ONLYINCOMPOUND suffixes at the very end of compound words

lucene/backward-codecs/src/test/org/apache/lucene/backward_index/TestBackwardsCompatibility.java
This PR also cleans up some old checks that only applied to pre-6.0 indices.
=> Improve backwards compatibility tests for sorted indexes.

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
In [LUCENE-9680](https://issues.apache.org/jira/browse/LUCENE-9680) we re-added `IW::getFieldNames` back to `master`. The method still exists in 8x, so this simply removes the deprecation annotation. 
=> LUCENE-9680 - Backport to 8x - Remove deprecation from getFieldNames

lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90VectorWriter.java
A recent change replaced a static constant random seed initialized to `System.currentTimeMillis()` with a call to `System.currentTimeMillis()`, invalidating tests that relied on the consistent random behavior for reproducibility. This just undoes that change, restoring the use of `HnswGraphBuilder.randSeed`
=> LUCENE-9731: restore consistent random seed to HnswGraphBuilder

lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene50/Lucene50LiveDocsFormat.java, lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene70/Lucene70Codec.java, lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene80/Lucene80Codec.java, lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene84/Lucene84Codec.java, lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene86/Lucene86Codec.java, lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene87/Lucene87Codec.java, lucene/backward-codecs/src/test/org/apache/lucene/backward_codecs/lucene50/TestLucene50LiveDocsFormat.java, lucene/backward-codecs/src/test/org/apache/lucene/backward_index/TestBackwardsCompatibility.java, lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90Codec.java, lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90LiveDocsFormat.java, lucene/core/src/java/org/apache/lucene/codecs/lucene90/package-info.java, lucene/core/src/test/org/apache/lucene/codecs/lucene50/TestLucene90LiveDocsFormat.java
For now this is just a copy of Lucene50LiveDocsFormat. The existing
Lucene50LiveDocsFormat was moved to backwards-codecs.
=> LUCENE-9705: Create Lucene90LiveDocsFormat

lucene/sandbox/src/java/org/apache/lucene/sandbox/search/CombinedFieldQuery.java, lucene/sandbox/src/java/org/apache/lucene/sandbox/search/MultiNormsLeafSimScorer.java, lucene/sandbox/src/test/org/apache/lucene/sandbox/search/TestCombinedFieldQuery.java
From a high level, BM25FQuery (1) computes statistic that represent the combined
field content and (2) passes these to a score function. This model makes sense
for many similarities besides BM25.
This PR unhardcodes BM25Similarity in BM25FQuery and instead uses the one
configured on IndexSearcher. It also renames BM25FQuery since it's no longer
specific to BM25.
=> LUCENE-9725: Allow BM25FQuery to use other similarities.

solr/docker/Docker-FAQ.md
The warning is annoying if you know what it is, and alarming if you don't!  
Add to the Docker FAQ how to disable it.  
Eventually this might feed the Ref Guide!
Doc only
- [X ] I have created a Jira issue and added the issue ID to my pull request title.
- [X ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [X ] I have developed this patch against the `master` branch.
- [X ] I have run `./gradlew …
=> SOLR-15133: Document how to eliminate Failed to reserve shared memory warning

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/CheckCompoundPattern.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/RepEntry.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/SpellChecker.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/SpellCheckerTest.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/checkcompoundrep.aff, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/checkcompoundrep.dic, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/checkcompoundrep.good, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/checkcompoundrep.wrong
> CHECKCOMPOUNDREP
> Forbid compounding, if the (usually bad) compound word may be a non-compound word with a REP fault. Useful for languages with ‘compound friendly’ orthography.
When a new compound word part is about to appear, check that together with the previous one they don't form a misspelled simple word. For that, first introduce `CompoundPart` class (in a separate commit for easier review) to combine this new logic with similar `CHECKCOMPOUNDPATTERN` stuff.
`checkcompoundrep` from Hunspell/C++
=> LUCENE-9729: Hunspell: support CHECKCOMPOUNDREP flags

dev-tools/scripts/releaseWizard.yaml
During 8.8 release the RM missed some steps when publishing to maven. Turns out the step `release_maven` is a bit larger than wanted. This PR splits the step in two, one `stage_maven` that stages the artifacts using commands, and another `publish_maven` that is about clicking buttons on the repository.apache.org webpage. I have not tested the steps in bash, but here is the AsciiDoc render of the two steps, which looks good:
=> Split the publish_maven step in two TODOs

lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/SpellCheckerTest.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/TestHunspellRepositoryTestCases.java
Some of the original Hunspell's tests are out of scope of LUCENE-9687: Hunspell support improvements
Make their failures expected for now. Plus check suggestions in `TestHunspellRepositoryTestCases`.
The change itself is only about tests. `TestHunspellRepositoryTestCases` still fails and needs to be fixed.
=> LUCENE-9743: Hunspell: ignore original tests which are out of scope

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/GeneratingSuggester.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/ModifyingSuggester.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/SpellChecker.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/base_utf.sug, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/checksharps.sug, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/keepcase.sug
Hunspell has "ngram-based suggestions" where the dictionary is enumerated, forms are derived, and checked whether the result is similar to the misspelled word.
Here I start implementing this functionality, without affixes so far.
3 suggestion tests from Hunspell repo are now added
=> LUCENE-9742: Hunspell: suggest dictionary entries similar to the misspelled word

lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/ModifyingSuggester.java, lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/SpellChecker.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/SpellCheckerTest.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/i58202.aff, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/i58202.dic, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/i58202.good, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/i58202.sug, lucene/analysis/common/src/test/org/apache/lucene/analysis/hunspell/i58202.wrong
Fix a failing Hunspell repo test
Replicate Hunspell's logic around suggestion casing, especially mixed-case ones
`i58202` from Hunspell repo, whatever that means
=> LUCENE-9750: Hunspell: improve suggestions for mixed-case misspelled words

solr/CHANGES.txt, solr/solrj/src/java/org/apache/solr/common/cloud/ZkNodeProps.java
Fix for https://issues.apache.org/jira/browse/SOLR-15145
Unfortunately, we don't have a lot of options with this issue. We could just go back to storing  `base_url` but I like the system property (could add an ENV var too) for installations that can upgrade their SolrJ to 8.8 as it helps get them closer to Solr 9.x where we don't store `base_url` but also gives the possibility to run an older SolrJ client version against an upgraded Solr 8.8 server.
Tests still TBD ...
=> SOLR-15145: System property to control whether base_url is stored in state.json to enable back-compat with older SolrJ versions

lucene/core/src/java/org/apache/lucene/document/FieldType.java, lucene/test-framework/src/java/org/apache/lucene/index/BaseFieldInfoFormatTestCase.java
This commit adds coverage to `BaseFieldInfoFormatTestCase ` for points,
vectors, and the soft deletes field.
=> LUCENE-9756: Extend FieldInfosFormat tests to cover points and vectors

lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90VectorWriter.java, lucene/core/src/test/org/apache/lucene/codecs/lucene90/TestLucene90VectorFormat.java, lucene/test-framework/src/java/org/apache/lucene/index/BaseVectorFormatTestCase.java
While trying to add a test class for Vectors based on `BaseIndexFileFormatTestCase`, a bug surface on the Lucene90VectorWriter constructor. If there is an exception during construction, it might happen that files are not properly closed and therefore it might leak.
Here is the proposal, move the current `TestVectorValues` to a `BaseVectorFormatTestCase` which extends `BaseIndexFileFormatTestCase`.
Fix the constructor so it handle closing files on error properly.
=> LUCENE-9322:  Lucene90VectorWriter can leak open files

lucene/core/src/java/org/apache/lucene/index/CodecReader.java
Take into account the new Vectors format for methods:
- ramBytesUsed
- getChildResources
- checkIntegrity
This has surfaced after #2331 as there are some test fails when nightly flag is true:
```
./gradlew :lucene:core:test --tests "org.apache.lucene.codecs.lucene90.TestLucene90VectorFormat.testRamBytesUsed" -Ptests.jvms=4 -Ptests.jvmargs=-XX:TieredStopAtLevel=1 -Ptests.seed=38AB1FFD5F1E45F6 -Ptests.nightly=true -Ptests.file.encoding=ISO-8859-1
```
=> LUCENE-9322:  Add Vectors format to CodecReader accounting methods

solr/core/src/java/org/apache/solr/search/MaxScoreCollector.java
In Solr 8.6.3, minCompetitiveScore of WANDScorer resets to zero for each index segment and remain zero until maxScore is updated.
There are two causes of this problem:
- MaxScoreCollector does not set minCompetitiveScore of MinCompetitiveScoreAwareScorable newly generated for another index segment.
- MaxScoreCollector updates minCompetitiveScore only if maxScore is updated. This behavior is correct considering the purpose of MaxScoreCollector.
For details, see the attached pdf https://issues.apache.org/jira/secure/attachment/13019548/wand.pdf.
Fixed https://issues.apache.org/jira/browse/SOLR-15114
=> SOLR-15114: WAND does not work correctly on multiple segments in Solr 8.6.3

lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90FieldInfosFormat.java
Since this is a fresh format, we can remove older version logic and reset the
internal version to 0.
=> LUCENE-9705: Reset internal version in Lucene90FieldInfosFormat.

solr/CHANGES.txt, solr/solr-ref-guide/src/major-changes-in-solr-9.adoc, solr/solr-ref-guide/src/solr-upgrade-notes.adoc, solr/solrj/src/java/org/apache/solr/common/cloud/ZkNodeProps.java
Align solr's changes.txt with fixes going into 8x / 8.8 and change the default value of the `solr.storeBaseUrl` sys prop for master.
=> SOLR-15145: solr.storeBaseUrl feature flag introduced in 8.8.1 should default to false for 9.x

lucene/core/src/java/org/apache/lucene/codecs/lucene86/Lucene86PointsFormat.java, lucene/core/src/java/org/apache/lucene/index/ReadersAndUpdates.java
JIRA: https://issues.apache.org/jira/browse/LUCENE-9590
1. since Lucene 4.8.0,  mergingNumericUpdates was replaced by mergingDVUpdates, so we should update some annotation. see detail: https://issues.apache.org/jira/browse/LUCENE-5513
2. add a link on ASF WIKI to introduce the data structure of point value , it make source readers happy and quick to understand point value.
=> LUCENE-9590: Add javadoc for Lucene86PointsFormat class

lucene/queries/src/java/org/apache/lucene/queries/function/FunctionScoreQuery.java, lucene/queries/src/test/org/apache/lucene/queries/function/TestFunctionScoreQuery.java
https://issues.apache.org/jira/browse/LUCENE-9762
The score() may be called multiple times. It should take care to call DoubleValues.advanceExact only the first time, or risk faulty behavior including exceptions.
There isn't an 8.8.1 section in the CHANGES.txt on master branch but I can add it into branch_8x and branch_8_8 where eventually it will show up when the RM does a release?  Or I should just add it?
=> LUCENE-9762: FunctionScoreQuery must guard score() called twice

solr/solrj/src/java/org/apache/solr/common/cloud/ZkNodeProps.java
Found an additional problem when doing rolling upgrades related to base_url, so pulling this fix over from 8x
=> SOLR-15145: Additional fix for SolrJ back-compat

lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90VectorReader.java
Related to #2331, this time change the logic when creating a `Lucene90VectorReader` so it closes properly files on error.
=> LUCENE-9322: Lucene90VectorReader can leak open files

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/admin/ZookeeperInfoHandler.java
Quick fix to render collections with `perReplicaState=true` by using DocCollection instead of reading ZK data directly.
Btw ... there is no unit test for the `ZookeeperInfoHandler` so testing for this fix was manual. Created 12 collections 6 with perReplicaState=true and 6 with perReplicaState=false and exercised the graph panel in the cloud UI. See SOLR-15098 where a unit test should be created when refactoring `ZookeeperInfoHandler`
=> SOLR-15135: Use DocCollection to generate state.json format expected by UI to work with perReplicaState collections.

solr/core/src/java/org/apache/solr/cloud/api/collections/OverseerCollectionMessageHandler.java, solr/core/src/java/org/apache/solr/cloud/api/collections/RestoreCmd.java, solr/core/src/java/org/apache/solr/handler/admin/CollectionsHandler.java, solr/core/src/java/org/apache/solr/handler/admin/RestoreCoreOp.java, solr/solr-ref-guide/src/collection-management.adoc, solr/test-framework/src/java/org/apache/solr/cloud/api/collections/AbstractIncrementalBackupTest.java
As originally implemented, SolrCloud's `restore` operation only supported restoring to collections that didn't yet exist.  This was primarily done out of a fear of race conditions involving writes to the collection.  Since then the support for toggling a per-collection "readonly" property has made restoration to existing collections possible, but unimplemented.
This PR adds a codepath to restore to an existing collection, assuming it is compatible with the stored backup files. (A backup with 2 shards can't be restored to a collection with 3, etc.).  If the collection doesn't exist, the restoration process continues to create it as it has done done in the past.
Manual testing, and automated tests added to AbstractIncrementalBackupTest.
=> SOLR-15087: Allow restoration to existing collections

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/response/transform/ChildDocTransformerFactory.java, solr/core/src/test/org/apache/solr/response/transform/TestChildDocTransformerHierarchy.java, solr/solr-ref-guide/src/major-changes-in-solr-9.adoc
The query escaping it did was inconsistent with all other places in Solr where a Lucene query may be provided.
https://issues.apache.org/jira/browse/SOLR-15156
=> SOLR-15156: [child childFilter='...:...'] no longer escapes

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/DoubleValuesSource.java, lucene/queries/src/test/org/apache/lucene/queries/function/TestFunctionScoreQuery.java
When same doc visited twice and when the query is TPI based, an exception can be thrown.  We need to ensure the internal TPI.matches() is never called repeatedly.
=> LUCENE-9762: DoubleValuesSource.fromQuery bug

solr/cloud-dev/cloud.sh
also ensure lucene libs exist
(cherry picked from commit 65da5ed32c940529b27a518deb8ffd1e61aa2e96) (backport)
=> SOLR-14704 add download option to cloud.sh (#1715),

lucene/misc/src/java/org/apache/lucene/misc/store/DirectIODirectory.java, lucene/misc/src/test/org/apache/lucene/misc/store/TestDirectIODirectory.java
TestDirectIODirectory will currently fail if run on an unsupported filesystem (e.g. tmpfs). Add an "assume" that probes if the filesystem supports Direct I/O.
Also tweak javadocs to indicate correct @throws clauses for the IndexInput and IndexOutput. You'll get an IOException (translated from EINVAL) if the filesystem doesn't support it, not a UOE.
cc: @zacharymorn I think you helped on this Directory, if you have time to review, thank you. I know Uwe is currently busy. Mainly I want the lucene tests passing on my machine again :)
=> LUCENE-9774: TestDirectIODirectory fails with EINVAL on some filesystems

solr/CHANGES.txt, solr/solrj/src/resources/apispec/collections.collection.Commands.modify.json
Not sure on rule, snitch, and policy on if they are still real.
Wish we had docs for rule, snitch, and policy in the Solr Ref Guide page under CREATE, appears to be half fixed.
Adding some parameters to make V2 match V1.
I tested the addition of `readOnly` and it worked great.  I didn't test `rule`, `snitch` or `policy` because I don't understand if they are still real or not, and it was unclear to me from reading the Ref Guide if they existed.   Some cleanup needed there!
Manually tested `readOnly` being passed in.
- [ X] I have created a Jira issue …
=> SOLR-15162: Add some parameters to make MODIFYCOLLECTION v1 and v2 more similar.   

gradle/testing/profiling.gradle
The profiler should only be invoked once at the end of the build. During refactoring the buildFinished() hook became nested underneath stuff such as allProjects which causes it to run too many times.
=> Fix tests.profile output to not run many many times

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/component/RealTimeGetComponent.java, solr/core/src/test/org/apache/solr/update/processor/AtomicUpdatesTest.java
Partial (AKA Atomic) updates could encounter "LazyField" instances in the document
cache and not know hot to deal with them when writing the updated doc to the update log.
https://issues.apache.org/jira/browse/SOLR-13034
=> SOLR-13034: RTG sometimes didn't materialize LazyField

lucene/codecs/src/java/org/apache/lucene/codecs/simpletext/SimpleTextVectorReader.java
Fix nightly test failure by implementing  SimpleTextVectorReader#ramBytesUsed
Passed nightly tests in `TestSimpleTextVectorFormat`
```
xichen@Xis-MacBook-Pro lucene-solr % ./gradlew  :lucene:codecs:test --tests="org.apache.lucene.codecs.simpletext.TestSimpleTextVectorFormat" -Ptests.nightly=true
> Task :randomizationInfo
Running tests with randomization seed: tests.seed=7B222A36847DE944
> Task :lucene:codecs:test
:lucene:codecs:test (SUCCESS): 40 test(s), 1 skipped
The slowest tests (exceeding 500 ms) during this run:
5.71s TestSimpleTextVectorFormat.testRamBytesUsed (:lucene:codecs)
BUILD SUCCESSFUL in 12s
16 actionable tasks: 9 executed, 7 up-to-date
```
=> LUCENE-9639: Implements SimpleTextVectorReader#ramBytesUsed

solr/core/src/java/org/apache/solr/cloud/DistributedClusterStateUpdater.java, solr/core/src/java/org/apache/solr/cloud/api/collections/CollectionHandlingUtils.java
add exponential backoff wait time when Compare And Swap fails in distributed cluster state update due to concurrent update
=> SOLR-14928: add exponential backoff for distributed cluster state updates

lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/java/org/apache/lucene/index/IndexWriterConfig.java, lucene/core/src/java/org/apache/lucene/index/IndexWriterEventListener.java, lucene/core/src/java/org/apache/lucene/index/LiveIndexWriterConfig.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterMergePolicy.java, lucene/test-framework/src/java/org/apache/lucene/index/MockIndexWriterEventListener.java, lucene/test-framework/src/java/org/apache/lucene/util/LuceneTestCase.java
Add IndexWriterEventListener interface to track events in IndexWriter
* Passed existing tests
* Added an additional test
Note: precommit is currently failing due to nocommit comment
=> LUCENE-9406: Add IndexWriterEventListener to track events in IndexWriter

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/search/HashQParserPlugin.java, solr/core/src/test/org/apache/solr/search/TestHashQParserPlugin.java
* Simpler
* Don't use Filter (to be removed)
* Do use TwoPhaseIterator, not PostFilter
* Don't pre-compute matching docs (wasteful)
* Support more fields, and more field types
* Faster hash on Strings (avoid Char conversion)
* Stronger hash when using multiple fields
----
@joel-bernstein, I set out to remove the use of Filter in `{!hash}` (because https://issues.apache.org/jira/browse/SOLR-12336 ) and then I saw a bunch of things that I felt could be improved.  Apparently I had nothing better to do this weekend 😄   j/k     WDYT?
=> SOLR-15185: Rewrite Hash query

solr/core/src/test/org/apache/solr/schema/TestPointFields.java
And also restore it's getRandomInts(..,..,bound) semantics to what it was -- positive or negative random values.
https://issues.apache.org/jira/browse/SOLR-15219
@madrob about a year ago you added a static analysis checker and made various changes to comply with its recommendations.  That did not introduce the bug I'm fixing here but nonetheless I can tell that the change recommended by "errorprone" (that you performed) was not the intention of the original code.  The original code wanted random integers within a "bound" that is positive *or negative*.  To make this clearer, I changed the parameter name to `boundPosNeg` and I changed the code to reflect "errorprone" recommendation if you intended the original semantics.
=> SOLR-15219: Fix TestPointFields integer overflow

solr/CHANGES.txt, solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java, solr/solrj/src/java/org/apache/solr/client/solrj/impl/PreemptiveBasicAuthClientBuilderFactory.java, solr/solrj/src/test/org/apache/solr/client/solrj/impl/Http2SolrClientTest.java, solr/solrj/src/test/org/apache/solr/client/solrj/impl/PreemptiveBasicAuthClientBuilderFactoryTest.java
Credentials can now be set explicitly at the client level, or can be read from System properties like in the previous version of the client when using `PreemptiveBasicAuthClientBuilderFactory`. Other implementations of `HttpClientBuilderFactory` can now also be used.
This test also adds a small refactor to `PreemptiveBasicAuthClientBuilderFactory` for better testing.
=> SOLR-15154: Let Http2SolrClient pass Basic Auth credentials to all requests

.github/workflows/docker-test.yml, solr/docker/Dockerfile, solr/docker/build.gradle, solr/docker/scripts/init-var-solr, solr/docker/tests/cases/empty-varsolr-vol-ramdomuser-rootgroup/test.sh, solr/docker/tests/shared.sh
There is currently an issue on the Ubuntu 20.04 github runner, with incorrect ownership being set for the `/var/solr` directory in the docker image.
=> Install ACL package for Solr Docker tests Github action

lucene/core/src/test/org/apache/lucene/search/TestBaseRangeFilter.java, lucene/core/src/test/org/apache/lucene/search/TestMultiTermConstantScore.java, lucene/sandbox/src/test/org/apache/lucene/sandbox/search/TestLongHashSet.java, lucene/spatial-extras/src/test/org/apache/lucene/spatial/TestSpatialExample.java, lucene/spatial-extras/src/test/org/apache/lucene/spatial/TestTestFramework.java
https://issues.apache.org/jira/browse/LUCENE-8626
=> LUCENE-8626: standardise 3 more Lucene test names

dev-tools/doap/solr.rdf
See https://issues.apache.org/jira/browse/SOLR-15163 for background.
The DOAP file is used to generate projects.apache.org, so updating it will fix that directory. See https://projects.apache.org/about.html
=> SOLR-15163 Update DOAP file for solr TLP

solr/CHANGES.txt, solr/core/build.gradle, solr/solrj/build.gradle
It was never truly required there.
Pervasive use of "javabin" reduces the need to care about client-side XML speed.  Better to reduce dependencies and let clients use the libs they want.
https://issues.apache.org/jira/browse/SOLR-2852
BTW I couldn't set "runtimeOnly" for it's inclusion in solr-core because the text tagger explicitly uses it in XmlOffsetCorrector.  I wrote that.  I don't recall if it was performance reasons or if it was for access to location metadata that I otherwise didn't see how to get.
=> SOLR-2852: SolrJ: remove Woodstox dependency

solr/CHANGES.txt, solr/webapp/web/js/angular/controllers/replication.js
Minor bug in the Admin UI Angular code introduced when switching to followers terminology, the underlying API for 8.x still refers to them as slave. In master 9.x branch this is resolved as full migration to new terminology is complete, but any future 8.x builds would have this issue.
This bug prevents the Replication UI for Legacy Replication from loading if polling is enabled and there has been a successful run.
Changed to use the correct JavaScript attribute.
Compiled and ran the UI against my development instance, verified that the UI loads correctly.
=> SOLR-15216 Fix for Invalid Reference to data.followers in Admin UI

lucene/CHANGES.txt, lucene/facet/src/java/org/apache/lucene/facet/FacetsConfig.java, lucene/facet/src/test/org/apache/lucene/facet/TestDrillDownQuery.java, lucene/facet/src/test/org/apache/lucene/facet/sortedset/TestSortedSetDocValuesFacets.java
This PR backports changes from https://github.com/apache/lucene/pull/25 into Lucene 8x
I have run `ant clean; ant precommit; ant test` to validate the changes.
=> LUCENE-9385: (Backporting) Add FacetsConfig option to control which drill-down terms are indexed for a FacetLabel

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/BaseCompositeReader.java, lucene/core/src/java/org/apache/lucene/index/DirectoryReader.java, lucene/core/src/java/org/apache/lucene/index/FilterDirectoryReader.java, lucene/core/src/java/org/apache/lucene/index/IndexWriterConfig.java, lucene/core/src/java/org/apache/lucene/index/LiveIndexWriterConfig.java, lucene/core/src/java/org/apache/lucene/index/MultiReader.java, lucene/core/src/java/org/apache/lucene/index/ParallelCompositeReader.java, lucene/core/src/java/org/apache/lucene/index/StandardDirectoryReader.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterReader.java, lucene/highlighter/src/java/org/apache/lucene/search/uhighlight/UnifiedHighlighter.java, lucene/misc/src/java/org/apache/lucene/index/MultiPassIndexSplitter.java, lucene/replicator/src/java/org/apache/lucene/replicator/nrt/SegmentInfosSearcherManager.java
Custom order for leaves in IndexReader and IndexWriter
1.Add an option to supply a custom leaf sorter for IndexWriter.
A DirectoryReader opened from this IndexWriter will have its leaf
readers sorted with the provided leaf sorter. This is useful for
indices on which it is expected to run many queries with particular
sort criteria (e.g. for time-based indices this is usually a
descending sort on timestamp). Providing leafSorter allows
to speed up early termination for this particular type of
sort queries.
2. Add an option to supply a custom sub-readers sorter for
BaseCompositeReader. In this case sub-readers will be sorted
according to the the provided leafSorter.
3. Add an option to supply a custom leaf sorter for
StandardDirectoryReader. The leaf readers of this
StandardDirectoryReader …
=> LUCENE-9507 Custom order for leaves

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/codecs/lucene84/PForUtil.java
Backport of https://github.com/apache/lucene/pull/48
=> LUCENE-9877: Allow up to 7 exceptions in PForUtil (instead of 3).

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/admin/ZookeeperStatusHandler.java, solr/core/src/test/org/apache/solr/handler/admin/ZookeeperStatusHandlerTest.java
This is a backport to 8.9 of https://github.com/apache/solr/pull/103
See https://issues.apache.org/jira/browse/SOLR-15383
=> SOLR-15383 Solr Zookeeper status page shows green even when a ZK is down

solr/core/src/java/org/apache/solr/index/UninvertDocValuesMergePolicyFactory.java, solr/core/src/java/org/apache/solr/update/SolrIndexConfig.java
I think a `solr/CHANGES.txt` entry for Solr 8.x is not warranted given the specialised use of the class but it would seem nice to provide some indication to anyone using it w.r.t. the class being removed in future Solr 9 via the https://github.com/apache/solr/pull/83 change?
https://issues.apache.org/jira/browse/SOLR-15356
=> SOLR-15356: Deprecate UninvertDocValuesMergePolicyFactory

solr/CHANGES.txt, solr/solrj/src/java/org/apache/solr/common/params/CommonParams.java
Backport of https://github.com/apache/solr/pull/105 targeting 8x (8.9)
=> SOLR-15384 Zookeeper Status handler /admin/zookeeper/status not queryable from SolrJ

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/codecs/compressing/CompressingStoredFieldsReader.java, lucene/core/src/java/org/apache/lucene/codecs/compressing/CompressingStoredFieldsWriter.java, lucene/core/src/java/org/apache/lucene/codecs/compressing/CompressingTermVectorsFormat.java, lucene/core/src/java/org/apache/lucene/codecs/compressing/CompressingTermVectorsReader.java, lucene/core/src/java/org/apache/lucene/codecs/compressing/CompressingTermVectorsWriter.java, lucene/core/src/java/org/apache/lucene/codecs/lucene50/Lucene50TermVectorsFormat.java, lucene/core/src/java/org/apache/lucene/index/SortingTermVectorsConsumer.java, lucene/test-framework/src/java/org/apache/lucene/codecs/compressing/CompressingCodec.java, lucene/test-framework/src/test/org/apache/lucene/codecs/compressing/TestCompressingStoredFieldsFormat.java, lucene/test-framework/src/test/org/apache/lucene/codecs/compressing/TestCompressingTermVectorsFormat.java
This change has baked in master for a while and it is really a performance trap. 
@jpountz mentioned he wanted to backport, but I figure'd I would take a stab, to try to help https://github.com/apache/lucene-solr/pull/2494 along too afterwards. This stuff is tricky, at the same time you get bad performance bugs for many use-cases if we don't fix the issues.
Note that backporting wasn't really walk in the park:
* cherry-pick even with max'd out rename detection doesn't figure out LUCENE-9705 changes that well, some files had to be merged painfully.
* massive style changes due to spotless in master makes for crazy diffs...
* needed to bump version here (i just made it `VERSION_NUMCHUNKS`, rename later for LUCENE-9935 or bump again)
Tests pass locally here for me, but I didn't do anything …
=> LUCENE-9827: backport avoiding wasteful recompression for small segments

lucene/CHANGES.txt, lucene/facet/src/java/org/apache/lucene/facet/StringDocValuesReaderState.java, lucene/facet/src/java/org/apache/lucene/facet/StringValueFacetCounts.java, lucene/facet/src/test/org/apache/lucene/facet/TestStringValueFacetCounts.java
This is a backport of #133 in apache/lucene. Only a couple very minor changes in the unit tests to work with JDK8.
=> LUCENE-9950: New facet counting implementation for general string doc value fields

.github/workflows/ant.yml
This PR re-introduces the `ant precommit` github action for branch_8x, which was removed when "wiping" master branch after the split.
=> Re-introduce ant precommit github action in 8x branch

dev-tools/scripts/smokeTestRelease.py
(Please note this pull request is for `lucene-solr/branch_8_9` branch and after merge the changes would have to be cherry-picked to `lucene-solr/branch_8x` branch and (I'm guessing) also `lucene/main` and `solr/main` branches.)
As part of the 8.9.0 release process @mayya-sharipova reported on the [dev@lucene](https://lists.apache.org/thread.html/rc81568f9006701fb72f9f82f17b89e1be94d3f2a5595ff78186f3b69%40%3Cdev.lucene.apache.org%3E) list that smokeTestRelease.py fails:
> I've also looked at the failure on 8.x branch: "Future release 8.9.0 is
greater than 8.10.0", and it looks like smokeTestRelease.py fails to
correctly compare v8.10.0 > v8.9.0, as (('8', '10', '0') < ('8', '9', '0')).
```
$ cat ./versionToTuple_test.py
#!/usr/bin/env python3
import re
reVersion = …
```
=> Fix 8.9.0 < 8.10.0 comparison in smokeTestRelease.py script.

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/WANDScorer.java, lucene/core/src/test/org/apache/lucene/search/TestWANDScorer.java
Backports changes from apache/lucene#171 into branch_8x
=> LUCENE-9976: Fix WANDScorer assertion error

solr/core/src/test/org/apache/solr/handler/TestRestoreCore.java
https://issues.apache.org/jira/browse/SOLR-15378
Backup/restore doesn't support SimpleTextCodec and because of this testFailedRestore in TestRestoreCore with given seed failed 100%.
Adding SuppressCodecs annotation to the test with SimpleText solved the problem. I have developed this change against current branch_8x and ran unit tests.
Run unit tests.
=> SOLR-15378 Suppress SimpleText codec in TestRestoreCore

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/comparators/DocComparator.java, lucene/core/src/test/org/apache/lucene/search/TestSortOptimization.java
DocComparator should not skip docs with the same docID on multiple
sorts with search after.
Because of the optimization introduced in LUCENE-9449, currently when
searching with sort on [_doc, other fields] with search after,
DocComparator can efficiently skip all docs before and including
the provided [search after docID]. This is a desirable behaviour
in a single index search. But in a distributed search, where multiple
indices have docs with the same docID, and when searching on
[_doc, other fields], the sort optimization should NOT skip
documents with the same docIDs.
This PR fixes this.
Backport for https://github.com/apache/lucene/pull/204
Relates to LUCENE-9449
=> LUCENE-10020 DocComparator don't skip docs of same docID

solr/solr-ref-guide/src/indexing-nested-documents.adoc, solr/solr-ref-guide/src/searching-nested-documents.adoc, solr/solr-ref-guide/src/transforming-result-documents.adoc, solr/solr-ref-guide/src/updating-parts-of-documents.adoc
Since `solr/main` no longer has the equivalent typos this pull request is for `lucene-solr/branch_8x` only.
=> Fix some psuedo->pseudo typos in Solr Ref Guide.

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/search/FieldComparator.java, lucene/core/src/java/org/apache/lucene/search/MultiCollector.java, lucene/core/src/java/org/apache/lucene/search/PositiveScoresOnlyCollector.java, lucene/core/src/java/org/apache/lucene/search/ScoreCachingWrappingScorer.java, lucene/core/src/test/org/apache/lucene/search/TestScoreCachingWrappingScorer.java
=> LUCENE-10036: Add factory method to ScoreCachingWrappingScorer that ensures unnecessary wrapping doesn't occur

lucene/CHANGES.txt, lucene/sandbox/src/java/org/apache/lucene/search/CombinedFieldQuery.java, lucene/sandbox/src/java/org/apache/lucene/search/MultiNormsLeafSimScorer.java, lucene/sandbox/src/test/org/apache/lucene/search/TestCombinedFieldQuery.java
When there's only one field, CombinedFieldQuery will ignore its weight while
scoring. This makes the scoring inconsistent, since the field weight is supposed
to multiply its term frequency.
This PR removes the optimizations around single-field scoring to make sure the
weight is always taken into account. These optimizations are not critical since
it should be uncommon to use CombinedFieldQuery with only one field.
This backport also incorporates the part of LUCENE-9823 that applies to
CombinedFieldQuery. We no longer rewrite single-field queries, which can also
change their scoring.
=> LUCENE-10039: Fix single-field scoring for CombinedFieldQuery

lucene/core/src/java/org/apache/lucene/index/IndexWriter.java, lucene/core/src/java/org/apache/lucene/index/MergeState.java
These maps are no longer useful after LUCENE-8505.
=> LUCENE-10032: Remove leafDocMaps from MergeState

solr/CHANGES.txt, solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java, solr/solr-ref-guide/src/parallel-sql-interface.adoc
backport of https://github.com/apache/solr/pull/237
=> SOLR-15566: Clarify ref guide documentation about SQL queries with SELECT * requiring a LIMIT clause

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/sql/SolrSchema.java, solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java
backport of https://github.com/apache/solr/pull/241
=> SOLR-15570: Include fields declared in the schema in table metadata (SQL) even if they are empty

lucene/CHANGES.txt, lucene/core/src/java/org/apache/lucene/index/DirectoryReader.java, lucene/core/src/test/org/apache/lucene/index/TestIndexWriterReader.java
Provide leaf sorter for directory readers opened from IndexCommit
LUCENE-9507 allowed to provide a leaf sorter for directory readers.
One API that was missed is to allow to provide a leaf sorter
for directory readers opened from an index commit.
This patch adds this API.
=> LUCENE-10027  provide leaf sorter from commit

lucene/CHANGES.txt, lucene/facet/src/java/org/apache/lucene/facet/LongValueFacetCounts.java, lucene/facet/src/test/org/apache/lucene/facet/TestLongValueFacetCounts.java
=> LUCENE-9964: Duplicate long values in a field should only be counted once when using SortedNumericDocValuesFields

lucene/CHANGES.txt, lucene/facet/src/java/org/apache/lucene/facet/DrillSideways.java, lucene/facet/src/test/org/apache/lucene/facet/TestDrillSideways.java
Backport from 9.0. Added `@deprecated` ctors to adhere to backwards compatibility [policy](https://cwiki.apache.org/confluence/display/LUCENE/BackwardsCompatibility)
=> LUCENE-9945: Extend DrillSidewaysResult to expose drillDowns and drillSideways

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/sql/SolrFilter.java, solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java, solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/JDBCStream.java
backport of https://github.com/apache/solr/pull/247
=> SOLR-15576: Allow filtering on ISO-8601 formatted timestamp literals in SQL WHERE clause

lucene/CHANGES.txt, lucene/analysis/common/src/java/org/apache/lucene/analysis/core/FlattenGraphFilter.java, lucene/analysis/common/src/test/org/apache/lucene/analysis/core/TestFlattenGraphFilter.java, lucene/core/src/java/org/apache/lucene/analysis/AutomatonToTokenStream.java, lucene/core/src/test/org/apache/lucene/analysis/TestAutomatonToTokenStream.java
back porting the commits that resolve https://issues.apache.org/jira/browse/LUCENE-9963 to lucene-solr. These changes make no API changes and fix bugs present.
I'm concerned about the formatting as it appears to be different from this branch. The `ant precommit` command from https://cwiki.apache.org/confluence/display/LUCENE/Old+How+to+contribute doesn't appear to exist anymore. I couldn't pick out a build directive that checked for style.
=> Backport Flatten GraphFilter changes from lucene to lucene-solr

lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/JapaneseTokenizer.java, lucene/analysis/kuromoji/src/test/org/apache/lucene/analysis/ja/TestJapaneseTokenizer.java
This is a backport of https://github.com/apache/lucene/pull/254
There is an issue which causes an `AssertionError` in the backtrace step of `JapaneseTokenizer`. If there is a text span of length 1024 (determined by `MAX_BACKTRACE_GAP`) where the regular backtrace is not called, a forced backtrace will be applied. If the partially best path at this point happens to end at the last pos, and since there is always a final backtrace applied at the end, the final backtrace will try to backtrace from and to the same position, causing an AssertionError in `RollingCharBuffer.get()` when it tries to generate an empty buffer.
=> LUCENE-10059: Fix AssertionError in JapaneseTokenizer backtrace

dev-tools/scripts/releaseWizard.py
Old URL to check the apache id gpg key is no longer available.
=> Fix gpg key download in release wizard.

lucene/CHANGES.txt, lucene/codecs/src/java/org/apache/lucene/codecs/simpletext/SimpleTextFieldsReader.java, lucene/codecs/src/java/org/apache/lucene/codecs/simpletext/SimpleTextFieldsWriter.java, lucene/codecs/src/java/org/apache/lucene/codecs/simpletext/SimpleTextSkipReader.java, lucene/codecs/src/java/org/apache/lucene/codecs/simpletext/SimpleTextSkipWriter.java, lucene/core/src/java/org/apache/lucene/codecs/MultiLevelSkipListReader.java, lucene/core/src/java/org/apache/lucene/codecs/MultiLevelSkipListWriter.java
I felt bad that we did not backport LUCENE-10035 to 8.x!
Just because 9.0 is coming soon, I don't think we should cut back on backporting "safe" changes.  Else we get ourselves into this awkward and possibly long-lasting and hard to predict lull leading up to the major release ...
The `git cherry-pick` hit a few interesting conflicts, mostly due to `tidy` styling changes, but a few due to `IndexOutput`/`DataOutput` change that was main-only.  I think I safely resolved all of them, and `ant precommit` and `ant test` inside `lucene` sub-directory pass.  Maybe @wuda0112 or @jpountz wants to take a quick look?
I tried running `ant test -Dtests.codec=SimpleText` in `lucene/core` and all tests (slowly) passed!
=> LUCENE-10035: Simple text codec add multi level skip list data (#224)

lucene/benchmark/conf/collector-small.alg, lucene/benchmark/conf/collector.alg, lucene/benchmark/src/java/org/apache/lucene/benchmark/byTask/tasks/NewAnalyzerTask.java
Hi, I found that the benchmark module hasn't been maintained for a long time. Some scripts were executed incorrectly, and some codes were outdated. I tried to fix a few small bugs, including:
collector-small.alg, collector.alg, NewAnalyzerTask.java.
Execute the following command to verify:
ant run-task -Dtask.alg=conf/analyzer.alg
ant run-task -Dtask.alg=conf/collector-small.alg
ant run-task -Dtask.alg=conf/collector.alg -Dtask.mem=1024M
=> LUCENE-10091 Fix some old errors in the benchmark module

solr/CHANGES.txt, solr/webapp/web/js/angular/controllers/schema-designer.js
backport of https://github.com/apache/solr/pull/291
Testing is manual on FF, Chrome & Safari ... w/ and w/o security enabled.
=> SOLR-15620: Download Config button in Schema Designer screen should not require user to re-login when already authenticated

lucene/core/src/java/org/apache/lucene/search/comparators/NumericComparator.java, lucene/core/src/test/org/apache/lucene/search/TestSortOptimization.java
The first documents of subsequent segments are mistakenly skipped when
sort optimization is enabled. We should initialize maxDocVisited in
NumericComparator to -1 instead of 0.
=> LUCENE-10106: Sort optimization wrongly skip first docs

lucene/core/src/java/org/apache/lucene/search/FieldValueHitQueue.java, lucene/core/src/java/org/apache/lucene/search/SortField.java, lucene/core/src/java/org/apache/lucene/search/SortedNumericSortField.java
This commit moves the responsibility to disable
the numeric sort optimization on comparators to the SortField.
This way we don't need to apply the logic on every top field collectors.
backport for: https://github.com/apache/lucene/pull/291
Co-authored-by: Jim Ferenczi <jim.ferenczi@elastic.co>
=> LUCENE-10089: Disable numeric sort optimization early

dev-tools/scripts/buildAndPushRelease.py, dev-tools/scripts/smokeTestRelease.py, lucene/common-build.xml
https://issues.apache.org/jira/browse/LUCENE-10107
=> LUCENE-10107

lucene/core/src/java/org/apache/lucene/search/FieldValueHitQueue.java, lucene/core/src/java/org/apache/lucene/search/TopFieldCollector.java, lucene/core/src/test/org/apache/lucene/search/TestSortOptimization.java
We should not set single sort when the search_after is non-null;
otherwise, we will incorrectly skip documents whose values are equal to
the value from the search_after and docIDs are greater than the docID
from the search_after.
=> LUCENE-10119: Do not set single sort with search after

lucene/CHANGES.txt, lucene/facet/src/java/org/apache/lucene/facet/sortedset/ConcurrentSortedSetDocValuesFacetCounts.java
=> LUCENE-10134: ConcurrentSortedSetDocValuesFacetCounts shouldn't share liveDocs Bits across threads

dev-tools/scripts/releaseWizard.yaml
I think the reason the `addBackcompatIndexes.py` script failed (`backcompat_master` step) when I built 8.10 was the missing Version info for 8_11, see: https://issues.apache.org/jira/browse/LUCENE-10131
So this PR adds a task to run the `addVersion.py` script for Lucene's main branch (in the split-out repo) so that the `backcompat_master` step works later in the release process.
=> LUCENE-10141: Add the next minor version on Lucene's main branch in the split repo so the backcompat_master task works

solr/core/src/java/org/apache/solr/search/CaffeineCache.java, solr/core/src/java/org/apache/solr/search/JoinQParserPlugin.java, solr/core/src/java/org/apache/solr/search/SolrCache.java, solr/core/src/test/org/apache/solr/search/join/InvalidConfigJoinQueryTest.java
When attempting to run a join query using a synchronous filtercache,
throw an error early with a link to docs rather than a mysterious
IllegalStateException.
Co-Authored-By: Thomas Wöckinger <two@silbergrau.com>
=> SOLR-15762 Error on Join Query with sync cache

solr/CHANGES.txt, solr/core/src/java/org/apache/solr/handler/admin/ShowFileRequestHandler.java, solr/core/src/test/org/apache/solr/handler/admin/ShowFileRequestHandlerTest.java, solr/webapp/web/js/angular/controllers/files.js
* Request .html as text/xml, .css as text/plain and .js as application/javascript
* Highlight css as txt (crashed browser)
* Set extension to 'xml' for managed-schema instead of 'text/xml'
=> SOLR-15804 Allow content-types with ;charset in ShowFileRequestHandler
